### ISSUE TITLE
GO111MODULE should be off when using docker deployment

### ISSUE THREAD

**Issue by huiminghao** [therecipe/qt#1010]
Im useing debian buster/amd64 to test the examples and also a user behind GFW.
Then the GO111MODULE=on should be set for me.
I tried to use Linux to deploy windows_64_shared/windows_64_static/android, but only the windows_64_static target works. The other two show as below.
When set GO111MODULE=off, the other two works.
  

`docker run --rm -i -e IDUG=1001:1001 -v /home/haohuiming/go/src/examples:/media/examples -v /home/haohuiming/go:/media/sf_GOPATH0 -e GO111MODULE=on -e GOPROXY=https://goproxy.cn -e GOBIN=/home/user/work -e GOPATH=/media/sf_GOPATH0:/home/user/work -i therecipe/qt:android qtdeploy -debug -ldflags= -tags= build android /media/examples/deploy/android
time="2019-11-08T06:41:41Z" level=debug msg=Execute _func=RunCmd cmd="go env GOMOD" dir=/media/examples/deploy/android env= name=GOMOD
time="2019-11-08T06:41:42Z" level=debug msg=Execute _func=RunCmd cmd="go list -m -mod=vendor -f {{.Version}} github.com/therecipe/qt" dir=/media/examples/deploy/android env= name="get qt tooling version"
time="2019-11-08T06:41:42Z" level=debug msg=Execute _func=RunCmd cmd="go install -v -tags=no_env github.com/therecipe/qt/cmd/...@v0.0.0-20191101232336-18864661ae4f" dir=/media/examples/deploy/android env= name="re-install qt tooling based on the go.mod version"
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x4c7556]

goroutine 1 [running]:
os.(*Process).wait(0x0, 0x18, 0xc000194000, 0x8)
        /usr/local/go/src/os/exec_unix.go:17 +0x26
os.(*Process).Wait(...)
        /usr/local/go/src/os/exec.go:125
github.com/therecipe/qt/internal/cmd.RestartWithPinnedVersion(0x7ffef6b65e6b, 0x1e)
        /home/user/work/src/github.com/therecipe/qt/internal/cmd/utils.go:202 +0x39a
main.main()
        /home/user/work/src/github.com/therecipe/qt/cmd/qtdeploy/main.go:138 +0x9e5`

**Comment by therecipe** [comment]
Hey

This is probably caused by passing `-e GOBIN=/home/user/work`, to solve this you can either remove the argument or pull the new images containing this fix https://github.com/therecipe/qt/commit/c9ba132582d41d97b3ed69a66ac336529ef8770d#diff-f704287d6fefc8a4eae6299c703f5d63 and also update the `therecipe/qt` version inside your go.mod file.

**Comment by huiminghao** [comment]
This issue still exists now. It has no matter with `-e GOBIN=/home/user/work`.
I update git repo, pulled the laster docker.
```
REPOSITORY               TAG                 IMAGE ID            CREATED             SIZE
therecipe/qt             android             c66490ae6d5a        19 hours ago        6.68GB
therecipe/qt             windows_64_static   d4a786bd167c        20 hours ago        3.53GB
```
With `GO111MODULE=off`, deploy works well. With `on` and get : 
```
haohuiming@iot:~/go/src/examples$ docker run --rm -e IDUG=1001:1001 -v /home/haohuiming/go/src/examples:/media/examples -v /home/haohuiming/go:/media/sf_GOPATH0 -e GO111MODULE=on -e GOPROXY=https://goproxy.cn -e GOPATH=/media/sf_GOPATH0:/home/user/work -i therecipe/qt:android qtdeploy -debug -ldflags= -tags= build android /media/examples/deploy/android
time="2019-11-09T09:27:21Z" level=debug msg=Execute _func=RunCmd cmd="go env GOMOD" dir=/media/examples/deploy/android env= name=GOMOD
time="2019-11-09T09:27:21Z" level=debug msg=Execute _func=RunCmd cmd="go list -m -mod=vendor -f {{.Version}} github.com/therecipe/qt" dir=/media/examples/deploy/android env= name="get qt tooling version"
time="2019-11-09T09:27:21Z" level=debug msg=Execute _func=RunCmd cmd="go install -v -tags=no_env github.com/therecipe/qt/cmd/...@v0.0.0-20191108125410-c9ba132582d4" dir=/media/examples/deploy/android env= name="re-install qt tooling based on the go.mod version"
time="2019-11-09T09:27:21Z" level=debug msg=Execute _func=RunCmd cmd="go env GOMOD" dir=/media/examples/deploy/android env= name=GOMOD
time="2019-11-09T09:27:21Z" level=debug msg="running Deploy" comply=false docker=false fast=false ldFlags= mode=build path=/media/examples/deploy/android quickcompiler=false target=android useuic=true
time="2019-11-09T09:27:21Z" level=debug msg=Execute _func=RunCmdOptional cmd="go get -v -d github.com/therecipe/qt/internal/binding/files/docs/5.13.0" dir=/media/examples/deploy/android env= name="go get docs"
time="2019-11-09T09:27:22Z" level=debug msg=Execute _func=RunCmd cmd="/home/user/work/bin/qtsetup generate android" dir=/media/examples/deploy/android env= name="run setup"
time="2019-11-09T09:27:22Z" level=error msg="failed to run command" _func=RunCmd cmd="/home/user/work/bin/qtsetup generate android" dir=/media/examples/deploy/android env= error="exit status 2" name="run setup"
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x4c7556]

goroutine 1 [running]:
os.(*Process).wait(0x0, 0x2e, 0xc0001444e0, 0x4)
        /usr/local/go/src/os/exec_unix.go:17 +0x26
os.(*Process).Wait(...)
        /usr/local/go/src/os/exec.go:125
github.com/therecipe/qt/internal/cmd.RestartWithPinnedVersion(0xc0000181c0, 0x1e)
        /home/user/work/src/github.com/therecipe/qt/internal/cmd/utils.go:202 +0x39a
main.main()
        /home/user/work/src/github.com/therecipe/qt/cmd/qtsetup/main.go:105 +0xb82
```
envs: 
```
haohuiming@iot:~/go/src/examples$ go env
GO111MODULE="on"
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/haohuiming/.cache/go-build"
GOENV="/home/haohuiming/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/haohuiming/go"
GOPRIVATE=""
GOPROXY="https://goproxy.cn"
GOROOT="/opt/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/opt/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/home/haohuiming/go/src/examples/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build027940156=/tmp/go-build -gno-record-gcc-switches"
haohuiming@iot:~/go/src/examples$ go version
go version go1.13.4 linux/amd64
```
@therecipe

**Comment by therecipe** [comment]
Ah, shit sorry you are right.
I worked on a fix and will try to push the changes in the next 12 hours.

**Comment by therecipe** [comment]
Okay, it should work now with https://github.com/therecipe/qt/commit/6e660afb3df7b12dbe1c0c1f3cf45cb289e47bb3 and https://github.com/therecipe/qt/commit/20ac5c183d881cbcf9995aee98ee75f1fe7a7dfc
But I will report back once the images are done building.

**Comment by huiminghao** [comment]
It works now, GREAT!. With `GO111MODULE=on`, it taks about 140s to deploy, while with `off`, it just taks 100s.

**Comment by therecipe** [comment]
Awesome :)
Yeah, it could be that the first deployment with modules takes a little longer, but all the following deployments shouldn't be that much slower than GOPATH deployments.

**Comment by huiminghao** [comment]
I wathed the processes/top when deploying.

with `GO111MODULE=on`, it always runs qtsetup when deploy, while `off` doesnt.

**Comment by marcovitali** [comment]
Hi @therecipe,

Sorry if I use this issue but I have a similiar problem with GOMOD. Maybe I'm forgetting something.
While I build successfully my app on my local machine (Windows 10 Pro x64) without Docker, I have a similiar problem trying to build it in a GitLab pipeline using a Docker image prepared by me (I use a custom Docker image because in GitLab pipelines services don't work like on Travis CI, so I need an image containing all the stuff).

Docker image has Go and Docker CLI.
```
FROM golang:alpine

RUN apk update && \
    apk add --no-cache git && \
    wget -q https://download.docker.com/linux/static/stable/x86_64/docker-19.03.4.tgz && \
    tar -xzf docker-19.03.4.tgz && \
    cp docker/* /usr/bin/ && \
    rm -r docker && \
    rm docker-19.03.4.tgz
```

The interesting part of the GitLab pipeline is the following:

```
docker pull therecipe/qt:windows_64_static
go get -u -tags=no_env github.com/therecipe/qt/cmd/...
qtdeploy -docker build windows_64_static
```

Follows the error:
```
time="2019-11-14T23:48:59Z" level=error msg="failed to run command" _func=RunCmd cmd="docker run --rm -e IDUG=0:0 -v /go:/media/sf_GOPATH0 -e CI=true -e GOPATH=/home/user/work:/media/sf_GOPATH0 -i therecipe/qt:windows_64_static qtdeploy -debug -ldflags= -tags= build windows /media/sf_GOPATH0/src/maredeployer" dir= env= error="exit status 1" name="deploy binary for windows_64_static on linux with docker"
time="2019-11-14T23:48:59Z" level=debug msg=Execute _func=RunCmd cmd="go env GOMOD" dir=/media/sf_GOPATH0/src/maredeployer env= name=GOMOD
time="2019-11-14T23:48:59Z" level=error msg="failed to run command" _func=RunCmd cmd="go env GOMOD" dir=/media/sf_GOPATH0/src/maredeployer env= error="chdir /media/sf_GOPATH0/src/maredeployer: no such file or directory" name=GOMOD
```

Your help would be very precious.
Thank you in advance.

**Comment by therecipe** [comment]
@huiminghao I made some change which should reduce the qtsetup usage for docker deployments. Maybe pull the latest image and try it again.

@marcovitali 
Hey

I think the problem is that you can't simply mount volumes inside a docker container for another docker container: https://stackoverflow.com/questions/31381322/docker-in-docker-cannot-mount-volume

Maybe try to run something like this
```bash
echo "_HOST_" && ls $(go env GOPATH) && echo "_CONTAINER_" && docker run --rm -v $(go env GOPATH):/media/sf_GOPATH0 -i therecipe/qt:windows_64_static ls /media/sf_GOPATH0
```
to see, if mounting inside the container works 

But the simplest solution is probably to replace your "base" image with `therecipe/qt:windows_64_static` and then clone your repo and run
`qtdeploy build windows path/to/your/repo`

**Comment by marcovitali** [comment]
> But the simplest solution is probably to replace your "base" image with `therecipe/qt:windows_64_static` and then clone your repo and run
> `qtdeploy build windows path/to/your/repo`

It's better for me to use your base image instead of creating a new one.
I tried it before but I was running `qtdeploy` with `-docker` arg.
Now I'm trying your suggestion with `qtdeploy build windows` and it seems to work, but I have the following error:

```
[...]
/tmp/go-build621112816/b001/_x003.o: In function `qInitResources_rcc_maredeployer()':
./rcc.cpp:136: undefined reference to `qRegisterResourceData(int, unsigned char const*, unsigned char const*, unsigned char const*)'
/tmp/go-build621112816/b001/_x003.o: In function `qCleanupResources_rcc_maredeployer()':
./rcc.cpp:145: undefined reference to `qUnregisterResourceData(int, unsigned char const*, unsigned char const*, unsigned char const*)'
./rcc.cpp:145: undefined reference to `qUnregisterResourceData(int, unsigned char const*, unsigned char const*, unsigned char const*)'
/tmp/go-build621112816/b001/_x003.o: In function `qInitResources_rcc_maredeployer()':
./rcc.cpp:136: undefined reference to `qRegisterResourceData(int, unsigned char const*, unsigned char const*, unsigned char const*)'
collect2: error: ld returned 1 exit status
```

Maybe I'm missing something.
Thank you very much.

**Comment by therecipe** [comment]
@marcovitali Did you commit the `rcc*` files, or where they generated by qtdeploy?
Also could you check the content of `rcc_cgo_*`, it should contain more than a few lines and maybe try to deploy this example https://github.com/therecipe/examples/tree/master/basic/qml?

**Comment by marcovitali** [comment]
> Did you commit the `rcc*` files, or where they generated by qtdeploy?

@therecipe I haven't committed `rcc*` files. I have committed `.syso` file generated on my Windows machine with windres.

> maybe try to deploy this example https://github.com/therecipe/examples/tree/master/basic/qml?

I receive exactly the same error.

**Comment by therecipe** [comment]
@marcovitali Sorry for the delay.

Could you run the following docker file for me and post the log?
```dockerfile
FROM therecipe/qt:windows_64_static

RUN /usr/lib/mxe/usr/x86_64-w64-mingw32.static/qt5/bin/rcc -version
RUN /usr/lib/mxe/usr/x86_64-w64-mingw32.static/qt5/bin/moc -version
RUN /usr/lib/mxe/usr/x86_64-w64-mingw32.static/qt5/bin/qmake -version
RUN /usr/lib/mxe/usr/x86_64-w64-mingw32.static/qt5/bin/qmake -query

RUN $(go env GOPATH)/bin/qtsetup check

RUN git clone https://github.com/therecipe/examples.git 
RUN qtdeploy -debug build windows /examples/basic/qml
```

(There is a small chance, that the `GitLab` pipeline server cause issues when running qmake but that's highly unlikely)

**Comment by marcovitali** [comment]
Hi @therecipe,

Below the log:

```
Step 1/8 : FROM therecipe/qt:windows_64_static
windows_64_static: Pulling from therecipe/qt
976a760c94fc: Pulling fs layer
c58992f3c37b: Pulling fs layer
0ca0e5e7f12e: Pulling fs layer
f2a274cc00ca: Pulling fs layer
ecfd008e5705: Pulling fs layer
74dfe1d70011: Pulling fs layer
c3d28149118b: Pulling fs layer
c119af46ad97: Pulling fs layer
cd31d4c76594: Pulling fs layer
68560616d9af: Pulling fs layer
124a2d9fb2b1: Pulling fs layer
947e8b362f4e: Pulling fs layer
5403c2d6c268: Pulling fs layer
f2a274cc00ca: Waiting
ecfd008e5705: Waiting
74dfe1d70011: Waiting
c3d28149118b: Waiting
c119af46ad97: Waiting
cd31d4c76594: Waiting
68560616d9af: Waiting
124a2d9fb2b1: Waiting
947e8b362f4e: Waiting
5403c2d6c268: Waiting
0ca0e5e7f12e: Verifying Checksum
0ca0e5e7f12e: Download complete
c58992f3c37b: Verifying Checksum
c58992f3c37b: Download complete
f2a274cc00ca: Verifying Checksum
f2a274cc00ca: Download complete
976a760c94fc: Verifying Checksum
976a760c94fc: Download complete
ecfd008e5705: Verifying Checksum
ecfd008e5705: Download complete
c3d28149118b: Verifying Checksum
c3d28149118b: Download complete
74dfe1d70011: Verifying Checksum
74dfe1d70011: Download complete
cd31d4c76594: Verifying Checksum
cd31d4c76594: Download complete
68560616d9af: Verifying Checksum
68560616d9af: Download complete
124a2d9fb2b1: Verifying Checksum
124a2d9fb2b1: Download complete
947e8b362f4e: Verifying Checksum
947e8b362f4e: Download complete
c119af46ad97: Verifying Checksum
c119af46ad97: Download complete
5403c2d6c268: Verifying Checksum
5403c2d6c268: Download complete
976a760c94fc: Pull complete
c58992f3c37b: Pull complete
0ca0e5e7f12e: Pull complete
f2a274cc00ca: Pull complete
ecfd008e5705: Pull complete
74dfe1d70011: Pull complete
c3d28149118b: Pull complete
c119af46ad97: Pull complete
cd31d4c76594: Pull complete
68560616d9af: Pull complete
124a2d9fb2b1: Pull complete
947e8b362f4e: Pull complete
5403c2d6c268: Pull complete
Digest: sha256:5c4dd36ba5a294daf3453c78b26a22db43e4ecccbcebe029b9f1c8e90e140b8d
Status: Downloaded newer image for therecipe/qt:windows_64_static
 ---> a242a02f6fb5
Step 2/8 : RUN /usr/lib/mxe/usr/x86_64-w64-mingw32.static/qt5/bin/rcc -version
 ---> Running in c0aa69e1a74f
rcc 5.13.1
Removing intermediate container c0aa69e1a74f
 ---> ab8482ac11af
Step 3/8 : RUN /usr/lib/mxe/usr/x86_64-w64-mingw32.static/qt5/bin/moc -version
 ---> Running in f9e8ab7b0f7a
moc 5.13.1
Removing intermediate container f9e8ab7b0f7a
 ---> ea893b506750
Step 4/8 : RUN /usr/lib/mxe/usr/x86_64-w64-mingw32.static/qt5/bin/qmake -version
 ---> Running in 789d4da175cf
QMake version 3.1
Using Qt version 5.13.1 in /usr/lib/mxe/usr/x86_64-w64-mingw32.static/qt5/lib
Removing intermediate container 789d4da175cf
 ---> 11c4b6302bc1
Step 5/8 : RUN /usr/lib/mxe/usr/x86_64-w64-mingw32.static/qt5/bin/qmake -query
 ---> Running in 905c30304532
QT_SYSROOT:
QT_INSTALL_PREFIX:/usr/lib/mxe/usr/x86_64-w64-mingw32.static/qt5
QT_INSTALL_ARCHDATA:/usr/lib/mxe/usr/x86_64-w64-mingw32.static/qt5
QT_INSTALL_DATA:/usr/lib/mxe/usr/x86_64-w64-mingw32.static/qt5
QT_INSTALL_DOCS:/usr/lib/mxe/usr/x86_64-w64-mingw32.static/qt5/doc
QT_INSTALL_HEADERS:/usr/lib/mxe/usr/x86_64-w64-mingw32.static/qt5/include
QT_INSTALL_LIBS:/usr/lib/mxe/usr/x86_64-w64-mingw32.static/qt5/lib
QT_INSTALL_LIBEXECS:/usr/lib/mxe/usr/x86_64-w64-mingw32.static/qt5/bin
QT_INSTALL_BINS:/usr/lib/mxe/usr/x86_64-w64-mingw32.static/qt5/bin
QT_INSTALL_TESTS:/usr/lib/mxe/usr/x86_64-w64-mingw32.static/qt5/tests
QT_INSTALL_PLUGINS:/usr/lib/mxe/usr/x86_64-w64-mingw32.static/qt5/plugins
QT_INSTALL_IMPORTS:/usr/lib/mxe/usr/x86_64-w64-mingw32.static/qt5/imports
QT_INSTALL_QML:/usr/lib/mxe/usr/x86_64-w64-mingw32.static/qt5/qml
QT_INSTALL_TRANSLATIONS:/usr/lib/mxe/usr/x86_64-w64-mingw32.static/qt5/translations
QT_INSTALL_CONFIGURATION:/usr/lib/mxe/usr/x86_64-w64-mingw32.static/qt5/etc/xdg
QT_INSTALL_EXAMPLES:/usr/lib/mxe/usr/x86_64-w64-mingw32.static/qt5/examples
QT_INSTALL_DEMOS:/usr/lib/mxe/usr/x86_64-w64-mingw32.static/qt5/examples
QT_HOST_PREFIX:/usr/lib/mxe/usr/x86_64-w64-mingw32.static/qt5
QT_HOST_DATA:/usr/lib/mxe/usr/x86_64-w64-mingw32.static/qt5
QT_HOST_BINS:/usr/lib/mxe/usr/x86_64-w64-mingw32.static/qt5/bin
QT_HOST_LIBS:/usr/lib/mxe/usr/x86_64-w64-mingw32.static/qt5/lib
QMAKE_SPEC:linux-g++
QMAKE_XSPEC:win32-g++
QMAKE_VERSION:3.1
QT_VERSION:5.13.1
Removing intermediate container 905c30304532
 ---> a3884ddd8f21
Step 6/8 : RUN $(go env GOPATH)/bin/qtsetup check
 ---> Running in e50bfb1916ce
time="2019-12-03T10:18:35Z" level=info msg="running: 'qtsetup check linux' [docker=false] [vagrant=false]"
time="2019-12-03T10:18:35Z" level=panic msg="failed to find g++, did you install g++?" error="exec: \"g++\": executable file not found in $PATH"
panic: (*logrus.Entry) (0x8a44e0,0xc000081b90)
goroutine 1 [running]:
github.com/sirupsen/logrus.Entry.log(0xc000080070, 0xc00012a660, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/home/user/work/src/github.com/sirupsen/logrus/entry.go:239 +0x2db
github.com/sirupsen/logrus.(*Entry).Log(0xc000081b20, 0x0, 0xc00011d818, 0x1, 0x1)
	/home/user/work/src/github.com/sirupsen/logrus/entry.go:267 +0xeb
github.com/sirupsen/logrus.(*Entry).Logf(0xc000081b20, 0x0, 0x8de08c, 0x26, 0xc00011dab8, 0x2, 0x2)
	/home/user/work/src/github.com/sirupsen/logrus/entry.go:313 +0xe2
github.com/sirupsen/logrus.(*Entry).Panicf(...)
	/home/user/work/src/github.com/sirupsen/logrus/entry.go:351
github.com/therecipe/qt/internal/cmd/setup.Check(0x8ac7db, 0x5, 0x8a0000)
	/home/user/work/src/github.com/therecipe/qt/internal/cmd/setup/check.go:110 +0x2677
main.main()
	/home/user/work/src/github.com/therecipe/qt/cmd/qtsetup/main.go:119 +0x857
The command '/bin/sh -c $(go env GOPATH)/bin/qtsetup check' returned a non-zero code: 2
```


In any case, I solved the problem moving my pipeline from GitLab to Codefresh, but the GitLab behavior is very strange.

**Comment by therecipe** [comment]
@marcovitali 
Ah shit, that should have been `RUN $(go env GOPATH)/bin/qtsetup check windows` sorry.
Nevertheless, it's strange that there were issues running this on GitLabs pipeline.
I will try to look into this once I find some time.
