### ISSUE TITLE
Building on windows.

### ISSUE THREAD

**Issue by AudriusButkevicius** [therecipe/qt#106]
Just followed the instructions via cygwin:

```
Audrius@Audrius Audrius $ qtsetup
time="2016-11-14T20:51:13Z" level=info msg="running setup/prep"
time="2016-11-14T20:51:14Z" level=info msg="running setup/check desktop"
time="2016-11-14T20:51:14Z" level=info msg="GOOS: windows"
time="2016-11-14T20:51:14Z" level=info msg="GOARCH: amd64"
time="2016-11-14T20:51:14Z" level=info msg="GOVERSION: go1.7.3"
time="2016-11-14T20:51:14Z" level=info msg="GOROOT: c:\\go"
time="2016-11-14T20:51:14Z" level=info msg="GOPATH: C:\\Go\\bin"
time="2016-11-14T20:51:14Z" level=info msg="GOBIN: C:\\Go\\bin\\bin"
time="2016-11-14T20:51:14Z" level=info msg="HASH: c61a787766c9bdb6168e5d44397785                                                                                                                                                                                               8743d5981e"
time="2016-11-14T20:51:14Z" level=info msg="QT_DIR: C:\\Qt\\Qt5.7.0"
time="2016-11-14T20:51:14Z" level=info msg="QT_STUB: false"
time="2016-11-14T20:51:14Z" level=info msg="QT_MSYS2: "
time="2016-11-14T20:51:14Z" level=info msg="QT_MSYS2_DIR: "
time="2016-11-14T20:51:14Z" level=info msg="IsMsys2QtDir: false"
time="2016-11-14T20:51:14Z" level=info msg="UseMsys2: false"
time="2016-11-14T20:51:14Z" level=info msg="running setup/generate"
time="2016-11-14T20:51:28Z" level=info msg="generating full qt/core"
time="2016-11-14T20:51:43Z" level=info msg="generating full qt/androidextras"
time="2016-11-14T20:51:44Z" level=info msg="generating full qt/gui"
time="2016-11-14T20:51:58Z" level=info msg="generating full qt/network"
time="2016-11-14T20:52:02Z" level=info msg="generating full qt/xml"
time="2016-11-14T20:52:04Z" level=info msg="generating full qt/dbus"
time="2016-11-14T20:52:05Z" level=info msg="generating full qt/nfc"
time="2016-11-14T20:52:07Z" level=info msg="generating full qt/script"
time="2016-11-14T20:52:08Z" level=info msg="generating full qt/sensors"
time="2016-11-14T20:52:11Z" level=info msg="generating full qt/positioning"
time="2016-11-14T20:52:12Z" level=info msg="generating full qt/widgets"
time="2016-11-14T20:53:01Z" level=info msg="generating full qt/sql"
time="2016-11-14T20:53:03Z" level=info msg="generating full qt/qml"
time="2016-11-14T20:53:04Z" level=info msg="generating full qt/websockets"
time="2016-11-14T20:53:05Z" level=info msg="generating full qt/xmlpatterns"
time="2016-11-14T20:53:06Z" level=info msg="generating full qt/bluetooth"
time="2016-11-14T20:53:07Z" level=info msg="generating full qt/webchannel"
time="2016-11-14T20:53:08Z" level=info msg="generating full qt/svg"
time="2016-11-14T20:53:08Z" level=info msg="generating full qt/multimedia"
time="2016-11-14T20:53:16Z" level=info msg="generating full qt/quick"
time="2016-11-14T20:53:19Z" level=info msg="generating full qt/help"
time="2016-11-14T20:53:22Z" level=info msg="generating full qt/location"
time="2016-11-14T20:53:23Z" level=info msg="generating full qt/scripttools"
time="2016-11-14T20:53:23Z" level=info msg="generating full qt/uitools"
time="2016-11-14T20:53:23Z" level=info msg="generating full qt/winextras"
time="2016-11-14T20:53:24Z" level=info msg="generating full qt/testlib"
time="2016-11-14T20:53:24Z" level=info msg="generating full qt/serialport"
time="2016-11-14T20:53:24Z" level=info msg="generating full qt/serialbus"
time="2016-11-14T20:53:25Z" level=info msg="generating full qt/printsupport"
time="2016-11-14T20:53:27Z" level=info msg="generating full qt/designer"
time="2016-11-14T20:53:31Z" level=info msg="generating full qt/scxml"
time="2016-11-14T20:53:31Z" level=info msg="generating full qt/gamepad"
time="2016-11-14T20:53:32Z" level=info msg="generating full qt/purchasing"
time="2016-11-14T20:53:32Z" level=info msg="generating full qt/sailfish"
time="2016-11-14T20:53:32Z" level=info msg="running setup/install desktop"
time="2016-11-14T20:53:49Z" level=panic msg="failed to install.std\nerror: # runtime/cgo\nc:\\go\\src\\runtime\\cgo\\gcc_libinit_windows.c: In function 'x_cgo_sys_thread_create':\nc:\\go\\src\\runtime\\cgo\\gcc_libinit_windows.c:56:12: error: implicit declaration of function '_beginthread' [-Werror=implicit-function-declaration]\n  thandle = _beginthread(func, 0, arg);\n            ^\nc:\\go\\src\\runtime\\cgo\\gcc_libinit_windows.c:58:69: error: 'errno' undeclared (first use in this function)\n   fprintf(stderr, \"runtime: failed to create new OS thread (%d)\\n\", errno);\n                                                                     ^\nc:\\go\\src\\runtime\\cgo\\gcc_libinit_windows.c:58:69: note: each undeclared identifier is reported only once for each function it appears in\ncc1: all warnings being treated as errors\n\ncmd: &{C:\\go\\bin\\go.exe [go install std] [TEMP=C:\\cygwin64\\tmp GOOS=windows GOARCH=386 CGO_ENABLED=1 PATH=C:\\go\\bin\\bin\\;C:\\cygwin64\\usr\\local\\bin;C:\\cygwin64\\bin;C:\\ProgramData\\Oracle\\Java\\javapath;C:\\Python27;C:\\Python27\\Scripts;C:\\Program Files (x86)\\Intel\\iCLS Client;C:\\Program Files\\Intel\\iCLS Client;C:\\Program Files (x86)\\ActiveState Komodo Edit 8;C:\\Program Files (x86)\\ActiveState Komodo Edit 7;C:\\Windows\\system32;C:\\Windows;C:\\Windows\\System32\\Wbem;C:\\Windows\\System32\\WindowsPowerShell\\v1.0;C:\\Program Files\\Microsoft\\Web Platform Installer;C:\\Program Files (x86)\\Microsoft ASP.NET\\ASP.NET Web Pages\\v1.0;C:\\Program Files\\Microsoft SQL Server\\110\\Tools\\Binn;C:\\Ch\\bin;C:\\Program Files (x86)\\MiKTeX 2.9\\miktex\\bin;C:\\Program Files\\Microsoft Network Monitor 3;C:\\Program Files (x86)\\Autodesk\\Backburner;C:\\Program Files\\Common Files\\Autodesk Shared;C:\\Program Files (x86)\\OpenSSH\\bin;C:\\Program Files\\Mercurial;C:\\Users\\Audrius\\AppData\\Local\\Smartbar\\Application;C:\\Program Files\\Intel\\Intel(R) Management Engine Components\\DAL;C:\\Program Files\\Intel\\Intel(R) Management Engine Components\\IPT;C:\\Program Files (x86)\\Intel\\Intel(R) Management Engine Components\\DAL;C:\\;C:\\Program Files (x86)\\Skype\\Phone;C:\\WINDOWS\\system32;C:\\WINDOWS;C:\\WINDOWS\\System32\\Wbem;C:\\WINDOWS\\System32\\WindowsPowerShell\\v1.0;C:\\Program Files (x86)\\GitExtensions;C:\\Program Files\\Git\\cmd;C:\\Program Files (x86)\\NVIDIA Corporation\\PhysX\\Common;C:\\WINDOWS\\system32;C:\\WINDOWS;C:\\WINDOWS\\System32\\Wbem;C:\\WINDOWS\\System32\\WindowsPowerShell\\v1.0;C:\\Program Files (x86)\\Nmap;C:\\Program Files (x86)\\Android\\android-sdk\\platform-tools;C:\\Users\\Audrius\\AppData\\Roaming\\npm;C:\\Program Files (x86)\\Minimal ADB and Fastboot;C:\\go\\bin;C:\\Program Files (x86)\\Git\\bin;C:\\Program Files (x86)\\Microsoft VS Code\\bin;C:\\Users\\Audrius\\AppData\\Local\\Microsoft\\WindowsApps GOPATH=C:\\Go\\bin GOROOT=c:\\go TMP=C:\\cygwin64\\tmp]  <nil> # runtime/cgo\nc:\\go\\src\\runtime\\cgo\\gcc_libinit_windows.c: In function 'x_cgo_sys_thread_create':\nc:\\go\\src\\runtime\\cgo\\gcc_libinit_windows.c:56:12: error: implicit declaration of function '_beginthread' [-Werror=implicit-function-declaration]\n  thandle = _beginthread(func, 0, arg);\n            ^\nc:\\go\\src\\runtime\\cgo\\gcc_libinit_windows.c:58:69: error: 'errno' undeclared (first use in this function)\n   fprintf(stderr, \"runtime: failed to create new OS thread (%d)\\n\", errno);\n                                                                     ^\nc:\\go\\src\\runtime\\cgo\\gcc_libinit_windows.c:58:69: note: each undeclared identifier is reported only once for each function it appears in\ncc1: all warnings being treated as errors\n # runtime/cgo\nc:\\go\\src\\runtime\\cgo\\gcc_libinit_windows.c: In function 'x_cgo_sys_thread_create':\nc:\\go\\src\\runtime\\cgo\\gcc_libinit_windows.c:56:12: error: implicit declaration of function '_beginthread' [-Werror=implicit-function-declaration]\n  thandle = _beginthread(func, 0, arg);\n            ^\nc:\\go\\src\\runtime\\cgo\\gcc_libinit_windows.c:58:69: error: 'errno' undeclared (first use in this function)\n   fprintf(stderr, \"runtime: failed to create new OS thread (%d)\\n\", errno);\n                                                                     ^\nc:\\go\\src\\runtime\\cgo\\gcc_libinit_windows.c:58:69: note: each undeclared identifier is reported only once for each function it appears in\ncc1: all warnings being treated as errors\n [] <nil> 0xc04600b6e0 exit status 2 <nil> <nil> true [0xc0454168c8 0xc0454168e0 0xc0454168e0] [0xc0454168c8 0xc0454168e0] [0xc0454168d8] [0x4733e0] 0xc0422ed980 <nil>}" error="exit status 2"
panic: (*logrus.Entry) (0x5da120,0xc0437ed900)

goroutine 1 [running]:
panic(0x5da120, 0xc0437ed900)
        c:/go/src/runtime/panic.go:500 +0x1af
github.com/Sirupsen/logrus.Entry.log(0xc042012280, 0xc04600b770, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0xc048ad1900, ...)
        c:/go/bin/src/github.com/Sirupsen/logrus/entry.go:124 +0x42a
github.com/Sirupsen/logrus.(*Entry).Panic(0xc0437ed860, 0xc048ad19a8, 0x1, 0x1)
        c:/go/bin/src/github.com/Sirupsen/logrus/entry.go:169 +0x12b
github.com/Sirupsen/logrus.(*Entry).Panicf(0xc0437ed860, 0x5eb6b4, 0x1e, 0xc048ad1a50, 0x3, 0x3)
        c:/go/bin/src/github.com/Sirupsen/logrus/entry.go:217 +0x108
github.com/therecipe/qt/internal/utils.RunCmd(0xc042076b00, 0x5e4a85, 0xb, 0x0, 0x5e231e)
        c:/go/bin/src/github.com/therecipe/qt/internal/utils/utils.go:71 +0x222
main.install(0x5e358c, 0x7)
        c:/go/bin/src/github.com/therecipe/qt/cmd/qtsetup/install.go:43 +0x215
main.main()
        c:/go/bin/src/github.com/therecipe/qt/cmd/qtsetup/setup.go:81 +0x3e7
```

**Comment by AudriusButkevicius** [comment]
Interestingly via DOS prompt:

```
time="2016-11-14T21:51:15Z" level=panic msg="failed to install.std\nerror: # runtime/cgo\ngcc: error: CreateProcess: No such file or directory\r\n\ncmd: &{go.exe [go install std] [TMP=C:\\Users\\Audrius\\AppData\\Local\\Temp TEMP=C:\\Users\\Audrius\\AppData\\Local\\Temp GOOS=windows GOARCH=386 CGO_ENABLED=1 PATH=C:\\ProgramData\\Oracle\\Java\\javapath;C:\\Python27\\;C:\\Python27\\Scripts;C:\\Program Files (x86)\\Intel\\iCLS Client\\;C:\\Program Files\\Intel\\iCLS Client\\;C:\\Program Files (x86)\\ActiveState Komodo Edit 8\\;C:\\Program Files (x86)\\ActiveState Komodo Edit 7\\;C:\\Windows\\system32;C:\\Windows;C:\\Windows\\System32\\Wbem;C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\;C:\\Program Files\\Microsoft\\Web Platform Installer\\;C:\\Program Files (x86)\\Microsoft ASP.NET\\ASP.NET Web Pages\\v1.0\\;C:\\Program Files\\Microsoft SQL Server\\110\\Tools\\Binn\\;C:\\Ch\\bin;C:\\Program Files (x86)\\MiKTeX 2.9\\miktex\\bin\\;C:\\Program Files\\Microsoft Network Monitor 3\\;C:\\Program Files (x86)\\Autodesk\\Backburner\\;C:\\Program Files\\Common Files\\Autodesk Shared\\;C:\\Program Files (x86)\\OpenSSH\\bin;C:\\Program Files\\Mercurial\\;C:\\Users\\Audrius\\AppData\\Local\\Smartbar\\Application\\;C:\\Program Files\\Intel\\Intel(R) Management Engine Components\\DAL;C:\\Program Files\\Intel\\Intel(R) Management Engine Components\\IPT;C:\\Program Files (x86)\\Intel\\Intel(R) Management Engine Components\\DAL;C:;C:\\Program Files (x86)\\Skype\\Phone\\;C:\\WINDOWS\\system32;C:\\WINDOWS;C:\\WINDOWS\\System32\\Wbem;C:\\WINDOWS\\System32\\WindowsPowerShell\\v1.0\\;C:\\Program Files (x86)\\GitExtensions\\;C:\\Program Files\\Git\\cmd;C:\\Program Files (x86)\\NVIDIA Corporation\\PhysX\\Common;C:\\WINDOWS\\system32;C:\\WINDOWS;C:\\WINDOWS\\System32\\Wbem;C:\\WINDOWS\\System32\\WindowsPowerShell\\v1.0\\;C:\\Go\\bin;C:\\Program Files (x86)\\Nmap;C:\\Program Files (x86)\\Android\\android-sdk\\platform-tools;C:\\Users\\Audrius\\AppData\\Roaming\\npm;C:\\Program Files (x86)\\Minimal ADB and Fastboot;C:\\go\\bin;C:\\Program Files (x86)\\Git\\bin;C:\\Program Files (x86)\\Microsoft VS Code\\bin;C:\\Users\\Audrius\\AppData\\Local\\Microsoft\\WindowsApps;;C:\\go\\bin;c:\\go\\bin\\bin;C:\\Qt\\Qt5.7.0\\Tools\\mingw530_32\\bin GOPATH=C:\\go\\bin GOROOT=C:\\go\\]  <nil> # runtime/cgo\ngcc: error: CreateProcess: No such file or directory\r\n # runtime/cgo\ngcc: error: CreateProcess: No such file or directory\r\n [] <nil> 0xc045ffaa50 exit status 2 <nil> <nil> true [0xc042024610 0xc042024628 0xc042024628] [0xc042024610 0xc042024628] [0xc042024620] [0x4733e0] 0xc044ec2cc0 <nil>}" error="exit status 2"
panic: (*logrus.Entry) (0x5da120,0xc045350460)

goroutine 1 [running]:
panic(0x5da120, 0xc045350460)
        c:/go/src/runtime/panic.go:500 +0x1af
github.com/Sirupsen/logrus.Entry.log(0xc04200e280, 0xc045dea0f0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0xc04fe93900, ...)
        c:/go/bin/src/github.com/Sirupsen/logrus/entry.go:124 +0x42a
github.com/Sirupsen/logrus.(*Entry).Panic(0xc0453500a0, 0xc04fe939a8, 0x1, 0x1)
        c:/go/bin/src/github.com/Sirupsen/logrus/entry.go:169 +0x12b
github.com/Sirupsen/logrus.(*Entry).Panicf(0xc0453500a0, 0x5eb6b4, 0x1e, 0xc04fe93a50, 0x3, 0x3)
        c:/go/bin/src/github.com/Sirupsen/logrus/entry.go:217 +0x108
github.com/therecipe/qt/internal/utils.RunCmd(0xc0492d8c60, 0x5e4a85, 0xb, 0x0, 0x5e231e)
        c:/go/bin/src/github.com/therecipe/qt/internal/utils/utils.go:71 +0x222
main.install(0x5e358c, 0x7)
        c:/go/bin/src/github.com/therecipe/qt/cmd/qtsetup/install.go:43 +0x215
main.main()
        c:/go/bin/src/github.com/therecipe/qt/cmd/qtsetup/setup.go:81 +0x3e7

c:\Go\bin>go version
go version go1.7.3 windows/amd64

c:\Go\bin>go.exe version
go version go1.7.3 windows/amd64
```

I have a pretty broken structure where my GOPATH is actually within the GOROOT/bin directory, yet I don't see how this could be the cause.

**Comment by therecipe** [comment]
Hey

It looks like gcc wasn't found in the cgywin output and therefore it failed to install the std package.
In the DOS output it looks like gcc was found (and is also in your PATH), but it still failed with
`gcc: error: CreateProcess: No such file or directory`.

I haven't tested the binding with cygwin (only msys2 mingw32/64), but it looks like you downloaded the pre-build package from Qt's site, so I would try the following in the normal DOS cmd:

Manually install the "std" package with 
```
set GOARCH=386
set CGO_ENABLED=1
go install std
```
and then re-run the setup as usual.

Or maybe set `QT_STUB=true` and then re-run the setup.

And another idea, would be to move the `C:\\Qt\\Qt5.7.0\\Tools\\mingw530_32\\bin` folder further to the beginning of your PATH.

Or maybe even cleanup the PATH if possible, because windows can't handle to long environment variables. (https://github.com/golang/go/issues/3358)

**Comment by AudriusButkevicius** [comment]
Moving stuff around in PATH works in DOS.
Cygwin is probably borked due to some other reason.
