### ISSUE TITLE
java.lang.UnsatisfiedLinkError: dlopen failed: library "libQt5Qml.so" not found

### ISSUE THREAD

**Issue by bclermont** [therecipe/qt#109]
Host Linux, target android.
Trying to run the binary built with `qtdeploy build android`

```
11-15 22:52:06.544 21238 21238 W linker  : /data/app/org.qtproject.example.go-2/lib/arm/libQt5Gui.so: unused DT entry: type 0x1d arg 0x507ec
11-15 22:52:06.544 21238 21238 W linker  : /data/app/org.qtproject.example.go-2/lib/arm/libQt5Gui.so: unsupported flags DT_FLAGS_1=0x81
11-15 22:52:06.549 21238 21238 W linker  : /data/data/org.qtproject.example.go/qt-reserved-files/plugins/platforms/android/libqtforandroid.so: unused DT entry: type 0x1d arg 0x920e
11-15 22:52:06.549 21238 21238 W linker  : /data/data/org.qtproject.example.go/qt-reserved-files/plugins/platforms/android/libqtforandroid.so: unsupported flags DT_FLAGS_1=0x81
11-15 22:52:06.549 21238 21238 W linker  : /data/data/org.qtproject.example.go/qt-reserved-files/plugins/platforms/android/libqtforandroid.so: is missing DT_SONAME will use basename as a replacement: "libqtforandroid.so"
11-15 22:52:06.553 21238 21238 I Qt      : qt start
11-15 22:52:06.555 21238 21238 W linker  : /data/app/org.qtproject.example.go-2/lib/arm/libgo_base.so: unused DT entry: type 0xf arg 0x118c9
11-15 22:52:06.556 21238 21238 W linker  : /data/app/org.qtproject.example.go-2/lib/arm/libgo_base.so: is missing DT_SONAME will use basename as a replacement: "libgo_base.so"
11-15 22:52:06.556 21238 21238 W linker  : /data/app/org.qtproject.example.go-2/lib/arm/libQt5Widgets.so: unused DT entry: type 0x1d arg 0x6c222
11-15 22:52:06.556 21238 21238 W linker  : /data/app/org.qtproject.example.go-2/lib/arm/libQt5Widgets.so: unsupported flags DT_FLAGS_1=0x81
11-15 22:52:06.557 21238 21238 W System.err: java.lang.reflect.InvocationTargetException
11-15 22:52:06.557 21238 21238 W System.err: 	at java.lang.reflect.Method.invoke(Native Method)
11-15 22:52:06.558 21238 21238 W System.err: 	at org.qtproject.qt5.android.bindings.QtLoader.loadApplication(QtLoader.java:237)
11-15 22:52:06.558 21238 21238 W System.err: 	at org.qtproject.qt5.android.bindings.QtLoader.startApp(QtLoader.java:647)
11-15 22:52:06.558 21238 21238 W System.err: 	at org.qtproject.qt5.android.bindings.QtActivityLoader.onCreate(QtActivityLoader.java:181)
11-15 22:52:06.558 21238 21238 W System.err: 	at org.qtproject.qt5.android.bindings.QtActivity.onCreate(QtActivity.java:269)
11-15 22:52:06.558 21238 21238 W System.err: 	at android.app.Activity.performCreate(Activity.java:6251)
11-15 22:52:06.558 21238 21238 W System.err: 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1108)
11-15 22:52:06.558 21238 21238 W System.err: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2403)
11-15 22:52:06.558 21238 21238 W System.err: 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2510)
11-15 22:52:06.558 21238 21238 W System.err: 	at android.app.ActivityThread.-wrap11(ActivityThread.java)
11-15 22:52:06.558 21238 21238 W System.err: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1363)
11-15 22:52:06.558 21238 21238 W System.err: 	at android.os.Handler.dispatchMessage(Handler.java:102)
11-15 22:52:06.558 21238 21238 W System.err: 	at android.os.Looper.loop(Looper.java:148)
11-15 22:52:06.558 21238 21238 W System.err: 	at android.app.ActivityThread.main(ActivityThread.java:5461)
11-15 22:52:06.558 21238 21238 W System.err: 	at java.lang.reflect.Method.invoke(Native Method)
11-15 22:52:06.558 21238 21238 W System.err: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
11-15 22:52:06.558 21238 21238 W System.err: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
11-15 22:52:06.558 21238 21238 W System.err: Caused by: java.lang.UnsatisfiedLinkError: dlopen failed: library "libQt5Qml.so" not found
11-15 22:52:06.558 21238 21238 W System.err: 	at java.lang.Runtime.load(Runtime.java:332)
11-15 22:52:06.558 21238 21238 W System.err: 	at java.lang.System.load(System.java:1069)
11-15 22:52:06.558 21238 21238 W System.err: 	at org.qtproject.qt5.android.QtNative.loadBundledLibraries(QtNative.java:190)
11-15 22:52:06.558 21238 21238 W System.err: 	at org.qtproject.qt5.android.QtActivityDelegate.loadApplication(QtActivityDelegate.java:504)
11-15 22:52:06.559 21238 21238 W System.err: 	... 17 more
```

**Comment by therecipe** [comment]
Should be fixed with a minor addition to qtdeploy https://github.com/therecipe/qt/commit/87207552307e2b0c632843c4e418ad43866c8f77

Usually `androiddeployqt`, which is invoked by `qtdeploy` should recognize the need for the qml lib and bundle it ...

Do you actually making use of the qml module?
And do you import it in your code?

**Comment by bclermont** [comment]
Yes I do need `qml`, I have an `import "github.com/therecipe/qt/qml"` in one of my `main.go`

**Comment by bclermont** [comment]
I finally been able to run my app as soon as I added

```
utils.RunCmd(exec.Command(copyCmd, filepath.Join(qtLibPath, "libQt5Quick.so"), libPath), fmt.Sprintf("copy libQt5Quick for %v on %v", buildTarget, runtime.GOOS))
```

to `deploy.go`

is this normal? I don't feel `qtdeploy` can actually figure which library it really need to include in the binary.

**Comment by bclermont** [comment]
By the way: https://github.com/bclermont/logrus-android if you want to use logrus with your android apps

**Comment by therecipe** [comment]
Yes qtdeploy doesn't resolve the dependencies on its own, it mainly relies on Qt's `androiddeployqt`, `macdeployqt`, `windeployqt`, ... to figure out what to bundle with the binary.

I could reproduce the missing *.so libs, by removing the dynamic/qml/dynamic.qml dummy file from the example.

So it seems you just need to provide a dummy *.qml file, so that `androiddeployqt` can scan the QML imports and bundle the needed libs (modules + plugins).

Just copy [this](https://github.com/therecipe/qt/blob/master/internal/examples/quick/dynamic/qml/dynamic.qml) dummy qml file into your project/qml folder and it should work.

**Comment by bclermont** [comment]
Problem is solved now
