### ISSUE TITLE
Slot return complex data

### ISSUE THREAD

**Issue by bclermont** [therecipe/qt#111]
I need to fill in QML data from Go, like:

```
//go:generate qtmoc
type QmlBridge struct {
	core.QObject

	_ func() $SOMETHING `slot:"myList"`
}
```

QML:

```
ListView {
    model: QmlBridge.myList()
}
```

I figured that the `cmd/qtmoc` is quite limited. I guess there I should use `unsafe.Pointer`. and tried:

```
//go:generate qtmoc
type QmlBridge struct {
	core.QObject

	_ func(parent *core.QObject) unsafe.Pointer `slot:"myList"`
}

func MyList(parent *core.QObject) unsafe.Pointer {
	model := gui.NewQStandardItemModel2(1, 1, parent)
	x := gui.NewQStandardItem2("X")
	x.SetText("Y")
        model.SetItem(0, 0, x)
	return unsafe.Pointer(model)
}
```

QML:

```
ListView {
    id: listView1
    model: QmlBridge.myList(listView1)
}
```

But I get:

```
panic: runtime error: cgo result has Go pointer

goroutine 1 [running, locked to thread]:
panic(0x55c691710e40, 0xc421f25600)
	/usr/local/go/src/runtime/panic.go:500 +0x1a1
xxx/logic._cgoexpwrap_4fb443b4f7e6_callbackQmlBridge_MyList.func1(0xc420b459a0)
	??:0 +0x3a
xxx/logic._cgoexpwrap_4fb443b4f7e6_callbackQmlBridge_MyList(0x55c69370d390, 0x55c69370fd80, 0xc420442050)
	??:0 +0x6f
github.com/therecipe/qt/quick._Cfunc_QQuickView_SetSource(0x55c6933f75d0, 0x55c69370d730)
	??:0 +0x41
github.com/therecipe/qt/quick.(*QQuickView).SetSource(0xc42034e3a0, 0x55c691c258e0, 0xc420442028)
	yyy/github.com/therecipe/qt/quick/quick-minimal.go:189 +0xf2
```

Is there any way I can return complex data structure to feed models of QML apps?

**Comment by therecipe** [comment]
It should work if you replace `return unsafe.Pointer(model)` with `return model.Pointer()` to get the C++ pointer. But I will test it and report back.

**Comment by bclermont** [comment]
I confirm it's working now!
