### ISSUE TITLE
Errors in file generated by qtmoc

### ISSUE THREAD

**Issue by pekim** [therecipe/qt#112]
This looks like it might be related to the new support for container classes.

```
mainwindow/moc.go:5347: l.len undefined (type C.struct_main_PackedList has no field or method len)
mainwindow/moc.go:5348: l.len undefined (type C.struct_main_PackedList has no field or method len)
mainwindow/moc.go:5349: l.data undefined (type C.struct_main_PackedList has no field or method data)
mainwindow/moc.go:5349: NewConversationsProxyModelFromPointer(l.data).match_atList undefined (type *ConversationsProxyModel has no field or method match_atList)
mainwindow/moc.go:5352: cannot use _Cfunc_ConversationsProxyModel_Match(_cgoCheckPointer0(ptr.Pointer()), _cgoCheckPointer0(core.PointerFromQModelIndex(start)), C.int(int32(role)), _cgoCheckPointer0(core.PointerFromQVariant(value)), C.int(int32(hits)), C.longlong(flags)) (type C.struct_Main_PackedList) as type C.struct_main_PackedList in argument to func literal
mainwindow/moc.go:5360: l.len undefined (type C.struct_main_PackedList has no field or method len)
mainwindow/moc.go:5361: l.len undefined (type C.struct_main_PackedList has no field or method len)
mainwindow/moc.go:5362: l.data undefined (type C.struct_main_PackedList has no field or method data)
mainwindow/moc.go:5362: NewConversationsProxyModelFromPointer(l.data).match_atList undefined (type *ConversationsProxyModel has no field or method match_atList)
mainwindow/moc.go:5365: cannot use _Cfunc_ConversationsProxyModel_MatchDefault(_cgoCheckPointer0(ptr.Pointer()), _cgoCheckPointer0(core.PointerFromQModelIndex(start)), C.int(int32(role)), _cgoCheckPointer0(core.PointerFromQVariant(value)), C.int(int32(hits)), C.longlong(flags)) (type C.struct_Main_PackedList) as type C.struct_main_PackedList in argument to func literal
```

**Comment by therecipe** [comment]
https://github.com/therecipe/qt/commit/50bff136b0425b3fe335f608a9b939ca28ce472b should fix `(type C.struct_Main_PackedList) as type C.struct_main_PackedList`

Hope it works.

**Comment by pekim** [comment]
There are fewer errors now. I'm just left with these.

```
mainwindow/moc.go:5349: NewConversationsProxyModelFromPointer(l.data).match_atList undefined (type *ConversationsProxyModel has no field or method match_atList)
mainwindow/moc.go:5362: NewConversationsProxyModelFromPointer(l.data).match_atList undefined (type *ConversationsProxyModel has no field or method match_atList)
```

**Comment by therecipe** [comment]
I will look into it.

What class did you used to create `ConversationsProxyModel`?

**Comment by pekim** [comment]
It extends `core.QSortFilterProxyModel`. Although it sounds like you might not need that info now.

**Comment by therecipe** [comment]
@pekim 
Hey, I think I solved it.
But I would like to do some testing before I push the changes.

And I'm also off to dinner now.
So I may update the repo later today (in 4+ hours), but can't guarantee it.

**Comment by therecipe** [comment]
Should be fixed (and some similar bug as well) with: https://github.com/therecipe/qt/commit/cf4073023cf3cce446b3d456fe96195e34e07c26

**Comment by pekim** [comment]
No, unfortunately it doesn't seem to be fixed. I've just reinstalled, qtsetup, qtmoc,...

```go
package mainwindow

import "github.com/therecipe/qt/core"

type TestProxyModel struct {
	core.QSortFilterProxyModel
}
```

```
mainwindow/moc.go:16672: NewTestProxyModelFromPointer(l.data).match_atList undefined (type *TestProxyModel has no field or method match_atList)
mainwindow/moc.go:16685: NewTestProxyModelFromPointer(l.data).match_atList undefined (type *TestProxyModel has no field or method match_atList)
```

(Sorry for the delay.)

**Comment by pekim** [comment]
I think that I can probably manage to refactor my code and just use `Connect...` functions. So not urgent.

**Comment by therecipe** [comment]
No problem.

This time it should be fixed for real https://github.com/therecipe/qt/commit/52186384545b1c30ee1a8e58d20739b0148bb19f

Just re-compile qtmoc.

**Comment by pekim** [comment]
Unfortunately not.

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x70 pc=0x4a9d0e]

goroutine 1 [running]:
panic(0x5afcc0, 0xc42000a140)
	/usr/local/go/src/runtime/panic.go:500 +0x1a1
github.com/therecipe/qt/internal/binding/parser.(*Class).add(0xc4258473b0)
	/home/mike/go/src/github.com/therecipe/qt/internal/binding/parser/class.go:144 +0x1dde
github.com/therecipe/qt/internal/binding/parser.(*Module).Prepare(0xc42454d640)
	/home/mike/go/src/github.com/therecipe/qt/internal/binding/parser/module.go:58 +0xa1c
main.moc(0xc424d4eb80, 0x35)
	/home/mike/go/src/github.com/therecipe/qt/cmd/qtmoc/moc.go:225 +0x86d
main.main.func1(0xc424d4eb80, 0x35, 0x69e720, 0xc4240c0680, 0x0, 0x0, 0x0, 0x0)
	/home/mike/go/src/github.com/therecipe/qt/cmd/qtmoc/moc.go:51 +0x15c
path/filepath.walk(0xc424d4eb80, 0x35, 0x69e720, 0xc4240c0680, 0xc420010840, 0x0, 0x0)
	/usr/local/go/src/path/filepath/path.go:351 +0x81
path/filepath.walk(0xc420014284, 0x2f, 0x69e720, 0xc42007d5f0, 0xc420010840, 0x0, 0x413101)
	/usr/local/go/src/path/filepath/path.go:376 +0x344
path/filepath.Walk(0xc420014284, 0x2f, 0xc420010840, 0x1, 0xc42004df01)
	/usr/local/go/src/path/filepath/path.go:398 +0xd5
main.main()
	/home/mike/go/src/github.com/therecipe/qt/cmd/qtmoc/moc.go:63 +0xf1
```

**Comment by pekim** [comment]
It seems that wrapping
```
				for _, sbcf := range ClassMap[sbc].Functions {
					if IsPackedList(sbcf.Output) {
						sbcf.Virtual = "non"
						sbcf.Meta = PLAIN
					}
				}
```
in
```
			if _, ok := ClassMap[sbc]; ok {
			        ...
			}
```
makes the problem go away. But I don't know how reasonable this is.

I think that this might be related to structs with embedded structs where neither struct is qt related.

**Comment by therecipe** [comment]
If it works, then it's good :)

> I think that this might be related to structs with embedded structs where neither struct is qt related.

Usually `qtmoc` should have sorted those out ...
I will look into that.

**Comment by therecipe** [comment]
Should be fixed with https://github.com/therecipe/qt/commit/c9176cdd9a8fa666f6e49e47ed91d287c70a5300

Now qtmoc uses the first non pointer class that inherits core.QObject.

**Comment by pekim** [comment]
Yes, that all seems good now. Thanks.
