### ISSUE TITLE
qtsetup failed to save /interop/interop.go: Access is denied.

### ISSUE THREAD

**Issue by Ryex** [therecipe/qt#1138]
I'm running into some issues getting the qt modules installed.
I've installed qt via MSYS2 per the instruction, set `QT_MSYS2=true` and `QT_MSYS2_ARCH=amd64` in my environment and run `$ENV:GOPATH/bin/qtsetup.exe`

```
time="2020-07-04T04:56:04-06:00" level=info msg="running: 'qtsetup prep'"
time="2020-07-04T04:56:04-06:00" level=info msg="successfully created qtrcc symlink in your PATH (C:\\msys64\\usr\\bin\\qtrcc.exe)"
time="2020-07-04T04:56:04-06:00" level=info msg="successfully created qtmoc symlink in your PATH (C:\\msys64\\usr\\bin\\qtmoc.exe)"        
time="2020-07-04T04:56:04-06:00" level=info msg="successfully created qtminimal symlink in your PATH (C:\\msys64\\usr\\bin\\qtminimal.exe)"
time="2020-07-04T04:56:04-06:00" level=info msg="successfully created qtdeploy symlink in your PATH (C:\\msys64\\usr\\bin\\qtdeploy.exe)"  
time="2020-07-04T04:56:04-06:00" level=info msg="successfully created go symlink in your PATH (C:\\msys64\\usr\\bin\\go.exe)"
time="2020-07-04T04:56:04-06:00" level=info msg="running: 'qtsetup check windows' [docker=false] [vagrant=false]"
time="2020-07-04T04:56:05-06:00" level=info msg="GOOS:                        'windows'"
time="2020-07-04T04:56:05-06:00" level=info msg="GOARCH:                      'amd64'"   
time="2020-07-04T04:56:05-06:00" level=info msg="GOVERSION:                   'go1.14.3'"
time="2020-07-04T04:56:05-06:00" level=info msg="GOROOT:                   *  'C:\\Go'"
time="2020-07-04T04:56:05-06:00" level=info msg="GOPATH:                   *  'C:\\Users\\ryex\\go'"
time="2020-07-04T04:56:05-06:00" level=info msg="GOBIN:                    *  'C:\\Users\\ryex\\go\\bin'"
time="2020-07-04T04:56:05-06:00" level=info msg="GOMOD:                       'E:\\Projects\\Go\\dungeondraft-gopackager\\go.mod'"
time="2020-07-04T04:56:05-06:00" level=info msg="QT_HASH:                     'v0.0.0-20200701200531-7f61353ee73e'"
time="2020-07-04T04:56:05-06:00" level=info msg="QT_API:                      ''"
time="2020-07-04T04:56:05-06:00" level=info msg="QT_VERSION:                  '5.12.0'"
time="2020-07-04T04:56:05-06:00" level=info msg="QT_DIR:                      'C:\\Qt'"
time="2020-07-04T04:56:05-06:00" level=info msg="QT_STUB:                     'false'"
time="2020-07-04T04:56:05-06:00" level=info msg="QT_DEBUG:                    'false'"
time="2020-07-04T04:56:05-06:00" level=info msg="QT_QMAKE_DIR:                ''"
time="2020-07-04T04:56:05-06:00" level=info msg="QT_WEBKIT:                   'false'"
time="2020-07-04T04:56:05-06:00" level=info msg="QT_STATIC:                   'false'"
time="2020-07-04T04:56:05-06:00" level=info msg="QT_GEN_TSD:                  'false'"
time="2020-07-04T04:56:05-06:00" level=info msg="QT_GEN_OPENGL:               'false'"
time="2020-07-04T04:56:05-06:00" level=info msg="QT_GEN_QUICK_EXTRAS:         'false'"
time="2020-07-04T04:56:05-06:00" level=info msg="QT_RESOURCES_BIG:            'false'"
time="2020-07-04T04:56:05-06:00" level=info msg="QT_NOT_CACHED:               'false'"
time="2020-07-04T04:56:05-06:00" level=info msg="QT_DEBUG_CONSOLE:            'false'"
time="2020-07-04T04:56:05-06:00" level=info msg="QT_MSYS2:                 *  'true'"
time="2020-07-04T04:56:05-06:00" level=info msg="QT_MSYS2_DIR:                'C:\\msys64\\mingw64'"
time="2020-07-04T04:56:05-06:00" level=info msg="QT_MSYS2_ARCH:            *  'amd64'"
time="2020-07-04T04:56:05-06:00" level=info msg="QT_MSYS2_STATIC:          *  'true'"
time="2020-07-04T04:56:05-06:00" level=info msg="running: 'qtsetup generate windows' [docker=false] [vagrant=false]"
time="2020-07-04T04:56:15-06:00" level=info msg="generating full qt/core"
time="2020-07-04T04:56:27-06:00" level=info msg="generating full qt/androidextras"
time="2020-07-04T04:56:27-06:00" level=info msg="generating full qt/gui"
time="2020-07-04T04:56:40-06:00" level=info msg="generating full qt/network"
time="2020-07-04T04:56:44-06:00" level=info msg="generating full qt/xml"
time="2020-07-04T04:56:45-06:00" level=info msg="generating full qt/dbus"
time="2020-07-04T04:56:46-06:00" level=info msg="generating full qt/nfc"
time="2020-07-04T04:56:47-06:00" level=info msg="generating full qt/script"
time="2020-07-04T04:56:48-06:00" level=info msg="generating full qt/sensors"
time="2020-07-04T04:56:52-06:00" level=info msg="generating full qt/positioning"
time="2020-07-04T04:56:53-06:00" level=info msg="generating full qt/widgets"
time="2020-07-04T04:57:23-06:00" level=info msg="generating full qt/sql"
time="2020-07-04T04:57:25-06:00" level=info msg="generating full qt/qml"
time="2020-07-04T04:57:26-06:00" level=panic msg="failed to save C:\\Users\\ryex\\go\\pkg\\mod\\github.com\\therecipe\\qt@v0.0.0-20200701200531-7f61353ee73e\\interop\\interop.go" error="open C:\\Users\\ryex\\go\\pkg\\mod\\github.com\\therecipe\\qt@v0.0.0-20200701200531-7f61353ee73e\\interop\\interop.go: Access is denied."
panic: (*logrus.Entry) (0xa77500,0xc01168c2a0)

goroutine 1 [running]:
github.com/sirupsen/logrus.Entry.log(0xc00012e070, 0xc000296a80, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        C:/Users/ryex/go/pkg/mod/github.com/sirupsen/logrus@v1.6.0/entry.go:259 +0x33c
github.com/sirupsen/logrus.(*Entry).Log(0xc01168c230, 0x0, 0xc00718af18, 0x1, 0x1)
        C:/Users/ryex/go/pkg/mod/github.com/sirupsen/logrus@v1.6.0/entry.go:287 +0xf2
github.com/sirupsen/logrus.(*Entry).Logf(0xc01168c230, 0x0, 0xa9d46a, 0x11, 0xc00718afa0, 0x1, 0x1)
        C:/Users/ryex/go/pkg/mod/github.com/sirupsen/logrus@v1.6.0/entry.go:333 +0xe9
github.com/sirupsen/logrus.(*Entry).Panicf(...)
        C:/Users/ryex/go/pkg/mod/github.com/sirupsen/logrus@v1.6.0/entry.go:371
github.com/therecipe/qt/internal/utils.Save(0xc008146850, 0x66, 0xc00727d500, 0x5290, 0x66, 0xf)
        C:/Users/ryex/go/pkg/mod/github.com/therecipe/qt@v0.0.0-20200701200531-7f61353ee73e/internal/utils/utils.go:45 +0x165
github.com/therecipe/qt/internal/binding/templater.GoTemplate(0xa7f7f9, 0x3, 0x0, 0x0, 0xa7f7f9, 0x3, 0xa83fa1, 0x7, 0x0, 0x0, ...)
        C:/Users/ryex/go/pkg/mod/github.com/therecipe/qt@v0.0.0-20200701200531-7f61353ee73e/internal/binding/templater/template_go.go:36 +0xb251
github.com/therecipe/qt/internal/binding/templater.GenModule(0xa7f7f9, 0x3, 0xa83fa1, 0x7, 0x0)
        C:/Users/ryex/go/pkg/mod/github.com/therecipe/qt@v0.0.0-20200701200531-7f61353ee73e/internal/binding/templater/templater.go:65 +0xa8a
github.com/therecipe/qt/internal/cmd/setup.Generate(0xa83fa1, 0x7, 0x0)
        C:/Users/ryex/go/pkg/mod/github.com/therecipe/qt@v0.0.0-20200701200531-7f61353ee73e/internal/cmd/setup/generate.go:57 +0x4e2
main.main()
        C:/Users/ryex/go/pkg/mod/github.com/therecipe/qt@v0.0.0-20200701200531-7f61353ee73e/cmd/qtsetup/main.go:132 +0x69e
```

I've tried running in an admin shell and restarting. does anybody have any ideas as to what's gogin on?

**Comment by NovaVoyager** [comment]
Has the problem been solved？Me too...

**Comment by NJUSTgzy** [comment]
I get the same problem
