### ISSUE TITLE
Quick Touch Screen Presses Causes Segfault

### ISSUE THREAD

**Issue by TheApeMachine** [therecipe/qt#1142]
Hi,

I've been trying for a couple of days to get a handle on an issue I am having.
I have an application that is cross-compiled for rpi3, which has a touch screen connected.

We implemented a mouse area to send a keep-alive signal to Go whenever the screen is touched (to keep it out of standby mode).
However, when you spam the touches, the app crashes with a segfault.
I have read through the issues here, and I don't think it has much to do with the Go code, since I removed the call to the QmlBridge that calls Go.

It all goes well when you do the same thing with a mouse on a laptop or something (cannot really test the mouse on the rpi device).
I have now even removed the MouseArea and the problem still persists. I am quite at a loss here.

```
fatal error: unexpected signal during runtime execution
[signal SIGSEGV: segmentation violation code=0x1 addr=0x14 pc=0x76be8e80]

runtime stack:
runtime.throw(0x7c54d3, 0x2a)
	runtime/panic.go:774 +0x5c
runtime.sigpanic()
	runtime/signal_unix.go:378 +0x398

goroutine 1 [syscall, locked to thread]:
runtime.cgocall(0x66243c, 0x1defe7c, 0x11)
	runtime/cgocall.go:128 +0x5c fp=0x1defe64 sp=0x1defe4c pc=0x81f04
github.com/therecipe/qt/widgets._Cfunc_QApplication_QApplication_Exec(0x0)
	_cgo_gotypes.go:866 +0x38 fp=0x1defe78 sp=0x1defe64 pc=0x4946e0
github.com/therecipe/qt/widgets.(*QApplication).Exec(...)
	github.com/therecipe/qt@v0.0.0-20200701200531-7f61353ee73e/widgets/widgets-minimal.go:838
gitlab.com/[redacted]/monitor/kiosk.(*KioskGUI).Exec(0x1ea4e00)
	gitlab.com/[redacted]/monitor@/kiosk/gui.go:91 +0x180 fp=0x1defe98 sp=0x1defe78 pc=0x4eda58
main.run(0x0, 0x0)
	gitlab.com/[redacted]/monitor@/main.go:101 +0x20c fp=0x1defee8 sp=0x1defe98 pc=0x617b98
main.main()
	gitlab.com/[redacted]/monitor@/main.go:45 +0x118 fp=0x1deffa4 sp=0x1defee8 pc=0x61760c
runtime.main()
	runtime/proc.go:203 +0x208 fp=0x1deffe4 sp=0x1deffa4 pc=0xb0df8
runtime.goexit()
	runtime/asm_arm.s:868 +0x4 fp=0x1deffe4 sp=0x1deffe4 pc=0xdc04c
```

**Comment by TheApeMachine** [comment]
A little update on this, it seems to have something to do with the screen-rotation being overwritten. Once confirmed I will update this ticket.

**Comment by TheApeMachine** [comment]
Yeah, so when we try this: `QT_QPA_GENERIC_PLUGINS=evdevtouch:/dev/input/event0 ./project.sh` even on the most basic examples touching the screen repeatedly makes the application crash.
However, we have found it, so that solves it for us.
