### ISSUE TITLE
MacOS, cgo-less qtbox problem.

### ISSUE THREAD

**Issue by aggyomfg** [therecipe/qt#1157]
Hi! Trying to run widgets example on MacOS Catalina 10.15.6 using new cgo-less bindings.
Extra info:
```
=> uname -a
Darwin MacBook-Pro-aggy.local 19.6.0 Darwin Kernel Version 19.6.0: Thu Jun 18 20:49:00 PDT 2020; root:xnu-6153.141.1~1/RELEASE_X86_64 x86_64
=> go version
go version go1.15 darwin/amd64
```

Steps to reproduce:
```
git clone https://github.com/therecipe/examples.git
cd examples/basic/widgets
go build
./widgets
```
First time its running fine (when downloading qtbox), but when file presents in folder, it fails:
```
looking for qtbox in: /tmp/examples/basic/widgets/qtbox
final qtbox location: /tmp/examples/basic/widgets/qtbox/qtbox
httpRequest error: ["","","core.QCoreApplication_Instance",""] -> Post "http://127.0.0.1:8000/syncCallIntoLocal": dial tcp 127.0.0.1:8000: connect: connection refused
panic: interface conversion: interface {} is nil, not *core.QCoreApplication

goroutine 1 [running, locked to thread]:
github.com/therecipe/qt/core.QCoreApplication_Instance(...)
	/Users/aggy/go/pkg/mod/github.com/therecipe/qt@v0.0.0-20200821140435-d8b4e721393a/core/core.go:8462
github.com/therecipe/qt/widgets.NewQApplication(0x1, 0xc0000121b0, 0x1, 0x1, 0xc000057f78)
	/Users/aggy/go/pkg/mod/github.com/therecipe/qt@v0.0.0-20200821140435-d8b4e721393a/widgets/widgets.go:4930 +0x125
main.main()
	/tmp/examples/basic/widgets/main.go:12 +0x79
```
Problem with running qtbox process, it's trying to run it from subdir `qbox` - `examples/basic/widgets/qtbox/qtbox`, but downloaded binary is `examples/basic/widgets/qtbox`

Please add some additional checks needed for subproces.

Moving file to subdir solves problem, but seems need to be fixed.
Thanks :)

**Comment by therecipe** [comment]
Hey

Sorry for the delay, this should be fixed now with https://github.com/therecipe/qt/commit/6367b9236a241b3c6010c83bbeb243b9156bd893

**Comment by aggyomfg** [comment]
Thank @therecipe
It works now :)
