### ISSUE TITLE
Wallet example "go run" fails

### ISSUE THREAD

**Issue by Ekliptor** [therecipe/qt#1251]
I am trying to run your Wallet example: https://github.com/therecipe/qt/tree/master/internal/examples/showcases/wallet

My system config:
```
MacOS Big Sur 11.5.2
export QT_DIR=/Users/daniel/Qt
export QT_VERSION=5.13.2
export QT_API=5.13.0
```

When I run `qtdeploy` I get the working OSX wallet bundle application under `deploy/darwin`.

However `go run main.go` fails with the following error:

```
panic: reflect: New(nil)

goroutine 1 [running, locked to thread]:
reflect.New(0x0, 0x0, 0x0, 0x0, 0x0)
        reflect/value.go:2351 +0xc1
github.com/therecipe/qt/interop.Z_wrapperFunction(0xc000010048, 0xc00028d9a8)
        github.com/therecipe/qt/interop/interop.go:165 +0x1189
github.com/therecipe/qt/interop._syncCallIntoLocal.func3()
        github.com/therecipe/qt/interop/interop_api.go:64 +0x3c
github.com/therecipe/qt/interop.(*mainThreadHelper).runOnMainThread(...)
        github.com/therecipe/qt/interop/interop_api.go:36
github.com/therecipe/qt/interop.callbackmainThreadHelperc43c44_RunOnMainThread(0x175040b0, 0x16a1aa88a8b0dc80)
        github.com/therecipe/qt/interop/moc.go:106 +0x96
github.com/therecipe/qt/interop._cgoexpwrap_8b577920a12a_callbackmainThreadHelperc43c44_RunOnMainThread(0x175040b0, 0x16a1aa88a8b0dc80)
        _cgo_gotypes.go:696 +0x35
github.com/therecipe/qt/interop._Cfunc_mainThreadHelperc43c44_EventDefault(0x175040b0, 0x178052a0, 0x0)
        _cgo_gotypes.go:375 +0x4a
github.com/therecipe/qt/interop.(*mainThreadHelper).EventDefault.func1(0xc0000aec90, 0x80554a0, 0xc0000b8ef0, 0xc0000b8ef0)
        github.com/therecipe/qt/interop/moc.go:478 +0xb6
github.com/therecipe/qt/interop.(*mainThreadHelper).EventDefault(0xc0000aec90, 0x80554a0, 0xc0000b8ef0, 0x5)
        github.com/therecipe/qt/interop/moc.go:478 +0x4d
github.com/therecipe/qt/interop.callbackmainThreadHelperc43c44_Event(0x175040b0, 0x178052a0, 0x7c2e4d0)
        github.com/therecipe/qt/interop/moc.go:473 +0x11e
github.com/therecipe/qt/interop._cgoexpwrap_8b577920a12a_callbackmainThreadHelperc43c44_Event(0x175040b0, 0x178052a0, 0x175040c0)
        _cgo_gotypes.go:800 +0x35
github.com/therecipe/qt/widgets._Cfunc_QApplication_QApplication_Exec(0x0)
        _cgo_gotypes.go:9078 +0x49
github.com/therecipe/qt/widgets.QApplication_Exec(...)
        github.com/therecipe/qt/widgets/widgets.go:9694
main.main()
        github.com/therecipe/box/full/full_box.go:25 +0x69
httpRequest error: ["",162547584,"","ConnectDestroyed","___REMOTE_CALLBACK___"] -> Post "http://127.0.0.1:8000/syncCallIntoLocal": EOF
httpRequest error: ["","","quick.NewQQuickView","",null] -> Post "http://127.0.0.1:8000/syncCallIntoLocal": dial tcp 127.0.0.1:8000: connect: connection refused
panic: interface conversion: interface {} is nil, not *quick.QQuickView

goroutine 1 [running, locked to thread]:
github.com/therecipe/qt/quick.NewQQuickView(...)
        /Users/daniel/go/pkg/mod/github.com/therecipe/qt@v0.0.0-20200904063919-c0c124a5770d/quick/quick.go:5492
main.main()
        /Users/daniel/go/src/github.com/therecipe/qt/internal/examples/showcases/wallet/main.go:58 +0x10ff

Process finished with the exit code 2
```

I noticed other people having this HTTP server issue too and it was sometimes related to working directory & files: https://github.com/therecipe/qt/issues?q=syncCallIntoLocal

My working directory is the root of the `wallet` project.

**Comment by Ekliptor** [comment]
I got it running by making sure the environment variables are setup properly:
```
export GO111MODULE=off
unset GOROOT
```

My IDE (Goland) was re-setting these every time I pressed "run" so I had to change my project settings there too.
