### ISSUE TITLE
qtsetup on windows recently broke

### ISSUE THREAD

**Issue by jordanorelli** [therecipe/qt#146]
qtsetup is now failing to remove one of the application .exe files when building and running the setup applications:

```
time="2016-12-14T08:15:17-06:00" level=info msg="testing qml\\application"
time="2016-12-14T08:15:17-06:00" level=panic msg="failed to run command" cmd="C:\\Users\\jorelli\\go\\bin\\qtdeploy test desktop C:\\Users\\jorelli\\go\\src\\github.com\\therecipe\\qt\\internal\\examples\\qml\\application " error="exit status 2" func=RunCmd name="test qml\\application" output="time=\"2016-12-14T08:15:17-06:00\" level=panic msg=\"failed to remove C:\\\\Users\\\\jorelli\\\\go\\\\src\\\\github.com\\\\therecipe\\\\qt\\\\internal\\\\examples\\\\qml\\\\application\\\\deploy\\\\windows_minimal\" error=\"remove C:\\\\Users\\\\jorelli\\\\go\\\\src\\\\github.com\\\\therecipe\\\\qt\\\\internal\\\\examples\\\\qml\\\\application\\\\deploy\\\\windows_minimal\\\\application.exe: Access is denied.\"
panic: (*logrus.Entry) (0x60a220,0xc04207a960)

goroutine 1 [running]:
panic(0x60a220, 0xc04207a960)
\tC:/Go/src/runtime/panic.go:500 +0x1af
github.com/Sirupsen/logrus.Entry.log(0xc04207a5a0, 0xc04208f200, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0xc04208d900, ...)
\tC:/Users/jorelli/go/src/github.com/Sirupsen/logrus/entry.go:124 +0x42a
github.com/Sirupsen/logrus.(*Entry).Panic(0xc04207a910, 0xc04208d9f0, 0x1, 0x1)
\tC:/Users/jorelli/go/src/github.com/Sirupsen/logrus/entry.go:169 +0x12b
github.com/Sirupsen/logrus.(*Entry).Panicf(0xc04207a910, 0x617279, 0x13, 0xc04208da68, 0x1, 0x1)
\tC:/Users/jorelli/go/src/github.com/Sirupsen/logrus/entry.go:217 +0x108
github.com/therecipe/qt/internal/utils.RemoveAll(0xc0420ca000, 0x68, 0x613291, 0x4)
\tC:/Users/jorelli/go/src/github.com/therecipe/qt/internal/utils/utils.go:34 +0x139
main.args()
\tC:/Users/jorelli/go/src/github.com/therecipe/qt/cmd/qtdeploy/qtdeploy.go:189 +0xa40
main.main()
\tC:/Users/jorelli/go/src/github.com/therecipe/qt/cmd/qtdeploy/qtdeploy.go:33 +0x2d
"
panic: (*logrus.Entry) (0x5d9ac0,0xc046a87860)

goroutine 1 [running]:
panic(0x5d9ac0, 0xc046a87860)
        C:/Go/src/runtime/panic.go:500 +0x1af
github.com/Sirupsen/logrus.Entry.log(0xc042006230, 0xc0472060c0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0xc047d53900, ...)
        C:/Users/jorelli/go/src/github.com/Sirupsen/logrus/entry.go:124 +0x42a
github.com/Sirupsen/logrus.(*Entry).Panic(0xc046a87810, 0xc047d53a70, 0x1, 0x1)
        C:/Users/jorelli/go/src/github.com/Sirupsen/logrus/entry.go:169 +0x12b
github.com/therecipe/qt/internal/utils.RunCmd(0xc046c40160, 0xc0475be5c0, 0x14, 0x1, 0x1)
        C:/Users/jorelli/go/src/github.com/therecipe/qt/internal/utils/utils.go:81 +0x575
main.test(0x5e302e, 0x7)
        C:/Users/jorelli/go/src/github.com/therecipe/qt/cmd/qtsetup/test.go:68 +0x6dd
main.main()
        C:/Users/jorelli/go/src/github.com/therecipe/qt/cmd/qtsetup/qtsetup.go:82 +0x3ff
```

will take a look

**Comment by therecipe** [comment]
Hey

This can happen on windows, if the application.exe is currently being used.
Could you test it again with `qtsetup test desktop` (this will jump straight to building the examples)

**Comment by jordanorelli** [comment]
yeah, it's a race condition. Skipping all the other tests, I can make it happen every time. It always happens on the qml stuff. I'm taking a crack at fixing it now, cleaning up test.go first.

```
jorelli@LAPTOP-6A5RC78H MINGW64 /c/Users/jorelli/go/src/github.com/therecipe/qt/cmd/qtsetup
$ qtsetup test desktop
time="2016-12-14T10:19:50-06:00" level=info msg="running setup/test desktop (~10min)"
time="2016-12-14T10:19:50-06:00" level=info msg="testing qml\\application"
time="2016-12-14T10:19:51-06:00" level=panic msg="failed to run command" cmd="C:\\Users\\jorelli\\go\\bin\\qtdeploy test desktop C:\\Users\\jorelli\\go\\src\\github.com\\therecipe\\qt\\internal\\examples\\qml\\application" error="exit status 2" func=RunCmd name="test qml\\application" output="time=\"2016-12-14T10:19:51-06:00\" level=panic msg=\"failed to remove C:\\\\Users\\\\jorelli\\\\go\\\\src\\\\github.com\\\\therecipe\\\\qt\\\\internal\\\\examples\\\\qml\\\\application\\\\deploy\\\\windows_minimal\" error=\"remove C:\\\\Users\\\\jorelli\\\\go\\\\src\\\\github.com\\\\therecipe\\\\qt\\\\internal\\\\examples\\\\qml\\\\application\\\\deploy\\\\windows_minimal\\\\application.exe: Access is denied.\" \npanic: (*logrus.Entry) (0x60a220,0xc042191b30)\n\ngoroutine 1 [running]:\npanic(0x60a220, 0xc042191b30)\n\tC:/Go/src/runtime/panic.go:500 +0x1af\ngithub.com/Sirupsen/logrus.Entry.log(0xc04207a550, 0xc042169fb0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0xc04208d900, ...)\n\tC:/Users/jorelli/go/src/github.com/Sirupsen/logrus/entry.go:124 +0x42a\ngithub.com/Sirupsen/logrus.(*Entry).Panic(0xc042191ae0, 0xc04208d9f0, 0x1, 0x1)\n\tC:/Users/jorelli/go/src/github.com/Sirupsen/logrus/entry.go:169 +0x12b\ngithub.com/Sirupsen/logrus.(*Entry).Panicf(0xc042191ae0, 0x617279, 0x13, 0xc04208da68, 0x1, 0x1)\n\tC:/Users/jorelli/go/src/github.com/Sirupsen/logrus/entry.go:217 +0x108\ngithub.com/therecipe/qt/internal/utils.RemoveAll(0xc0420ca000, 0x68, 0x613291, 0x4)\n\tC:/Users/jorelli/go/src/github.com/therecipe/qt/internal/utils/utils.go:34 +0x139\nmain.args()\n\tC:/Users/jorelli/go/src/github.com/therecipe/qt/cmd/qtdeploy/qtdeploy.go:189 +0xa40\nmain.main()\n\tC:/Users/jorelli/go/src/github.com/therecipe/qt/cmd/qtdeploy/qtdeploy.go:33 +0x2d\n"
panic: (*logrus.Entry) (0x5da0c0,0xc0420062d0)

goroutine 1 [running]:
panic(0x5da0c0, 0xc0420062d0)
        C:/Go/src/runtime/panic.go:500 +0x1af
github.com/Sirupsen/logrus.Entry.log(0xc0420780f0, 0xc0420084e0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0xc042037a00, ...)
        C:/Users/jorelli/go/src/github.com/Sirupsen/logrus/entry.go:124 +0x42a
github.com/Sirupsen/logrus.(*Entry).Panic(0xc042006280, 0xc042037ae8, 0x1, 0x1)
        C:/Users/jorelli/go/src/github.com/Sirupsen/logrus/entry.go:169 +0x12b
github.com/therecipe/qt/internal/utils.RunCmd(0xc04207c840, 0xc04205ec00, 0x14, 0x1, 0x1)
        C:/Users/jorelli/go/src/github.com/therecipe/qt/internal/utils/utils.go:81 +0x575
main.test(0xc0420401a0, 0x7)
        C:/Users/jorelli/go/src/github.com/therecipe/qt/cmd/qtsetup/test.go:79 +0x7be
main.main()
        C:/Users/jorelli/go/src/github.com/therecipe/qt/cmd/qtsetup/qtsetup.go:78 +0x2fc
```

**Comment by jordanorelli** [comment]
also can I fix this crazy logrus escaping thing lol

**Comment by therecipe** [comment]
> I'm taking a crack at fixing it now, cleaning up test.go first.

That sounds good :)

> also can I fix this crazy logrus escaping thing lol

I beg you :D

**Comment by jordanorelli** [comment]
I'm gonna close this because it could more accurately be described as "qtsetup doesn't kill child processes". there was a background process that i couldn't find that was screwing things up because i aborted qtsetup and it didn't clean up well at all. restarting fixed it, and i don't think that making qtsetup safe to abort in the middle is really a major priority right now.

**Comment by therecipe** [comment]
Okay, that's good to know :)

**Comment by jordanorelli** [comment]
yeah sometimes on Windows, restarting the machine just magically fixes things. the "tactical reboot".
