### ISSUE TITLE
qt creator setup

### ISSUE THREAD

**Issue by joeblew99** [therecipe/qt#157]
I want to switch from the homebrew version to the full QT so i can do IOS and android builds.
So i downloaded the QT with the included android and ios and set it up. 

But in QT creator i get this:

![screen shot 2016-12-22 at 15 15 50](https://cloud.githubusercontent.com/assets/11999859/21428329/c1ae173c-c859-11e6-8b18-21a3e3ecdcf3.png)

Anyone know how to fix the Yellow warnings ?

qtsetup seems happy though..
````

x-MacBook-Pro:go apple$ $GOPATH/bin/qtsetup
INFO[0000] running setup/prep                           
INFO[0006] running setup/check desktop                  
INFO[0006] VERSION: 0.0.1                               
INFO[0006] GOOS: darwin                                 
INFO[0006] GOARCH: amd64                                
INFO[0006] GOVERSION: go1.7.4                           
INFO[0006] GOROOT: /usr/local/go                        
INFO[0006] GOPATH: /Users/apple/workspace/go            
INFO[0006] GOBIN: /Users/apple/workspace/go/bin         
INFO[0006] HASH: e6da611e3d4403e73a2f5b94d606ad62751ea3cf 
INFO[0006] QT_DIR: /Users/apple/Qt5.7.0                 
INFO[0006] QT_STUB: false                               
INFO[0006] QT_HOMEBREW:                                 
INFO[0006] IsHomeBrewQtDir: false                       
INFO[0006] UseHomebrew: false                           
INFO[0006] QT_DARWIN_DIR: /Users/apple/Qt5.7.0/5.7/clang_64 
INFO[0006] XCODE_DIR: /Applications/Xcode.app           
INFO[0006] MACOS_SDK_DIR: MacOSX10.12.sdk               
INFO[0006] IPHONEOS_SDK_DIR: iPhoneOS10.2.sdk           
INFO[0006] IPHONESIMULATOR_SDK_DIR: iPhoneSimulator10.2.sdk 
````

**Comment by joeblew99** [comment]
This screen might also help

![screen shot 2016-12-22 at 15 22 15](https://cloud.githubusercontent.com/assets/11999859/21428465/79eb78d0-c85a-11e6-9fc4-2857ffd3e5e6.png)

**Comment by therecipe** [comment]
IIRC Xcode8 changed something with the command line tools, that caused problems if you wanted to compile Qt from source. Maybe this is somehow related to your problem.

Found it: http://stackoverflow.com/questions/39544135/qt-does-not-work-since-xcode-8
Maybe this helps.

**Comment by joeblew99** [comment]
That page also say that they fix it in https://download.qt.io/official_releases/qt/5.7/5.7.1/

But this will break on your side right ?

**Comment by therecipe** [comment]
Yes, 5.7.1 currently breaks a few things.
But I have already started to work on it.

**Comment by joeblew99** [comment]
Ok, so lets wait. 

I got OSX, IOS and Android building. Happy chappy.
Next on my list is to try out a golang database that does offline / inline sync.
Then GRPC networking, which should be not too hard.
Then Responsive Layouts. I noticed you dont have any examples handling that and its really needed. For example the same app on IOS, OSX has to handle different screen sizes
Then dynamic layouts.


Dont knwo if you knwo this but one of the demos fails for android

````


x-MacBook-Pro:qt apple$ $GOPATH/bin/qtsetup android
INFO[0000] running setup/prep                           
INFO[0006] running setup/check android                  
INFO[0006] VERSION: 0.0.1                               
INFO[0006] GOOS: darwin                                 
INFO[0006] GOARCH: amd64                                
INFO[0006] GOVERSION: go1.7.4                           
INFO[0006] GOROOT: /usr/local/go                        
INFO[0006] GOPATH: /Users/apple/workspace/go            
INFO[0006] GOBIN: /Users/apple/workspace/go/bin         
INFO[0006] HASH: e6da611e3d4403e73a2f5b94d606ad62751ea3cf 
INFO[0006] QT_DIR: /Users/apple/Qt5.7.0                 
INFO[0006] QT_STUB: false                               
INFO[0006] JDK_DIR: /Library/Java/JavaVirtualMachines/jdk1.8.0_60.jdk/Contents/Home 
INFO[0006] JAVA_HOME: /Library/Java/JavaVirtualMachines/jdk1.8.0_60.jdk/Contents/Home 
INFO[0006] ANDROID_SDK_DIR: /Users/apple/Library/Android/sdk 
INFO[0006] ANDROID_NDK_DIR: /Users/apple/Library/Android/ndk/android-ndk-r13b 
INFO[0006] running setup/generate                       
INFO[0006] running setup/install android                
INFO[0018] running setup/test android (~10min)          
INFO[0018] testing widgets/line_edits                   
INFO[0068] testing widgets/video_player                 
INFO[0127] testing widgets/graphicsscene                
INFO[0171] testing widgets/dropsite                     
PANI[0220] failed to run command                         cmd="/Users/apple/workspace/go/bin/qtdeploy test android /Users/apple/workspace/go/src/github.com/therecipe/qt/internal/examples/widgets/dropsite " error="exit status 2" func=RunCmd name="test widgets/dropsite" output="time=\"2016-12-23T22:22:07+01:00\" level=panic msg=\"failed to run command\" cmd=\"go build -v -ldflags=\\\"-s\\\" \\\"-w\\\" -o /Users/apple/workspace/go/src/github.com/therecipe/qt/internal/examples/widgets/dropsite/deploy/android_minimal/libgo_base.so -tags=\\\"minimal\\\"\\\"android\\\" -installsuffix=android -buildmode c-shared\" error=\"exit status 2\" func=RunCmd name=\"build for android on darwin\" output=\"runtime/internal/sys\\nruntime/internal/atomic\\nruntime\\ninternal/race\\nerrors\\nsync/atomic\\nmath\\nunicode/utf8\\nunicode\\nruntime/cgo\\nsync\\nio\\nsyscall\\nbytes\\nbufio\\nstrconv\\nstrings\\nreflect\\ntime\\nos\\nfmt\\nlog\\ngithub.com/therecipe/qt/internal/android/cgo\\ngithub.com/therecipe/qt\\ngithub.com/therecipe/qt/core\\n# github.com/therecipe/qt/core\\n/tmp/go-build454209985/github.com/therecipe/qt/core/_obj/_cgo_main.c: In function 'crosscall2':\\n/tmp/go-build454209985/github.com/therecipe/qt/core/_obj/_cgo_main.c:2:23: warning: unused parameter 'fn' [-Wunused-parameter]\\n void crosscall2(void(*fn)(void*, int, __SIZE_TYPE__), void *a, int c, __SIZE_TYPE__ ctxt) { }\\n                       ^\\n/tmp/go-build454209985/github.com/therecipe/qt/core/_obj/_cgo_main.c:2:61: warning: unused parameter 'a' [-Wunused-parameter]\\n void crosscall2(void(*fn)(void*, int, __SIZE_TYPE__), void *a, int c, __SIZE_TYPE__ ctxt) { }\\n                                                             ^\\n/tmp/go-build454209985/github.com/therecipe/qt/core/_obj/_cgo_main.c:2:68: warning: unused parameter 'c' [-Wunused-parameter]\\n void crosscall2(void(*fn)(void*, int, __SIZE_TYPE__), void *a, int c, __SIZE_TYPE__ ctxt) { }\\n                                                                    ^\\n/tmp/go-build454209985/github.com/therecipe/qt/core/_obj/_cgo_main.c:2:85: warning: unused parameter 'ctxt' [-Wunused-parameter]\\n void crosscall2(void(*fn)(void*, int, __SIZE_TYPE__), void *a, int c, __SIZE_TYPE__ ctxt) { }\\n                                                                                     ^\\n/tmp/go-build454209985/github.com/therecipe/qt/core/_obj/_cgo_main.c: In function '_cgo_release_context':\\n/tmp/go-build454209985/github.com/therecipe/qt/core/_obj/_cgo_main.c:4:41: warning: unused parameter 'ctxt' [-Wunused-parameter]\\n void _cgo_release_context(__SIZE_TYPE__ ctxt) { }\\n                                         ^\\n/tmp/go-build454209985/github.com/therecipe/qt/core/_obj/_cgo_main.c: In function '_cgo_allocate':\\n/tmp/go-build454209985/github.com/therecipe/qt/core/_obj/_cgo_main.c:6:26: warning: unused parameter 'a' [-Wunused-parameter]\\n void _cgo_allocate(void *a, int c) { }\\n                          ^\\n/tmp/go-build454209985/github.com/therecipe/qt/core/_obj/_cgo_main.c:6:33: warning: unused parameter 'c' [-Wunused-parameter]\\n void _cgo_allocate(void *a, int c) { }\\n                                 ^\\n/tmp/go-build454209985/github.com/therecipe/qt/core/_obj/_cgo_main.c: In function '_cgo_panic':\\n/tmp/go-build454209985/github.com/therecipe/qt/core/_obj/_cgo_main.c:7:23: warning: unused parameter 'a' [-Wunused-parameter]\\n void _cgo_panic(void *a, int c) { }\\n                       ^\\n/tmp/go-build454209985/github.com/therecipe/qt/core/_obj/_cgo_main.c:7:30: warning: unused parameter 'c' [-Wunused-parameter]\\n void _cgo_panic(void *a, int c) { }\\n                              ^\\ngithub.com/therecipe/qt/gui\\n# github.com/therecipe/qt/gui\\n/tmp/go-build454209985/github.com/therecipe/qt/gui/_obj/_cgo_main.c: In function 'crosscall2':\\n/tmp/go-build454209985/github.com/therecipe/qt/gui/_obj/_cgo_main.c:2:23: warning: unused parameter 'fn' [-Wunused-parameter]\\n void crosscall2(void(*fn)(void*, int, __SIZE_TYPE__), void *a, int c, __SIZE_TYPE__ ctxt) { }\\n                       ^\\n/tmp/go-build454209985/github.com/therecipe/qt/gui/_obj/_cgo_main.c:2:61: warning: unused parameter 'a' [-Wunused-parameter]\\n void crosscall2(void(*fn)(void*, int, __SIZE_TYPE__), void *a, int c, __SIZE_TYPE__ ctxt) { }\\n                                                             ^\\n/tmp/go-build454209985/github.com/therecipe/qt/gui/_obj/_cgo_main.c:2:68: warning: unused parameter 'c' [-Wunused-parameter]\\n void crosscall2(void(*fn)(void*, int, __SIZE_TYPE__), void *a, int c, __SIZE_TYPE__ ctxt) { }\\n                                                                    ^\\n/tmp/go-build454209985/github.com/therecipe/qt/gui/_obj/_cgo_main.c:2:85: warning: unused parameter 'ctxt' [-Wunused-parameter]\\n void crosscall2(void(*fn)(void*, int, __SIZE_TYPE__), void *a, int c, __SIZE_TYPE__ ctxt) { }\\n                                                                                     ^\\n/tmp/go-build454209985/github.com/therecipe/qt/gui/_obj/_cgo_main.c: In function '_cgo_release_context':\\n/tmp/go-build454209985/github.com/therecipe/qt/gui/_obj/_cgo_main.c:4:41: warning: unused parameter 'ctxt' [-Wunused-parameter]\\n void _cgo_release_context(__SIZE_TYPE__ ctxt) { }\\n                                         ^\\n/tmp/go-build454209985/github.com/therecipe/qt/gui/_obj/_cgo_main.c: In function '_cgo_allocate':\\n/tmp/go-build454209985/github.com/therecipe/qt/gui/_obj/_cgo_main.c:6:26: warning: unused parameter 'a' [-Wunused-parameter]\\n void _cgo_allocate(void *a, int c) { }\\n                          ^\\n/tmp/go-build454209985/github.com/therecipe/qt/gui/_obj/_cgo_main.c:6:33: warning: unused parameter 'c' [-Wunused-parameter]\\n void _cgo_allocate(void *a, int c) { }\\n                                 ^\\n/tmp/go-build454209985/github.com/therecipe/qt/gui/_obj/_cgo_main.c: In function '_cgo_panic':\\n/tmp/go-build454209985/github.com/therecipe/qt/gui/_obj/_cgo_main.c:7:23: warning: unused parameter 'a' [-Wunused-parameter]\\n void _cgo_panic(void *a, int c) { }\\n                       ^\\n/tmp/go-build454209985/github.com/therecipe/qt/gui/_obj/_cgo_main.c:7:30: warning: unused parameter 'c' [-Wunused-parameter]\\n void _cgo_panic(void *a, int c) { }\\n                              ^\\ngithub.com/therecipe/qt/widgets\\n# github.com/therecipe/qt/widgets\\n/tmp/go-build454209985/github.com/therecipe/qt/widgets/_obj/_cgo_main.c: In function 'crosscall2':\\n/tmp/go-build454209985/github.com/therecipe/qt/widgets/_obj/_cgo_main.c:2:23: warning: unused parameter 'fn' [-Wunused-parameter]\\n void crosscall2(void(*fn)(void*, int, __SIZE_TYPE__), void *a, int c, __SIZE_TYPE__ ctxt) { }\\n                       ^\\n/tmp/go-build454209985/github.com/therecipe/qt/widgets/_obj/_cgo_main.c:2:61: warning: unused parameter 'a' [-Wunused-parameter]\\n void crosscall2(void(*fn)(void*, int, __SIZE_TYPE__), void *a, int c, __SIZE_TYPE__ ctxt) { }\\n                                                             ^\\n/tmp/go-build454209985/github.com/therecipe/qt/widgets/_obj/_cgo_main.c:2:68: warning: unused parameter 'c' [-Wunused-parameter]\\n void crosscall2(void(*fn)(void*, int, __SIZE_TYPE__), void *a, int c, __SIZE_TYPE__ ctxt) { }\\n                                                                    ^\\n/tmp/go-build454209985/github.com/therecipe/qt/widgets/_obj/_cgo_main.c:2:85: warning: unused parameter 'ctxt' [-Wunused-parameter]\\n void crosscall2(void(*fn)(void*, int, __SIZE_TYPE__), void *a, int c, __SIZE_TYPE__ ctxt) { }\\n                                                                                     ^\\n/tmp/go-build454209985/github.com/therecipe/qt/widgets/_obj/_cgo_main.c: In function '_cgo_release_context':\\n/tmp/go-build454209985/github.com/therecipe/qt/widgets/_obj/_cgo_main.c:4:41: warning: unused parameter 'ctxt' [-Wunused-parameter]\\n void _cgo_release_context(__SIZE_TYPE__ ctxt) { }\\n                                         ^\\n/tmp/go-build454209985/github.com/therecipe/qt/widgets/_obj/_cgo_main.c: In function '_cgo_allocate':\\n/tmp/go-build454209985/github.com/therecipe/qt/widgets/_obj/_cgo_main.c:6:26: warning: unused parameter 'a' [-Wunused-parameter]\\n void _cgo_allocate(void *a, int c) { }\\n                          ^\\n/tmp/go-build454209985/github.com/therecipe/qt/widgets/_obj/_cgo_main.c:6:33: warning: unused parameter 'c' [-Wunused-parameter]\\n void _cgo_allocate(void *a, int c) { }\\n                                 ^\\n/tmp/go-build454209985/github.com/therecipe/qt/widgets/_obj/_cgo_main.c: In function '_cgo_panic':\\n/tmp/go-build454209985/github.com/therecipe/qt/widgets/_obj/_cgo_main.c:7:23: warning: unused parameter 'a' [-Wunused-parameter]\\n void _cgo_panic(void *a, int c) { }\\n                       ^\\n/tmp/go-build454209985/github.com/therecipe/qt/widgets/_obj/_cgo_main.c:7:30: warning: unused parameter 'c' [-Wunused-parameter]\\n void _cgo_panic(void *a, int c) { }\\n                              ^\\ngithub.com/therecipe/qt/internal/examples/widgets/dropsite\\n# github.com/therecipe/qt/internal/examples/widgets/dropsite\\n/tmp/go-build454209985/github.com/therecipe/qt/internal/examples/widgets/dropsite/_obj/_cgo_main.c: In function 'crosscall2':\\n/tmp/go-build454209985/github.com/therecipe/qt/internal/examples/widgets/dropsite/_obj/_cgo_main.c:2:23: warning: unused parameter 'fn' [-Wunused-parameter]\\n void crosscall2(void(*fn)(void*, int, __SIZE_TYPE__), void *a, int c, __SIZE_TYPE__ ctxt) { }\\n                       ^\\n/tmp/go-build454209985/github.com/therecipe/qt/internal/examples/widgets/dropsite/_obj/_cgo_main.c:2:61: warning: unused parameter 'a' [-Wunused-parameter]\\n void crosscall2(void(*fn)(void*, int, __SIZE_TYPE__), void *a, int c, __SIZE_TYPE__ ctxt) { }\\n                                                             ^\\n/tmp/go-build454209985/github.com/therecipe/qt/internal/examples/widgets/dropsite/_obj/_cgo_main.c:2:68: warning: unused parameter 'c' [-Wunused-parameter]\\n void crosscall2(void(*fn)(void*, int, __SIZE_TYPE__), void *a, int c, __SIZE_TYPE__ ctxt) { }\\n                                                                    ^\\n/tmp/go-build454209985/github.com/therecipe/qt/internal/examples/widgets/dropsite/_obj/_cgo_main.c:2:85: warning: unused parameter 'ctxt' [-Wunused-parameter]\\n void crosscall2(void(*fn)(void*, int, __SIZE_TYPE__), void *a, int c, __SIZE_TYPE__ ctxt) { }\\n                                                                                     ^\\n/tmp/go-build454209985/github.com/therecipe/qt/internal/examples/widgets/dropsite/_obj/_cgo_main.c: In function '_cgo_release_context':\\n/tmp/go-build454209985/github.com/therecipe/qt/internal/examples/widgets/dropsite/_obj/_cgo_main.c:4:41: warning: unused parameter 'ctxt' [-Wunused-parameter]\\n void _cgo_release_context(__SIZE_TYPE__ ctxt) { }\\n                                         ^\\n/tmp/go-build454209985/github.com/therecipe/qt/internal/examples/widgets/dropsite/_obj/_cgo_main.c: In function '_cgo_allocate':\\n/tmp/go-build454209985/github.com/therecipe/qt/internal/examples/widgets/dropsite/_obj/_cgo_main.c:6:26: warning: unused parameter 'a' [-Wunused-parameter]\\n void _cgo_allocate(void *a, int c) { }\\n                          ^\\n/tmp/go-build454209985/github.com/therecipe/qt/internal/examples/widgets/dropsite/_obj/_cgo_main.c:6:33: warning: unused parameter 'c' [-Wunused-parameter]\\n void _cgo_allocate(void *a, int c) { }\\n                                 ^\\n/tmp/go-build454209985/github.com/therecipe/qt/internal/examples/widgets/dropsite/_obj/_cgo_main.c: In function '_cgo_panic':\\n/tmp/go-build454209985/github.com/therecipe/qt/internal/examples/widgets/dropsite/_obj/_cgo_main.c:7:23: warning: unused parameter 'a' [-Wunused-parameter]\\n void _cgo_panic(void *a, int c) { }\\n                       ^\\n/tmp/go-build454209985/github.com/therecipe/qt/internal/examples/widgets/dropsite/_obj/_cgo_main.c:7:30: warning: unused parameter 'c' [-Wunused-parameter]\\n void _cgo_panic(void *a, int c) { }\\n                              ^\\n# github.com/therecipe/qt/internal/examples/widgets/dropsite\\n./dropsite.go:122: undefined: widgets.QLabel\\n\" \npanic: (*logrus.Entry) (0x216800,0xc4200e2410)\n\ngoroutine 1 [running]:\npanic(0x216800, 0xc4200e2410)\n\t/usr/local/go/src/runtime/panic.go:500 +0x1a1\ngithub.com/Sirupsen/logrus.Entry.log(0xc42000c7d0, 0xc4200d0690, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0xc42004cd00, ...)\n\t/Users/apple/workspace/go/src/github.com/Sirupsen/logrus/entry.go:124 +0x423\ngithub.com/Sirupsen/logrus.(*Entry).Panic(0xc4200e23c0, 0xc42010ede8, 0x1, 0x1)\n\t/Users/apple/workspace/go/src/github.com/Sirupsen/logrus/entry.go:169 +0x124\ngithub.com/therecipe/qt/internal/utils.RunCmd(0xc4200dc2c0, 0xc4200d63c0, 0x1b, 0x2, 0x2)\n\t/Users/apple/workspace/go/src/github.com/therecipe/qt/internal/utils/utils.go:81 +0x56e\nmain.build()\n\t/Users/apple/workspace/go/src/github.com/therecipe/qt/cmd/qtdeploy/qtdeploy.go:470 +0x833\nmain.main()\n\t/Users/apple/workspace/go/src/github.com/therecipe/qt/cmd/qtdeploy/qtdeploy.go:45 +0x144\n"
panic: (*logrus.Entry) (0x1ca500,0xc42010a5a0)

goroutine 1 [running]:
panic(0x1ca500, 0xc42010a5a0)
	/usr/local/go/src/runtime/panic.go:500 +0x1a1
github.com/Sirupsen/logrus.Entry.log(0xc420016280, 0xc4200fc4e0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0xc420037300, ...)
	/Users/apple/workspace/go/src/github.com/Sirupsen/logrus/entry.go:124 +0x423
github.com/Sirupsen/logrus.(*Entry).Panic(0xc42010a550, 0xc420037470, 0x1, 0x1)
	/Users/apple/workspace/go/src/github.com/Sirupsen/logrus/entry.go:169 +0x124
github.com/therecipe/qt/internal/utils.RunCmd(0xc4200dab00, 0xc4200d4da0, 0x15, 0x1, 0x1)
	/Users/apple/workspace/go/src/github.com/therecipe/qt/internal/utils/utils.go:81 +0x56e
main.test(0x7fff5fbff6f6, 0x7)
	/Users/apple/workspace/go/src/github.com/therecipe/qt/cmd/qtsetup/test.go:46 +0x12ae
main.main()
	/Users/apple/workspace/go/src/github.com/therecipe/qt/cmd/qtsetup/qtsetup.go:82 +0x3f8


`````

**Comment by therecipe** [comment]
> Then Responsive Layouts. I noticed you dont have any examples handling that and its really needed. 

I haven't really thought about that yet. But I found a few interesting infos here:
http://doc.qt.io/qt-5/scalability.html, so maybe I will create a small example.

Mh, the error says: `undefined: widgets.QLabel`, did you ran qtdeploy/qtminimal during the test?
Currently you can only run one instance of qtdeploy/qtminimal at the same time, otherwise it can lead to errors like this.

And the tests worked here: https://travis-ci.org/therecipe/qt/jobs/186426519
So, if you can get the dropsite example working with `qtdeploy` then this is nothing to worry about.

**Comment by joeblew99** [comment]
Regarding the error. ah yes i was running qtdeploy from multiple terminals ! so thats good to know. Well picked up.

I will now close this, but raise a new issue about responsive. hope thats ok.
