### ISSUE TITLE
issue qtsetup

### ISSUE THREAD

**Issue by Matt-Texier** [therecipe/qt#201]
Hi,

I am having a segmentation fault using qtseup ... I saw that it has been pointed 6 days ago and normally fixed ... but doesn't work for me !

It is me having a problem ?

Thanks Matthieu.

```
matthieu@matt-dev-box:~/go-work/bin$ sudo -E /home/matthieu/go-work/bin/qtsetup 
INFO[0000] running setup/prep                           
INFO[0000] running setup/check desktop                  
INFO[0000] VERSION: 0.0.4                               
INFO[0000] GOOS: linux                                  
INFO[0000] GOARCH: amd64                                
INFO[0000] GOVERSION: go1.7.3                           
INFO[0000] GOROOT: /usr/local/go                        
INFO[0000] GOPATH: /home/matthieu/go-work               
INFO[0000] GOBIN: /home/matthieu/go-work/bin            
INFO[0000] HASH: b376bbbc1034b787475724ab15815b3aefa01450 
WARN[0000] Couldn't get valid application name 'Qt' in /home/matthieu/Qt/components.xml 
panic: runtime error: index out of range

goroutine 1 [running]:
panic(0x6cc180, 0xc42000c180)
	/usr/local/go/src/runtime/panic.go:500 +0x1a1
github.com/therecipe/qt/internal/utils.QT_VERSION(0x0, 0x0)
	/home/matthieu/go-work/src/github.com/therecipe/qt/internal/utils/env.go:71 +0x6e3
github.com/therecipe/qt/internal/cmd/setup.check(0x70f9ac, 0x7)
	/home/matthieu/go-work/src/github.com/therecipe/qt/internal/cmd/setup/check.go:30 +0xaee
github.com/therecipe/qt/internal/cmd/setup.Setup(0x70e7c4, 0x4, 0x70f9ac, 0x7)
	/home/matthieu/go-work/src/github.com/therecipe/qt/internal/cmd/setup/setup.go:7 +0x136
main.main()
	/home/matthieu/go-work/src/github.com/therecipe/qt/cmd/qtsetup/qtsetup.go:37 +0x27b
matthieu@matt-dev-box:~/go-work/bin$
```

**Comment by Matt-Texier** [comment]
Forgot to mention that it happens on linux server ...
Thanks Matt.

**Comment by therecipe** [comment]
Hey

Yes, there were some changes. I will look into it.
Do you use the "official" Qt package or your system package managers version of Qt?

Regardless of that, you should be able to work around this by setting `QT_VERSION=5.7.0` before running qtsetup.

**Comment by Matt-Texier** [comment]
Hey,

I do use the 5.7.0 installed from Qt web site...

Thanks for your help ... I getting close to have a small application running (Networking stuff with BGP). I am looking at putting it as open source.

Thanks Matt.

**Comment by therecipe** [comment]
>I do use the 5.7.0 installed from Qt web site...

Okay, then I really have to look into it.
But it works now with QT_VERSION?

>Thanks for your help ... I getting close to have a small application running (Networking stuff with BGP). I am looking at putting it as open source.

Great :) let me know if you want to have a link in the readme or something (or just send a PR and I will merge it)

**Comment by Matt-Texier** [comment]
Ha ok, I didn't realize I had to add an ENV variable ... Sorry for that.

Process is on going ... Just had a small issue for now:
ERRO[0006] failed to load /home/matthieu/Qt/Docs/Qt-5.7/qtdatavisualization/qtdatavisualization.index  error="open /home/matthieu/Qt/Docs/Qt-5.7/qtdatavisualization/qtdatavisualization.index: no such file or directory"
ERRO[0006] failed to load /home/matthieu/Qt/Docs/Qt-5.7/qtcharts/qtcharts.index  error="open /home/matthieu/Qt/Docs/Qt-5.7/qtcharts/qtcharts.index: no such file or directory"

It hasn't broken the install and process is still running...

I'll let you know.

Thanks Matt.

**Comment by therecipe** [comment]
Okay.

And these:
```
ERRO[0006] failed to load /home/matthieu/Qt/Docs/Qt-5.7/qtdatavisualization/qtdatavisualization.index error="open /home/matthieu/Qt/Docs/Qt-5.7/qtdatavisualization/qtdatavisualization.index: no such file or directory"
ERRO[0006] failed to load /home/matthieu/Qt/Docs/Qt-5.7/qtcharts/qtcharts.index error="open /home/matthieu/Qt/Docs/Qt-5.7/qtcharts/qtcharts.index: no such file or directory"
```
are just warnings and nothing to worry about.

**Comment by Matt-Texier** [comment]
Looks I have another issue ...

```
ERRO[0153] failed to run command                         cmd="go install -p 3 -v github.com/therecipe/qt/core" error="exec: \"go\": executable file not found in $PATH" func=RunCmdOptional name=install.core

INFO[0153] installing full qt/androidextras             
ERRO[0153] failed to run command                         cmd="go install -p 3 -v github.com/therecipe/qt/androidextras" error="exec: \"go\": executable file not found in $PATH" func=RunCmdOptional name=install.androidextras

INFO[0153] installing full qt/gui                       
ERRO[0153] failed to run command                         cmd="go install -p 3 -v github.com/therecipe/qt/gui" error="exec: \"go\": executable file not found in $PATH" func=RunCmdOptional name=install.gui

INFO[0153] installing full qt/network                   
ERRO[0153] failed to run command                         cmd="go install -p 3 -v github.com/therecipe/qt/network" error="exec: \"go\": executable file not found in $PATH" func=RunCmdOptional name=install.network

INFO[0153] installing full qt/xml                       
ERRO[0153] failed to run command                         cmd="go install -p 3 -v github.com/therecipe/qt/xml" error="exec: \"go\": executable file not found in $PATH" func=RunCmdOptional name=install.xml

INFO[0153] installing full qt/dbus                      
ERRO[0153] failed to run command                         cmd="go install -p 3 -v github.com/therecipe/qt/dbus" error="exec: \"go\": executable file not found in $PATH" func=RunCmdOptional name=install.dbus

INFO[0153] installing full qt/nfc                       
ERRO[0153] failed to run command                         cmd="go install -p 3 -v github.com/therecipe/qt/nfc" error="exec: \"go\": executable file not found in $PATH" func=RunCmdOptional name=install.nfc

INFO[0153] installing full qt/script                    
ERRO[0153] failed to run command                         cmd="go install -p 3 -v github.com/therecipe/qt/script" error="exec: \"go\": executable file not found in $PATH" func=RunCmdOptional name=install.script

INFO[0153] installing full qt/sensors                   
ERRO[0153] failed to run command                         cmd="go install -p 3 -v github.com/therecipe/qt/sensors" error="exec: \"go\": executable file not found in $PATH" func=RunCmdOptional name=install.sensors

INFO[0153] installing full qt/positioning               
ERRO[0153] failed to run command                         cmd="go install -p 3 -v github.com/therecipe/qt/positioning" error="exec: \"go\": executable file not found in $PATH" func=RunCmdOptional name=install.positioning

INFO[0153] installing full qt/widgets                   
ERRO[0153] failed to run command                         cmd="go install -p 3 -v github.com/therecipe/qt/widgets" error="exec: \"go\": executable file not found in $PATH" func=RunCmdOptional name=install.widgets

INFO[0153] installing full qt/sql                       
ERRO[0153] failed to run command                         cmd="go install -p 3 -v github.com/therecipe/qt/sql" error="exec: \"go\": executable file not found in $PATH" func=RunCmdOptional name=install.sql

INFO[0153] installing full qt/qml                       
ERRO[0153] failed to run command                         cmd="go install -p 3 -v github.com/therecipe/qt/qml" error="exec: \"go\": executable file not found in $PATH" func=RunCmdOptional name=install.qml

INFO[0153] installing full qt/websockets                
ERRO[0153] failed to run command                         cmd="go install -p 3 -v github.com/therecipe/qt/websockets" error="exec: \"go\": executable file not found in $PATH" func=RunCmdOptional name=install.websockets

INFO[0153] installing full qt/xmlpatterns               
ERRO[0153] failed to run command                         cmd="go install -p 3 -v github.com/therecipe/qt/xmlpatterns" error="exec: \"go\": executable file not found in $PATH" func=RunCmdOptional name=install.xmlpatterns

INFO[0153] installing full qt/bluetooth                 
ERRO[0153] failed to run command                         cmd="go install -p 3 -v github.com/therecipe/qt/bluetooth" error="exec: \"go\": executable file not found in $PATH" func=RunCmdOptional name=install.bluetooth

INFO[0153] installing full qt/webchannel                
ERRO[0153] failed to run command                         cmd="go install -p 3 -v github.com/therecipe/qt/webchannel" error="exec: \"go\": executable file not found in $PATH" func=RunCmdOptional name=install.webchannel

INFO[0153] installing full qt/svg                       
ERRO[0153] failed to run command                         cmd="go install -p 3 -v github.com/therecipe/qt/svg" error="exec: \"go\": executable file not found in $PATH" func=RunCmdOptional name=install.svg

INFO[0153] installing full qt/multimedia                
ERRO[0153] failed to run command                         cmd="go install -p 3 -v github.com/therecipe/qt/multimedia" error="exec: \"go\": executable file not found in $PATH" func=RunCmdOptional name=install.multimedia

INFO[0153] installing full qt/quick                     
ERRO[0153] failed to run command                         cmd="go install -p 3 -v github.com/therecipe/qt/quick" error="exec: \"go\": executable file not found in $PATH" func=RunCmdOptional name=install.quick

INFO[0153] installing full qt/help                      
ERRO[0153] failed to run command                         cmd="go install -p 3 -v github.com/therecipe/qt/help" error="exec: \"go\": executable file not found in $PATH" func=RunCmdOptional name=install.help

INFO[0153] installing full qt/location                  
ERRO[0153] failed to run command                         cmd="go install -p 3 -v github.com/therecipe/qt/location" error="exec: \"go\": executable file not found in $PATH" func=RunCmdOptional name=install.location

INFO[0153] installing full qt/scripttools               
ERRO[0153] failed to run command                         cmd="go install -p 3 -v github.com/therecipe/qt/scripttools" error="exec: \"go\": executable file not found in $PATH" func=RunCmdOptional name=install.scripttools

INFO[0153] installing full qt/uitools                   
ERRO[0153] failed to run command                         cmd="go install -p 3 -v github.com/therecipe/qt/uitools" error="exec: \"go\": executable file not found in $PATH" func=RunCmdOptional name=install.uitools

INFO[0153] installing full qt/x11extras                 
ERRO[0153] failed to run command                         cmd="go install -p 3 -v github.com/therecipe/qt/x11extras" error="exec: \"go\": executable file not found in $PATH" func=RunCmdOptional name=install.x11extras

INFO[0153] installing full qt/webengine                 
ERRO[0153] failed to run command                         cmd="go install -p 3 -v github.com/therecipe/qt/webengine" error="exec: \"go\": executable file not found in $PATH" func=RunCmdOptional name=install.webengine

INFO[0153] installing full qt/testlib                   
ERRO[0153] failed to run command                         cmd="go install -p 3 -v github.com/therecipe/qt/testlib" error="exec: \"go\": executable file not found in $PATH" func=RunCmdOptional name=install.testlib

INFO[0153] installing full qt/serialport                
ERRO[0153] failed to run command                         cmd="go install -p 3 -v github.com/therecipe/qt/serialport" error="exec: \"go\": executable file not found in $PATH" func=RunCmdOptional name=install.serialport

INFO[0153] installing full qt/serialbus                 
ERRO[0153] failed to run command                         cmd="go install -p 3 -v github.com/therecipe/qt/serialbus" error="exec: \"go\": executable file not found in $PATH" func=RunCmdOptional name=install.serialbus

INFO[0153] installing full qt/printsupport              
ERRO[0153] failed to run command                         cmd="go install -p 3 -v github.com/therecipe/qt/printsupport" error="exec: \"go\": executable file not found in $PATH" func=RunCmdOptional name=install.printsupport

INFO[0153] installing full qt/designer                  
ERRO[0153] failed to run command                         cmd="go install -p 3 -v github.com/therecipe/qt/designer" error="exec: \"go\": executable file not found in $PATH" func=RunCmdOptional name=install.designer

INFO[0153] installing full qt/scxml                     
ERRO[0153] failed to run command                         cmd="go install -p 3 -v github.com/therecipe/qt/scxml" error="exec: \"go\": executable file not found in $PATH" func=RunCmdOptional name=install.scxml

INFO[0153] installing full qt/gamepad                   
ERRO[0153] failed to run command                         cmd="go install -p 3 -v github.com/therecipe/qt/gamepad" error="exec: \"go\": executable file not found in $PATH" func=RunCmdOptional name=install.gamepad

INFO[0153] installing full qt/purchasing                
ERRO[0153] failed to run command                         cmd="go install -p 3 -v github.com/therecipe/qt/purchasing" error="exec: \"go\": executable file not found in $PATH" func=RunCmdOptional name=install.purchasing

INFO[0153] installing full qt/datavisualization         
ERRO[0153] failed to run command                         cmd="go install -p 3 -v github.com/therecipe/qt/datavisualization" error="exec: \"go\": executable file not found in $PATH" func=RunCmdOptional name=install.datavisualization

INFO[0153] installing full qt/charts                    
ERRO[0153] failed to run command                         cmd="go install -p 3 -v github.com/therecipe/qt/charts" error="exec: \"go\": executable file not found in $PATH" func=RunCmdOptional name=install.charts

INFO[0153] installing full qt/quickcontrols2            
ERRO[0153] failed to run command                         cmd="go install -p 3 -v github.com/therecipe/qt/quickcontrols2" error="exec: \"go\": executable file not found in $PATH" func=RunCmdOptional name=install.quickcontrols2

INFO[0153] installing full qt/sailfish                  
ERRO[0153] failed to run command                         cmd="go install -p 3 -v github.com/therecipe/qt/sailfish" error="exec: \"go\": executable file not found in $PATH" func=RunCmdOptional name=install.sailfish

INFO[0153] installing full qt/sailfish                  
ERRO[0153] failed to run command                         cmd="go install -p 3 -v github.com/therecipe/qt/sailfish" error="exec: \"go\": executable file not found in $PATH" func=RunCmdOptional name=install.sailfish

INFO[0153] installing full qt/sailfish                  
ERRO[0153] failed to run command                         cmd="go install -p 3 -v github.com/therecipe/qt/sailfish" error="exec: \"go\": executable file not found in $PATH" func=RunCmdOptional name=install.sailfish

INFO[0153] installing full qt/sailfish                  
ERRO[0153] failed to run command                         cmd="go install -p 3 -v github.com/therecipe/qt/sailfish" error="exec: \"go\": executable file not found in $PATH" func=RunCmdOptional name=install.sailfish

INFO[0153] running setup/test desktop (~10min)          
INFO[0153] testing widgets/line_edits                   
ERRO[0159] failed to run command                         cmd="go build -i -p 3 -v -ldflags=\"-s\" \"-w\" -o /home/matthieu/go-work/src/github.com/therecipe/qt/internal/examples/widgets/line_edits/deploy/linux_minimal/line_edits -tags=\"minimal\"" error="exec: \"go\": executable file not found in $PATH" func=RunCmd name="build for desktop on linux"

```

**Comment by Matt-Texier** [comment]
Probably a PATH issue of my root user ...

**Comment by Matt-Texier** [comment]
All good, thanks for your help.

**Comment by therecipe** [comment]
You are welcome :)
