### ISSUE TITLE
Linux + official prebuilt or system libs fails

### ISSUE THREAD

**Issue by Huholoman** [therecipe/qt#223]
Hello,
Im trying to run qtserup, but it fails.. 
My system qt version is 5.7, official prebuilt libs are also 5.7 (i installed it for this Qt bindings)
I tryed use my system libs runing
```
export QT_PKG_CONFIG=true
$GOPATH/bin/qtsetup
```
or
```
export QT_DIR=path/to/Qt/
$GOPATH/bin/qtsetup
```

But both fails, there is my output
```
INFO[0000] running setup/prep                           
WARN[0000] (not root) failed to create qtdeploy symlink in your PATH (/usr/local/bin) -> use /home/tobik/Buhvico/Programovani/go/bin/qtdeploy instead 
WARN[0000] (not root) failed to create qtmoc symlink in your PATH (/usr/local/bin) -> use /home/tobik/Buhvico/Programovani/go/bin/qtmoc instead 
WARN[0000] (not root) failed to create qtrcc symlink in your PATH (/usr/local/bin) -> use /home/tobik/Buhvico/Programovani/go/bin/qtrcc instead 
WARN[0000] (not root) failed to create qtminimal symlink in your PATH (/usr/local/bin) -> use /home/tobik/Buhvico/Programovani/go/bin/qtminimal instead 
INFO[0000] running setup/check desktop                  
INFO[0000] VERSION: 0.0.4                               
INFO[0000] GOOS: linux                                  
INFO[0000] GOARCH: amd64                                
INFO[0000] GOVERSION: go1.7.4                           
INFO[0000] GOROOT: /usr/lib/go                          
INFO[0000] GOPATH: /home/tobik/Buhvico/Programovani/go  
INFO[0000] GOBIN: /home/tobik/Buhvico/Programovani/go/bin 
INFO[0000] HASH: b1cb04c1a009ae7b807f7ed7e1ddfa86d3f8606a 
WARN[0000] Couldn't get valid application name 'Qt' in /home/tobik/Buhvico/Apps/Qt/components.xml 
panic: runtime error: index out of range

goroutine 1 [running]:
panic(0x6df3c0, 0xc42000c160)
	/usr/lib/go/src/runtime/panic.go:500 +0x1a1
github.com/therecipe/qt/internal/utils.QT_VERSION(0x0, 0x0)
	/home/tobik/Buhvico/Programovani/go/src/github.com/therecipe/qt/internal/utils/env.go:71 +0x6e3
github.com/therecipe/qt/internal/cmd/setup.check(0x722dac, 0x7)
	/home/tobik/Buhvico/Programovani/go/src/github.com/therecipe/qt/internal/cmd/setup/check.go:30 +0xaee
github.com/therecipe/qt/internal/cmd/setup.Setup(0x721b7c, 0x4, 0x722dac, 0x7)
	/home/tobik/Buhvico/Programovani/go/src/github.com/therecipe/qt/internal/cmd/setup/setup.go:7 +0x136
main.main()
	/home/tobik/Buhvico/Programovani/go/src/github.com/therecipe/qt/cmd/qtsetup/qtsetup.go:37 +0x27b
```
If anyone can help, I will be very gratful

Cheers

Edit:
Ok, my problem was solved with QT_VERSION=5.7.1, i was looking for something which could help me earlier, but that time i didnt find it. This issue can be set as fixed, or deleted, or whatever :D

**Comment by therecipe** [comment]
Hey

Yes, setting `QT_VERSION`would have been my advice as well.

It's probably the same issue as this one: https://github.com/therecipe/qt/issues/201

I will look into this today and change the version detection.

**Comment by Huholoman** [comment]
I actualy found that and said ill give it a chance. And woah, it worked. :))
