### ISSUE TITLE
go1.8 default GOPATH and msys2 errors on windows

### ISSUE THREAD

**Issue by m8m5** [therecipe/qt#261]
`qtsetup` won't run if there is no explicit `GOPATH` on go1.8. 

https://github.com/therecipe/qt/blob/master/internal/utils/windows.go#L19 always returns `msys2 dir` and https://github.com/therecipe/qt/blob/master/internal/cmd/setup/check.go#L133 panics without checking `useMsys2`

<details>
<summary>log</summary>

```
Shovon@DESKTOP-1KCM8MH C:\Users\Shovon\go\bin
> qtsetup
INFO[0000] running: 'qtsetup prep'
INFO[0000] running: 'qtsetup check windows' [docker=false]
INFO[0000] GOOS:                        'windows'
INFO[0000] GOARCH:                      'amd64'
INFO[0000] GOVERSION:                   'go1.8'
INFO[0000] GOROOT:                   *  'C:\Go\'
INFO[0000] GOPATH:                   *  'C:\Users\Shovon\go'
INFO[0000] GOBIN:                       'C:\Users\Shovon\go\bin'
INFO[0000] QT_HASH:                     '6943fe08ad1a7fe5fdc2d0ef5defc7de4cf7997f'
INFO[0000] QT_VERSION:                  '5.8.0'
INFO[0000] QT_VERSION_MAJOR:            '5.8'
INFO[0000] QT_DIR:                      'C:\Qt\Qt5.8.0'
INFO[0000] QT_STUB:                     'false'
INFO[0000] QT_DEBUG:                    'false'
INFO[0000] QT_QMAKE_DIR:                ''
INFO[0000] QT_MSYS2:                    'false'
INFO[0000] QT_MSYS2_DIR:                'C:\msys64\mingw32'
PANI[0000] failed to find QT_MSYS2_DIR (C:\msys64\mingw32)  error="open C:\msys64\mingw32: The system cannot find the path specified."
panic: (*logrus.Entry) (0x726500,0xc042115d10)

goroutine 1 [running]:
github.com/Sirupsen/logrus.Entry.log(0xc04200e2d0, 0xc04213f380, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x40cd00, ...)
        C:/Users/Shovon/go/src/github.com/Sirupsen/logrus/entry.go:124 +0x347
github.com/Sirupsen/logrus.(*Entry).Panic(0xc042115cc0, 0xc04207f790, 0x1, 0x1)
        C:/Users/Shovon/go/src/github.com/Sirupsen/logrus/entry.go:169 +0x122
github.com/Sirupsen/logrus.(*Entry).Panicf(0xc042115cc0, 0x738190, 0x16, 0xc04207fb50, 0x2, 0x2)
        C:/Users/Shovon/go/src/github.com/Sirupsen/logrus/entry.go:217 +0xff
github.com/therecipe/qt/internal/cmd/setup.Check(0x731011, 0x7, 0x72fc00)
        C:/Users/Shovon/go/src/github.com/therecipe/qt/internal/cmd/setup/check.go:134 +0x1380
main.main()
        C:/Users/Shovon/go/src/github.com/therecipe/qt/cmd/qtsetup/main.go:78 +0x1d2
```

</details>

**Comment by therecipe** [comment]
Hey

Thanks the report :)
I will fix them.

**Comment by m8m5** [comment]
also please lower case "github.com/Sirupsen/logrus". 

(Go 1.8 default GOPATH issue discussion on https://github.com/joefitzgerald/go-plus/issues/547 will simplify your process.)

**Comment by m8m5** [comment]
also please lower case "github.com/Sirupsen/logrus".

**Comment by therecipe** [comment]
>also please lower case "github.com/Sirupsen/logrus".

Did that and fixed the other issues on windows with: https://github.com/therecipe/qt/commit/8afded013bb498a558175f44abbd29d82a54b4ad

**Comment by m8m5** [comment]
works as expected 👍
