### ISSUE TITLE
Byte array cause panic

### ISSUE THREAD

**Issue by arknable** [therecipe/qt#276]
Hi, 

I noticed that array of byte causes a panic on qtmoc
```
PANI[0025] failed to format: moc                         error="56:33: expected type, found '{' (and 10 more errors)"
panic: (*logrus.Entry) (0x11ef6a0,0xc4251ad270)

goroutine 1 [running]:
github.com/Sirupsen/logrus.Entry.log(0xc42006c0f0, 0xc4252a3830, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x100c100, ...)
        /Users/arknable/Documents/Cats/Repository/godeps/src/github.com/Sirupsen/logrus/entry.go:124 +0x340
github.com/Sirupsen/logrus.(*Entry).Panic(0xc4251ad220, 0xc4274328f0, 0x1, 0x1)
        /Users/arknable/Documents/Cats/Repository/godeps/src/github.com/Sirupsen/logrus/entry.go:169 +0x11b
github.com/Sirupsen/logrus.(*Entry).Panicln(0xc4251ad220, 0xc427432b80, 0x2, 0x2)
        /Users/arknable/Documents/Cats/Repository/godeps/src/github.com/Sirupsen/logrus/entry.go:264 +0xe0
github.com/therecipe/qt/internal/binding/templater.preambleGo(0x11f80f8, 0x3, 0x11f80f8, 0x3, 0xc422d7e000, 0x3a1a, 0x4f8a, 0x0
, 0x1, 0xc4201748c8, ...)
        /Users/arknable/Documents/Cats/Repository/go/src/github.com/therecipe/qt/internal/binding/templater/template_go.go:284
+0xacb
github.com/therecipe/qt/internal/binding/templater.GoTemplate(0x11f80f8, 0x3, 0x0, 0x1, 0xc4201748c8, 0x4, 0x11f8d2f, 0x6, 0x0,
 0x0, ...)
        /Users/arknable/Documents/Cats/Repository/go/src/github.com/therecipe/qt/internal/binding/templater/template_go.go:180
+0xbd7
github.com/therecipe/qt/internal/cmd/moc.Moc(0xc4200b4c00, 0x54, 0x11f8d2f, 0x6)
        /Users/arknable/Documents/Cats/Repository/go/src/github.com/therecipe/qt/internal/cmd/moc/moc.go:222 +0x2fc9
github.com/therecipe/qt/internal/cmd/moc.Moc(0xc420018004, 0x54, 0x11f8d2f, 0x6)
        /Users/arknable/Documents/Cats/Repository/go/src/github.com/therecipe/qt/internal/cmd/moc/moc.go:39 +0xd9d
main.main()
        /Users/arknable/Documents/Cats/Repository/go/src/github.com/therecipe/qt/cmd/qtmoc/main.go:69 +0x21b
```

Example:
```
type Message struct {
	core.QObject
	_ []byte `property:"checksum"`
}
```

If I replace `checksum` type to other kind of type such as `[]int` then no panic occurred.
I put an example on this repository: https://github.com/arknable/therecipe-issue

Thanks.

**Comment by arknable** [comment]
I just remembered that QML doesn't have `byte` data type. probably that panic is normal on non supported QML type ?

**Comment by therecipe** [comment]
Hey

Yes, that's because `byte` is currently not supported.
Maybe you could try to use a `string` instead?

**Comment by arknable** [comment]
ah ok. I better use `int` then, thanks a lot.
