### ISSUE TITLE
qtmoc panic when using struct on different package

### ISSUE THREAD

**Issue by arknable** [therecipe/qt#293]
Hey,

I encounter a panic error as follows,
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x115415c]

goroutine 1 [running]:
github.com/therecipe/qt/internal/binding/converter.goType(0xc427156c00, 0xc426a42e20, 0x18, 0xc424fc40a0, 0x17)
        /Users/arknable/Documents/Cats/Repository/go/src/github.com/therecipe/qt/internal/binding/converter/type.go:157 +0x8bc
github.com/therecipe/qt/internal/binding/converter.GoHeaderOutput(0xc427156c00, 0x0, 0x0)
        /Users/arknable/Documents/Cats/Repository/go/src/github.com/therecipe/qt/internal/binding/converter/header.go:111 +0xaa
github.com/therecipe/qt/internal/binding/templater.goFunctionHeader(0xc427156c00, 0xc427156c00, 0x1)
        /Users/arknable/Documents/Cats/Repository/go/src/github.com/therecipe/qt/internal/binding/templater/function_go.go:33 +0xaf
github.com/therecipe/qt/internal/binding/templater.goFunction(0xc427156c00, 0xc426961110, 0x61)
        /Users/arknable/Documents/Cats/Repository/go/src/github.com/therecipe/qt/internal/binding/templater/function_go.go:14 +0x40
github.com/therecipe/qt/internal/binding/templater.hasUnimplementedPureVirtualFunctions(0xc427571fb0, 0x10, 0xc4256b1330)
        /Users/arknable/Documents/Cats/Repository/go/src/github.com/therecipe/qt/internal/binding/templater/helper.go:15 +0x135
github.com/therecipe/qt/internal/binding/templater.goFunctionBody(0xc4225e6480, 0x0, 0x0)
        /Users/arknable/Documents/Cats/Repository/go/src/github.com/therecipe/qt/internal/binding/templater/function_go.go:265 +0x2
2c2
github.com/therecipe/qt/internal/binding/templater.goFunction(0xc4225e6480, 0x11fb601, 0xc4268d2a50)
        /Users/arknable/Documents/Cats/Repository/go/src/github.com/therecipe/qt/internal/binding/templater/function_go.go:14 +0x65
github.com/therecipe/qt/internal/binding/templater.cTemplateFunctions(0xc426960d20, 0xc420122780, 0x120a350, 0x11f9bc2, 0x2, 0xc422
f2e301)
        /Users/arknable/Documents/Cats/Repository/go/src/github.com/therecipe/qt/internal/binding/templater/template_c.go:90 +0x8eb
github.com/therecipe/qt/internal/binding/templater.cTemplate(0xc426960d20, 0xc420122780, 0x120a348, 0x120a350, 0x11f9bc2, 0x2, 0x1)
        /Users/arknable/Documents/Cats/Repository/go/src/github.com/therecipe/qt/internal/binding/templater/template_c.go:15 +0xc1
github.com/therecipe/qt/internal/binding/templater.GoTemplate(0x11f9ed5, 0x3, 0x0, 0x1, 0xc420105d28, 0x4, 0x11fab3e, 0x6, 0x0, 0x0
, ...)
        /Users/arknable/Documents/Cats/Repository/go/src/github.com/therecipe/qt/internal/binding/templater/template_go.go:177 +0xa
da
github.com/therecipe/qt/internal/cmd/moc.Moc(0xc4200c2000, 0x54, 0x11fab3e, 0x6, 0x12f4e00)
        /Users/arknable/Documents/Cats/Repository/go/src/github.com/therecipe/qt/internal/cmd/moc/moc.go:222 +0x2f86
github.com/therecipe/qt/internal/cmd/moc.Moc(0xc42001a004, 0x54, 0x11fab3e, 0x6, 0x1203b00)
        /Users/arknable/Documents/Cats/Repository/go/src/github.com/therecipe/qt/internal/cmd/moc/moc.go:39 +0xdc2
main.main()
        /Users/arknable/Documents/Cats/Repository/go/src/github.com/therecipe/qt/cmd/qtmoc/main.go:72 +0x285
```

I put an example to reproduce that error on https://github.com/arknable/therecipe-issue that uses struct on https://github.com/arknable/therecipe-issue-support.

If you look at https://github.com/arknable/therecipe-issue/blob/master/application.go, that panic only happens on `getMessageModel` slot and not on other i.e. `messages` property and `getMessages` slot.

Thanks.

**Comment by arknable** [comment]
this was fixed.
