### ISSUE TITLE
qtmoc crashed on signal with multiple argument

### ISSUE THREAD

**Issue by arknable** [therecipe/qt#336]
Hi.

I put a simple example for you here: https://github.com/arknable/therecipe-issue/blob/master/application.go#L18.

If I run `qtmoc` on that project, I got following error

```
panic: runtime error: index out of range

goroutine 1 [running]:
github.com/therecipe/qt/internal/binding/converter.CppInputParametersForCallbackHeader(0xc424beb800, 0x0, 0x0)
        /Users/arknable/Documents/Cats/Repository/go/src/github.com/therecipe/qt/internal/binding/converter/body_input_cpp.go:98 +0x5bf
github.com/therecipe/qt/internal/binding/templater.cppFunctionCallbackHeader(0xc424beb800, 0x12dfc80, 0x0)
        /Users/arknable/Documents/Cats/Repository/go/src/github.com/therecipe/qt/internal/binding/templater/function_cpp.go:72 +0xb2
github.com/therecipe/qt/internal/binding/templater.cppFunctionCallback(0xc424beb800, 0x6, 0xc4240292e8)
        /Users/arknable/Documents/Cats/Repository/go/src/github.com/therecipe/qt/internal/binding/templater/function_cpp.go:15 +0x40
github.com/therecipe/qt/internal/binding/templater.CppTemplate(0x120235d, 0x3, 0x1, 0x1203010, 0x6, 0x7fff5fbffa04, 0x2, 0x0, 0x0, 0x0)
        /Users/arknable/Documents/Cats/Repository/go/src/github.com/therecipe/qt/internal/binding/templater/template_cpp.go:211 +0x11dc
github.com/therecipe/qt/internal/cmd/moc.Moc(0xc42001a004, 0x54, 0x1203010, 0x6, 0x7fff5fbffa04, 0x2, 0x0)
        /Users/arknable/Documents/Cats/Repository/go/src/github.com/therecipe/qt/internal/cmd/moc/moc.go:216 +0x2e22
main.main()
        /Users/arknable/Documents/Cats/Repository/go/src/github.com/therecipe/qt/cmd/qtmoc/main.go:75 +0x364

```

but if I removed `result` argument from that signal signature, `qtmoc` worked. Same error also occured on following signature,

```
_ func(result *core.QObject, data []*core.QVariant) `signal:"dataSignal"`
```

and worked if I removed `result` argument,

```
_ func(data []*core.QVariant) `signal:"dataSignal"`
```

Could this be a possible bug ?

Thanks.

**Comment by therecipe** [comment]
Hey

Should be fixed now with: https://github.com/therecipe/qt/commit/73d9e74dd7ceee93573be085b98dc0bd1e2585ad

**Comment by arknable** [comment]
Hi. I tested and it works, thanks a lot.
