### ISSUE TITLE
concurrent map iteration and map write

### ISSUE THREAD

**Issue by pekim** [therecipe/qt#338]
```
fatal error: concurrent map iteration and map write

goroutine 4 [running]:
runtime.throw(0x13e68b4, 0x26)
	/usr/local/go/src/runtime/panic.go:596 +0x95 fp=0xc4202e1d48 sp=0xc4202e1d28
runtime.mapiternext(0xc4202e1e70)
	/usr/local/go/src/runtime/hashmap.go:737 +0x7ee fp=0xc4202e1df8 sp=0xc4202e1d48
github.com/therecipe/qt.DisconnectAllSignals(0xc4205cc000, 0xe)
	/home/mike/go/src/github.com/therecipe/qt/qt.go:62 +0x14e fp=0xc4202e1ee0 sp=0xc4202e1df8
github.com/therecipe/qt/gui.(*QPixmap).DestroyQPixmap(0xc42032d7a0)
	/home/mike/go/src/github.com/therecipe/qt/gui/gui.go:34005 +0xce fp=0xc4202e1f28 sp=0xc4202e1ee0
runtime.call32(0x0, 0x13ee960, 0xc4203ba000, 0x1000000010)
	/usr/local/go/src/runtime/asm_amd64.s:514 +0x48 fp=0xc4202e1f58 sp=0xc4202e1f28
runtime.runfinq()
	/usr/local/go/src/runtime/mfinal.go:208 +0x205 fp=0xc4202e1fe0 sp=0xc4202e1f58
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:2197 +0x1 fp=0xc4202e1fe8 sp=0xc4202e1fe0
created by runtime.createfing
	/usr/local/go/src/runtime/mfinal.go:142 +0x62
...
```

I don't know quite what I'm doing that provokes this, other than that I've got a whole bunch of goroutines flying around and in some of them emitting signals.

I'm a commit or two behind HEAD, and the line numbers have changed in this area. So it's worth pointing out which line appears to be implicated.
Line 62 is the `for ... range ...`, which suggest that the `signals` map is the problem.
```go
func DisconnectAllSignals(name string) {
        for entry := range signals {
                if strings.HasPrefix(entry, fmt.Sprintf("%v:", name)) {
                        signalsMutex.Lock()
                        delete(signals, entry)
                        signalsMutex.Unlock()
                }
        }
}
```

**Comment by therecipe** [comment]
Hey

Yeah, sorry seems like I have placed the mutex locks on the wrong positions.
But it's fixed now with: https://github.com/therecipe/qt/commit/8617cc69433ba2c08f54435962ea79861806d60f

The DisconnectAllSignals function is called when an object is destroyed, for example by calling `DeleteLater` or `DestroyXYZ`. Or if some non `QObject` derived class such as `QVariant` is collected by the gc.

**Comment by pekim** [comment]
The fix is obvious in hindsight. Thanks.
