### ISSUE TITLE
segfault to get font metrics

### ISSUE THREAD

**Issue by dzhou121** [therecipe/qt#343]
Hi, it crashes on getting font metrics, code example:

```
package main

import (
	"fmt"

	"github.com/therecipe/qt/gui"
)

func main() {
	font := gui.NewQFont2("Monospace", 11, int(gui.QFont__Normal), false)
	fontMetrics := gui.NewQFontMetricsF(font)
	fmt.Println(fontMetrics.Width("W"))
}

```

```
fatal error: unexpected signal during runtime execution
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x521cf76]

runtime stack:
runtime.throw(0x43a213c, 0x2a)
        /usr/local/Cellar/go/1.8.3/libexec/src/runtime/panic.go:596 +0x95
runtime.sigpanic()
        /usr/local/Cellar/go/1.8.3/libexec/src/runtime/signal_unix.go:274 +0x2db

goroutine 1 [syscall, locked to thread]:
runtime.cgocall(0x41b22a0, 0xc420051ec8, 0xc420051ef0)
        /usr/local/Cellar/go/1.8.3/libexec/src/runtime/cgocall.go:131 +0xe2 fp=0xc420051e98 sp=0xc420051e58
github.com/therecipe/qt/gui._Cfunc_QFontMetricsF_Width(0x6d00470, 0x6d027f0, 0x0)
        github.com/therecipe/qt/gui/_obj/_cgo_gotypes.go:10785 +0x4e fp=0xc420051ec8 sp=0xc420051e98
github.com/therecipe/qt/gui.(*QFontMetricsF).Width.func2(0x6d00470, 0x6d027f0, 0x6d027f0)
        /Users/Lulu/go/src/github.com/therecipe/qt/gui/gui.go:12798 +0x6a fp=0xc420051f00 sp=0xc420051ec8
github.com/therecipe/qt/gui.(*QFontMetricsF).Width(0xc42000e030, 0x439ac0e, 0x1, 0x0)
        /Users/Lulu/go/src/github.com/therecipe/qt/gui/gui.go:12798 +0x6b fp=0xc420051f30 sp=0xc420051f00
main.main()
        /Users/Lulu/test.go:12 +0x8e fp=0xc420051f88 sp=0xc420051f30
runtime.main()
        /usr/local/Cellar/go/1.8.3/libexec/src/runtime/proc.go:185 +0x20a fp=0xc420051fe0 sp=0xc420051f88
runtime.goexit()
        /usr/local/Cellar/go/1.8.3/libexec/src/runtime/asm_amd64.s:2197 +0x1 fp=0xc420051fe8 sp=0xc420051fe0

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
        /usr/local/Cellar/go/1.8.3/libexec/src/runtime/asm_amd64.s:2197 +0x1
exit status 2

```

**Comment by therecipe** [comment]
Hey

It seems like you need to create the QGuiApplication first.

This should work:
```go
package main

import (
	"fmt"
	"os"

	"github.com/therecipe/qt/gui"
)

func main() {
	gui.NewQGuiApplication(len(os.Args), os.Args)

	font := gui.NewQFont2("Monospace", 11, int(gui.QFont__Normal), false)
	fontMetrics := gui.NewQFontMetricsF(font)
	fmt.Println(fontMetrics.Width("W"))
}
```

**Comment by dzhou121** [comment]
That works. Thanks for your help @therecipe
