### ISSUE TITLE
qtdeploy on windows 10 x64

### ISSUE THREAD

**Issue by averrin** [therecipe/qt#376]
Its installs, all test programs were launched and my code works on linux, but on windows i get:
```
ERRO[0061] failed to run command                         cmd="go build -p 4 -v -ldflags="-s" "-w" "-H=windowsgui" -o C:\Users\averr_000\Documents\GitHub\norp_toolkit\deploy\windows\norp_toolkit.exe -tags="minimal"" env="GOPATH=C:\Users\averr_000\Documents\go TMP=C:\Users\averr_000\AppData\Local\Temp\ GOARCH=386 PATH=C:\Users\averr_000\AppData\Local\GitHub\PortableGit_f02737a78695063deace08e96d5042710d3e32db\cmd;C:\Users\averr_000\AppData\Local\GitHub\PortableGit_f02737a78695063deace08e96d5042710d3e32db\usr\bin;C:\Users\averr_000\AppData\Local\GitHub\PortableGit_f02737a78695063deace08e96d5042710d3e32db\usr\share\git-tfs;C:\Users\averr_000\AppData\Local\Apps\2.0\WNY5XH9J.ZOK\B1WE6KQC.EBL\gith..tion_317444273a93ac29_0003.0003_5794af8169eeff14;C:\Users\averr_000\AppData\Local\GitHub\lfs-amd64_1.5.5;C:\Users\averr_000\AppData\Local\Apps\2.0\WNY5XH9J.ZOK\B1WE6KQC.EBL\gith..tion_317444273a93ac29_0003.0003_5794af8169eeff14\NativeBinaries\x86;C:\WinAVR-20100110\bin;C:\WinAVR-20100110\utils\bin;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Go\bin;C:\emacs\bin;C:\Axon7Development\Axon7Toolkit;C:\Qt\Qt5.8.0\Tools\mingw530_32\bin;C:\WinAVR-20100110\bin;C:\WinAVR-20100110\utils\bin;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Go\bin;C:\emacs\bin;C:\Users\averr_000\AppData\Local\Microsoft\WindowsApps;C:\adb;%USERPROFILE%\AppData\Local\Microsoft\WindowsApps;;C:\Windows\Microsoft.NET\Framework\v4.0.30319\ GOROOT=C:\Go\ TEMP=C:\Users\averr_000\AppData\Local\Temp\ GOOS=windows CGO_ENABLED=1" error="exit status 2" func=RunCmd name="build for windows on windows"
bytes
context
container/list
hash
crypto
crypto/subtle
encoding/binary
crypto/cipher
math/rand
bufio
crypto/sha512
math/big
crypto/aes
crypto/des
crypto/hmac
crypto/internal/cipherhw
crypto/md5
crypto/rc4
crypto/sha1
crypto/sha256
encoding/hex
encoding/base64
sort
internal/nettrace
internal/singleflight
vendor/golang_org/x/crypto/chacha20poly1305/internal/chacha20
encoding/pem
net
vendor/golang_org/x/crypto/poly1305
vendor/golang_org/x/crypto/curve25519
vendor/golang_org/x/crypto/chacha20poly1305
crypto/elliptic
encoding/asn1
crypto/rand
crypto/rsa
crypto/dsa
crypto/ecdsa
crypto/x509/pkix
path/filepath
encoding
github.com/mattn/go-isatty
encoding/json
encoding/xml
io/ioutil
github.com/mattn/go-colorable
crypto/x509
github.com/labstack/gommon/color
github.com/valyala/fasttemplate/vendor/github.com/valyala/bytebufferpool
path
github.com/valyala/fasttemplate
compress/flate
hash/crc32
github.com/labstack/gommon/log
vendor/golang_org/x/net/http2/hpack
vendor/golang_org/x/net/idna
crypto/tls
vendor/golang_org/x/net/lex/httplex
vendor/golang_org/x/text/transform
compress/gzip
mime
vendor/golang_org/x/text/unicode/norm
vendor/golang_org/x/text/width
mime/quotedprintable
net/textproto
net/http/internal
net/url
mime/multipart
github.com/dgrijalva/jwt-go
net/http/httptrace
regexp/syntax
github.com/labstack/gommon/random
net/http
github.com/therecipe/qt/core
github.com/therecipe/qt/quickcontrols2
regexp
github.com/labstack/gommon/bytes
plugin
# github.com/therecipe/qt/core
cgo-gcc-prolog: In function '_cgo_de7db6aa85d9_Cfunc_QCoreApplication_QCoreApplication_Flush':
cgo-gcc-prolog:761:49: warning: unused variable 'a' [-Wunused-variable]
golang.org/x/crypto/acme
net/http/httputil
golang.org/x/crypto/acme/autocert
github.com/labstack/echo
# github.com/therecipe/qt/quickcontrols2
C:\Users\averr_000\AppData\Local\Temp\go-build264456814\github.com\therecipe\qt\quickcontrols2\_obj\_cgo_main.c: In function 'crosscall2':
C:\Users\averr_000\AppData\Local\Temp\go-build264456814\github.com\therecipe\qt\quickcontrols2\_obj\_cgo_main.c:2:23: warning: unused parameter 'fn' [-Wunused-parameter]
 void crosscall2(void(*fn)(void*, int, __SIZE_TYPE__), void *a, int c, __SIZE_TYPE__ ctxt) { }
                       ^
C:\Users\averr_000\AppData\Local\Temp\go-build264456814\github.com\therecipe\qt\quickcontrols2\_obj\_cgo_main.c:2:61: warning: unused parameter 'a' [-Wunused-parameter]
 void crosscall2(void(*fn)(void*, int, __SIZE_TYPE__), void *a, int c, __SIZE_TYPE__ ctxt) { }
                                                             ^
C:\Users\averr_000\AppData\Local\Temp\go-build264456814\github.com\therecipe\qt\quickcontrols2\_obj\_cgo_main.c:2:68: warning: unused parameter 'c' [-Wunused-parameter]
 void crosscall2(void(*fn)(void*, int, __SIZE_TYPE__), void *a, int c, __SIZE_TYPE__ ctxt) { }
                                                                    ^
C:\Users\averr_000\AppData\Local\Temp\go-build264456814\github.com\therecipe\qt\quickcontrols2\_obj\_cgo_main.c:2:85: warning: unused parameter 'ctxt' [-Wunused-parameter]
 void crosscall2(void(*fn)(void*, int, __SIZE_TYPE__), void *a, int c, __SIZE_TYPE__ ctxt) { }
                                                                                     ^
C:\Users\averr_000\AppData\Local\Temp\go-build264456814\github.com\therecipe\qt\quickcontrols2\_obj\_cgo_main.c: In function '_cgo_release_context':
C:\Users\averr_000\AppData\Local\Temp\go-build264456814\github.com\therecipe\qt\quickcontrols2\_obj\_cgo_main.c:4:41: warning: unused parameter 'ctxt' [-Wunused-parameter]
 void _cgo_release_context(__SIZE_TYPE__ ctxt) { }
                                         ^
C:\Users\averr_000\AppData\Local\Temp\go-build264456814\github.com\therecipe\qt\quickcontrols2\_obj\_cgo_main.c: In function '_cgo_allocate':
C:\Users\averr_000\AppData\Local\Temp\go-build264456814\github.com\therecipe\qt\quickcontrols2\_obj\_cgo_main.c:6:26: warning: unused parameter 'a' [-Wunused-parameter]
 void _cgo_allocate(void *a, int c) { }
                          ^
C:\Users\averr_000\AppData\Local\Temp\go-build264456814\github.com\therecipe\qt\quickcontrols2\_obj\_cgo_main.c:6:33: warning: unused parameter 'c' [-Wunused-parameter]
 void _cgo_allocate(void *a, int c) { }
                                 ^
C:\Users\averr_000\AppData\Local\Temp\go-build264456814\github.com\therecipe\qt\quickcontrols2\_obj\_cgo_main.c: In function '_cgo_panic':
C:\Users\averr_000\AppData\Local\Temp\go-build264456814\github.com\therecipe\qt\quickcontrols2\_obj\_cgo_main.c:7:23: warning: unused parameter 'a' [-Wunused-parameter]
 void _cgo_panic(void *a, int c) { }
                       ^
C:\Users\averr_000\AppData\Local\Temp\go-build264456814\github.com\therecipe\qt\quickcontrols2\_obj\_cgo_main.c:7:30: warning: unused parameter 'c' [-Wunused-parameter]
 void _cgo_panic(void *a, int c) { }
                              ^
github.com/labstack/echo/middleware
# github.com/therecipe/qt/core
C:\Users\averr_000\AppData\Local\Temp\go-build264456814\github.com\therecipe\qt\core\_obj\_cgo_main.c: In function 'crosscall2':
C:\Users\averr_000\AppData\Local\Temp\go-build264456814\github.com\therecipe\qt\core\_obj\_cgo_main.c:2:23: warning: unused parameter 'fn' [-Wunused-parameter]
 void crosscall2(void(*fn)(void*, int, __SIZE_TYPE__), void *a, int c, __SIZE_TYPE__ ctxt) { }
                       ^
C:\Users\averr_000\AppData\Local\Temp\go-build264456814\github.com\therecipe\qt\core\_obj\_cgo_main.c:2:61: warning: unused parameter 'a' [-Wunused-parameter]
 void crosscall2(void(*fn)(void*, int, __SIZE_TYPE__), void *a, int c, __SIZE_TYPE__ ctxt) { }
                                                             ^
C:\Users\averr_000\AppData\Local\Temp\go-build264456814\github.com\therecipe\qt\core\_obj\_cgo_main.c:2:68: warning: unused parameter 'c' [-Wunused-parameter]
 void crosscall2(void(*fn)(void*, int, __SIZE_TYPE__), void *a, int c, __SIZE_TYPE__ ctxt) { }
                                                                    ^
C:\Users\averr_000\AppData\Local\Temp\go-build264456814\github.com\therecipe\qt\core\_obj\_cgo_main.c:2:85: warning: unused parameter 'ctxt' [-Wunused-parameter]
 void crosscall2(void(*fn)(void*, int, __SIZE_TYPE__), void *a, int c, __SIZE_TYPE__ ctxt) { }
                                                                                     ^
C:\Users\averr_000\AppData\Local\Temp\go-build264456814\github.com\therecipe\qt\core\_obj\_cgo_main.c: In function '_cgo_release_context':
C:\Users\averr_000\AppData\Local\Temp\go-build264456814\github.com\therecipe\qt\core\_obj\_cgo_main.c:4:41: warning: unused parameter 'ctxt' [-Wunused-parameter]
 void _cgo_release_context(__SIZE_TYPE__ ctxt) { }
                                         ^
C:\Users\averr_000\AppData\Local\Temp\go-build264456814\github.com\therecipe\qt\core\_obj\_cgo_main.c: In function '_cgo_allocate':
C:\Users\averr_000\AppData\Local\Temp\go-build264456814\github.com\therecipe\qt\core\_obj\_cgo_main.c:6:26: warning: unused parameter 'a' [-Wunused-parameter]
 void _cgo_allocate(void *a, int c) { }
                          ^
C:\Users\averr_000\AppData\Local\Temp\go-build264456814\github.com\therecipe\qt\core\_obj\_cgo_main.c:6:33: warning: unused parameter 'c' [-Wunused-parameter]
 void _cgo_allocate(void *a, int c) { }
                                 ^
C:\Users\averr_000\AppData\Local\Temp\go-build264456814\github.com\therecipe\qt\core\_obj\_cgo_main.c: In function '_cgo_panic':
C:\Users\averr_000\AppData\Local\Temp\go-build264456814\github.com\therecipe\qt\core\_obj\_cgo_main.c:7:23: warning: unused parameter 'a' [-Wunused-parameter]
 void _cgo_panic(void *a, int c) { }
                       ^
C:\Users\averr_000\AppData\Local\Temp\go-build264456814\github.com\therecipe\qt\core\_obj\_cgo_main.c:7:30: warning: unused parameter 'c' [-Wunused-parameter]
 void _cgo_panic(void *a, int c) { }
                              ^
github.com/therecipe/qt/gui
github.com/therecipe/qt/qml
# github.com/therecipe/qt/qml
C:\Users\averr_000\AppData\Local\Temp\go-build264456814\github.com\therecipe\qt\qml\_obj\_cgo_main.c: In function 'crosscall2':
C:\Users\averr_000\AppData\Local\Temp\go-build264456814\github.com\therecipe\qt\qml\_obj\_cgo_main.c:2:23: warning: unused parameter 'fn' [-Wunused-parameter]
 void crosscall2(void(*fn)(void*, int, __SIZE_TYPE__), void *a, int c, __SIZE_TYPE__ ctxt) { }
                       ^
C:\Users\averr_000\AppData\Local\Temp\go-build264456814\github.com\therecipe\qt\qml\_obj\_cgo_main.c:2:61: warning: unused parameter 'a' [-Wunused-parameter]
 void crosscall2(void(*fn)(void*, int, __SIZE_TYPE__), void *a, int c, __SIZE_TYPE__ ctxt) { }
                                                             ^
C:\Users\averr_000\AppData\Local\Temp\go-build264456814\github.com\therecipe\qt\qml\_obj\_cgo_main.c:2:68: warning: unused parameter 'c' [-Wunused-parameter]
 void crosscall2(void(*fn)(void*, int, __SIZE_TYPE__), void *a, int c, __SIZE_TYPE__ ctxt) { }
                                                                    ^
C:\Users\averr_000\AppData\Local\Temp\go-build264456814\github.com\therecipe\qt\qml\_obj\_cgo_main.c:2:85: warning: unused parameter 'ctxt' [-Wunused-parameter]
 void crosscall2(void(*fn)(void*, int, __SIZE_TYPE__), void *a, int c, __SIZE_TYPE__ ctxt) { }
                                                                                     ^
C:\Users\averr_000\AppData\Local\Temp\go-build264456814\github.com\therecipe\qt\qml\_obj\_cgo_main.c: In function '_cgo_release_context':
C:\Users\averr_000\AppData\Local\Temp\go-build264456814\github.com\therecipe\qt\qml\_obj\_cgo_main.c:4:41: warning: unused parameter 'ctxt' [-Wunused-parameter]
 void _cgo_release_context(__SIZE_TYPE__ ctxt) { }
                                         ^
C:\Users\averr_000\AppData\Local\Temp\go-build264456814\github.com\therecipe\qt\qml\_obj\_cgo_main.c: In function '_cgo_allocate':
C:\Users\averr_000\AppData\Local\Temp\go-build264456814\github.com\therecipe\qt\qml\_obj\_cgo_main.c:6:26: warning: unused parameter 'a' [-Wunused-parameter]
 void _cgo_allocate(void *a, int c) { }
                          ^
C:\Users\averr_000\AppData\Local\Temp\go-build264456814\github.com\therecipe\qt\qml\_obj\_cgo_main.c:6:33: warning: unused parameter 'c' [-Wunused-parameter]
 void _cgo_allocate(void *a, int c) { }
                                 ^
C:\Users\averr_000\AppData\Local\Temp\go-build264456814\github.com\therecipe\qt\qml\_obj\_cgo_main.c: In function '_cgo_panic':
C:\Users\averr_000\AppData\Local\Temp\go-build264456814\github.com\therecipe\qt\qml\_obj\_cgo_main.c:7:23: warning: unused parameter 'a' [-Wunused-parameter]
 void _cgo_panic(void *a, int c) { }
                       ^
C:\Users\averr_000\AppData\Local\Temp\go-build264456814\github.com\therecipe\qt\qml\_obj\_cgo_main.c:7:30: warning: unused parameter 'c' [-Wunused-parameter]
 void _cgo_panic(void *a, int c) { }
                              ^
# github.com/therecipe/qt/gui
C:\Users\averr_000\AppData\Local\Temp\go-build264456814\github.com\therecipe\qt\gui\_obj\_cgo_main.c: In function 'crosscall2':
C:\Users\averr_000\AppData\Local\Temp\go-build264456814\github.com\therecipe\qt\gui\_obj\_cgo_main.c:2:23: warning: unused parameter 'fn' [-Wunused-parameter]
 void crosscall2(void(*fn)(void*, int, __SIZE_TYPE__), void *a, int c, __SIZE_TYPE__ ctxt) { }
                       ^
C:\Users\averr_000\AppData\Local\Temp\go-build264456814\github.com\therecipe\qt\gui\_obj\_cgo_main.c:2:61: warning: unused parameter 'a' [-Wunused-parameter]
 void crosscall2(void(*fn)(void*, int, __SIZE_TYPE__), void *a, int c, __SIZE_TYPE__ ctxt) { }
                                                             ^
C:\Users\averr_000\AppData\Local\Temp\go-build264456814\github.com\therecipe\qt\gui\_obj\_cgo_main.c:2:68: warning: unused parameter 'c' [-Wunused-parameter]
 void crosscall2(void(*fn)(void*, int, __SIZE_TYPE__), void *a, int c, __SIZE_TYPE__ ctxt) { }
                                                                    ^
C:\Users\averr_000\AppData\Local\Temp\go-build264456814\github.com\therecipe\qt\gui\_obj\_cgo_main.c:2:85: warning: unused parameter 'ctxt' [-Wunused-parameter]
 void crosscall2(void(*fn)(void*, int, __SIZE_TYPE__), void *a, int c, __SIZE_TYPE__ ctxt) { }
                                                                                     ^
C:\Users\averr_000\AppData\Local\Temp\go-build264456814\github.com\therecipe\qt\gui\_obj\_cgo_main.c: In function '_cgo_release_context':
C:\Users\averr_000\AppData\Local\Temp\go-build264456814\github.com\therecipe\qt\gui\_obj\_cgo_main.c:4:41: warning: unused parameter 'ctxt' [-Wunused-parameter]
 void _cgo_release_context(__SIZE_TYPE__ ctxt) { }
                                         ^
C:\Users\averr_000\AppData\Local\Temp\go-build264456814\github.com\therecipe\qt\gui\_obj\_cgo_main.c: In function '_cgo_allocate':
C:\Users\averr_000\AppData\Local\Temp\go-build264456814\github.com\therecipe\qt\gui\_obj\_cgo_main.c:6:26: warning: unused parameter 'a' [-Wunused-parameter]
 void _cgo_allocate(void *a, int c) { }
                          ^
C:\Users\averr_000\AppData\Local\Temp\go-build264456814\github.com\therecipe\qt\gui\_obj\_cgo_main.c:6:33: warning: unused parameter 'c' [-Wunused-parameter]
 void _cgo_allocate(void *a, int c) { }
                                 ^
C:\Users\averr_000\AppData\Local\Temp\go-build264456814\github.com\therecipe\qt\gui\_obj\_cgo_main.c: In function '_cgo_panic':
C:\Users\averr_000\AppData\Local\Temp\go-build264456814\github.com\therecipe\qt\gui\_obj\_cgo_main.c:7:23: warning: unused parameter 'a' [-Wunused-parameter]
 void _cgo_panic(void *a, int c) { }
                       ^
C:\Users\averr_000\AppData\Local\Temp\go-build264456814\github.com\therecipe\qt\gui\_obj\_cgo_main.c:7:30: warning: unused parameter 'c' [-Wunused-parameter]
 void _cgo_panic(void *a, int c) { }
                              ^
_/C_/Users/averr_000/Documents/GitHub/norp_toolkit
# _/C_/Users/averr_000/Documents/GitHub/norp_toolkit
C:\Users\averr_000\AppData\Local\Temp\go-build264456814\_\C_\Users\averr_000\Documents\GitHub\norp_toolkit\_obj\_cgo_main.c: In function 'crosscall2':
C:\Users\averr_000\AppData\Local\Temp\go-build264456814\_\C_\Users\averr_000\Documents\GitHub\norp_toolkit\_obj\_cgo_main.c:2:23: warning: unused parameter 'fn' [-Wunused-parameter]
 void crosscall2(void(*fn)(void*, int, __SIZE_TYPE__), void *a, int c, __SIZE_TYPE__ ctxt) { }
                       ^
C:\Users\averr_000\AppData\Local\Temp\go-build264456814\_\C_\Users\averr_000\Documents\GitHub\norp_toolkit\_obj\_cgo_main.c:2:61: warning: unused parameter 'a' [-Wunused-parameter]
 void crosscall2(void(*fn)(void*, int, __SIZE_TYPE__), void *a, int c, __SIZE_TYPE__ ctxt) { }
                                                             ^
C:\Users\averr_000\AppData\Local\Temp\go-build264456814\_\C_\Users\averr_000\Documents\GitHub\norp_toolkit\_obj\_cgo_main.c:2:68: warning: unused parameter 'c' [-Wunused-parameter]
 void crosscall2(void(*fn)(void*, int, __SIZE_TYPE__), void *a, int c, __SIZE_TYPE__ ctxt) { }
                                                                    ^
C:\Users\averr_000\AppData\Local\Temp\go-build264456814\_\C_\Users\averr_000\Documents\GitHub\norp_toolkit\_obj\_cgo_main.c:2:85: warning: unused parameter 'ctxt' [-Wunused-parameter]
 void crosscall2(void(*fn)(void*, int, __SIZE_TYPE__), void *a, int c, __SIZE_TYPE__ ctxt) { }
                                                                                     ^
C:\Users\averr_000\AppData\Local\Temp\go-build264456814\_\C_\Users\averr_000\Documents\GitHub\norp_toolkit\_obj\_cgo_main.c: In function '_cgo_release_context':
C:\Users\averr_000\AppData\Local\Temp\go-build264456814\_\C_\Users\averr_000\Documents\GitHub\norp_toolkit\_obj\_cgo_main.c:4:41: warning: unused parameter 'ctxt' [-Wunused-parameter]
 void _cgo_release_context(__SIZE_TYPE__ ctxt) { }
                                         ^
C:\Users\averr_000\AppData\Local\Temp\go-build264456814\_\C_\Users\averr_000\Documents\GitHub\norp_toolkit\_obj\_cgo_main.c: In function '_cgo_allocate':
C:\Users\averr_000\AppData\Local\Temp\go-build264456814\_\C_\Users\averr_000\Documents\GitHub\norp_toolkit\_obj\_cgo_main.c:6:26: warning: unused parameter 'a' [-Wunused-parameter]
 void _cgo_allocate(void *a, int c) { }
                          ^
C:\Users\averr_000\AppData\Local\Temp\go-build264456814\_\C_\Users\averr_000\Documents\GitHub\norp_toolkit\_obj\_cgo_main.c:6:33: warning: unused parameter 'c' [-Wunused-parameter]
 void _cgo_allocate(void *a, int c) { }
                                 ^
C:\Users\averr_000\AppData\Local\Temp\go-build264456814\_\C_\Users\averr_000\Documents\GitHub\norp_toolkit\_obj\_cgo_main.c: In function '_cgo_panic':
C:\Users\averr_000\AppData\Local\Temp\go-build264456814\_\C_\Users\averr_000\Documents\GitHub\norp_toolkit\_obj\_cgo_main.c:7:23: warning: unused parameter 'a' [-Wunused-parameter]
 void _cgo_panic(void *a, int c) { }
                       ^
C:\Users\averr_000\AppData\Local\Temp\go-build264456814\_\C_\Users\averr_000\Documents\GitHub\norp_toolkit\_obj\_cgo_main.c:7:30: warning: unused parameter 'c' [-Wunused-parameter]
 void _cgo_panic(void *a, int c) { }
                              ^
# _/C_/Users/averr_000/Documents/GitHub/norp_toolkit
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x8 pc=0x59c7e0]

goroutine 1 [running]:
cmd/link/internal/ld.writePESymTableRecords(0xc0424a2000, 0xc04249bbf0)
        c:/go/src/cmd/link/internal/ld/pe.go:1001 +0xa0
cmd/link/internal/ld.addpesymtable(0xc0424a2000)
        c:/go/src/cmd/link/internal/ld/pe.go:1022 +0x5f
cmd/link/internal/ld.Asmbpe(0xc0424a2000)
        c:/go/src/cmd/link/internal/ld/pe.go:1177 +0x1a8
cmd/link/internal/x86.asmb(0xc0424a2000)
        c:/go/src/cmd/link/internal/x86/asm.go:775 +0x38f
cmd/link/internal/ld.Main()
        c:/go/src/cmd/link/internal/ld/main.go:208 +0x968
main.main()
        c:/go/src/cmd/link/main.go:58 +0xe2
```

**Comment by therecipe** [comment]
Hey

The error seems to be caused by: `# _/C_/Users/averr_000/Documents/GitHub/norp_toolkit`
Is this your package?
If yes, do you make use of qtmoc in that package? (It looks like it makes use of cgo at least)

Another thing, do you import that package regularly through you GOPATH?
Or do you import it locally with a regular or absolute path?
(The `_` prefix is iirc appended when a local package is used)

If you import it locally, could you maybe move it into your GOPATH and import it regularly?
Because local imports are not supported, I think.

**Comment by averrin** [comment]
I develop it on linux and it works like charm.
Yes, its my package. I use golang plugins and qml from your package.
I didnt import any local packages, for now all code in main package.  

On windows i just run qtdeploy without any changes in code. Main app was pretty simple: https://github.com/averrin/norp_toolkit/blob/94aaa75fab51f7a78413a60d68c12201f03da910/main.go

**Comment by therecipe** [comment]
Ah, sorry it's the main package.
Okay then it makes sense :D
I will try to reproduce it.

**Comment by therecipe** [comment]
@averrin 
Okay, tested it on 3b92f7aebfd158d44de05d799189fcee99de96db and it did work for me.
I compiled it from darwin to windows with
`export QT_MXE_ARCH=amd64 && export QT_MXE_STATIC=true && qtdeploy -docker build windows` and on windows with msys2. (and also for darwin and android) 

Did you used the official prebuilt Qt version on windows?
And could you maybe test it again?
If it crashes again, I will setup a fresh vm to test it with the official prebuilt Qt version as well.

**Comment by averrin** [comment]
I use https://download.qt.io/official_releases/qt/5.8/5.8.0/qt-opensource-windows-x86-mingw530-5.8.0.exe on Win 10 (1703 - 16199.1000)/
I did update your package and run `qtdeploy build windows .` and got same result.
I will try others installation variants, but i prefer use regular.

**Comment by averrin** [comment]
I did msys installation. Now qtdeploy works, but build take 5-10 minutes per run. Its too long=(

**Comment by therecipe** [comment]
Mh, I did reproduce it on windows 7 with the official Qt version.
I will look into it.
