### ISSUE TITLE
qtmoc panic

### ISSUE THREAD

**Issue by bclermont** [therecipe/qt#408]
this step used to works for few hundred times before and it just started to fail today (the docker image get automatically pull'ed by our CI server

```
+ qtmoc /go/src/xxx/yyy/
time="2017-07-24T10:01:09Z" level=panic msg="failed to recognize build target /go/src/go/src/xxx/yyy" 
panic: (*logrus.Entry) (0x6a1c00,0xc42005e550)

goroutine 1 [running]:
github.com/Sirupsen/logrus.Entry.log(0xc42005e0f0, 0xc420015050, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/home/user/work/src/github.com/Sirupsen/logrus/entry.go:125 +0x33e
github.com/Sirupsen/logrus.(*Entry).Panic(0xc42005e460, 0xc420163c80, 0x1, 0x1)
	/home/user/work/src/github.com/Sirupsen/logrus/entry.go:170 +0x127
github.com/Sirupsen/logrus.(*Entry).Panicf(0xc42005e460, 0x6e1428, 0x23, 0xc420051d88, 0x1, 0x1)
	/home/user/work/src/github.com/Sirupsen/logrus/entry.go:218 +0x101
github.com/Sirupsen/logrus.(*Logger).Panicf(0xc42005e0f0, 0x6e1428, 0x23, 0xc420051d88, 0x1, 0x1)
	/home/user/work/src/github.com/Sirupsen/logrus/logger.go:173 +0x94
github.com/therecipe/qt/internal/utils.CheckBuildTarget(0x7ffd8a08815f, 0x2b)
	/home/user/work/src/github.com/therecipe/qt/internal/utils/env.go:78 +0x5d8
main.main()
/home/user/work/src/github.com/therecipe/qt/cmd/qtmoc/main.go:81 +0x2b5
```

**Comment by quantonganh** [comment]
Is there any different between:

```
cd /path/to/dir
qtmoc
```

and:

```
qtmoc /path/to/dir
```

Looks like I didn't get this error if `cd` into that directory before running `qtmoc`.

**Comment by therecipe** [comment]
Hey

@bclermont 
You will need to run `qtmoc desktop /go/src/go/src/xxx/yyy` or `qtmoc linux /go/src/go/src/xxx/yyy` instead.

@quantonganh
Yeah, running qtmoc without arguments is the same as running:
`qtmoc desktop $PWD`
