### ISSUE TITLE
qtdeploy mkdir panic

### ISSUE THREAD

**Issue by bclermont** [therecipe/qt#435]
This bug appeared in the latest build

```
time="2017-08-23T01:13:49Z" level=panic msg="failed to create dir /go/src/x/ui/lib/deploy/linux/lib" error="mkdir /go/src/x/ui/lib/deploy/linux/lib: not a directory"
panic: (*logrus.Entry) (0x7f9140,0xc42820b590)

goroutine 1 [running]:
github.com/Sirupsen/logrus.Entry.log(0xc42008c0a0, 0xc428809ad0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/home/user/work/src/github.com/Sirupsen/logrus/entry.go:125 +0x33e
github.com/Sirupsen/logrus.(*Entry).Panic(0xc42820b400, 0xc42da5cf88, 0x1, 0x1)
	/home/user/work/src/github.com/Sirupsen/logrus/entry.go:170 +0x127
github.com/Sirupsen/logrus.(*Entry).Panicf(0xc42820b400, 0x82a8e4, 0x17, 0xc42da5d000, 0x1, 0x1)
	/home/user/work/src/github.com/Sirupsen/logrus/entry.go:218 +0x101
github.com/therecipe/qt/internal/utils.MkdirAll(0xc423386940, 0x35, 0x2, 0xc423386940)
	/home/user/work/src/github.com/therecipe/qt/internal/utils/utils.go:26 +0x131
github.com/therecipe/qt/internal/cmd/deploy.bundle(0x7ffd0a5811c7, 0x5, 0x8036c0, 0x5, 0xc420067890, 0x24, 0xc4200678b1, 0x3, 0xc42006aa40, 0x31)
	/home/user/work/src/github.com/therecipe/qt/internal/cmd/deploy/bundle.go:89 +0x202d
github.com/therecipe/qt/internal/cmd/deploy.Deploy(0x7ffd0a5811c7, 0x5, 0x8036c0, 0x5, 0xc420067890, 0x24, 0x0, 0x7ffd0a581117, 0xaf, 0x0, ...)
	/home/user/work/src/github.com/therecipe/qt/internal/cmd/deploy/deploy.go:60 +0xe4b
main.main()
/home/user/work/src/github.com/therecipe/qt/cmd/qtdeploy/main.go:117 +0x54b
```

**Comment by quantonganh** [comment]
https://github.com/therecipe/qt/blob/master/internal/cmd/deploy/bundle.go#L89

The reason is our module name is `lib`:

> DEBU[0022] Execute                                       cmd="go build -p 2 -v -ldflags=\"-s\" \"-w\" -o /go/src/xx/aop/wl/ui/lib/deploy/linux/lib -tags=\"minimal\"" env= func=RunCmd name="build for linux on linux"

**Comment by therecipe** [comment]
>The reason is our module name is lib:

Yeah, `lib`, `linux` and `qml` are somewhat reserved names on linux.
