### ISSUE TITLE
Windows installed fail.

### ISSUE THREAD

**Issue by skiy** [therecipe/qt#488]
RUN 
```
$GOPATH/bin/qtsetup
```

```
admin@DESKTOP-FH1JOHS MINGW64 ~/Desktop
$ $GOPATH/bin/qtsetup
time="2017-10-27T16:39:14+08:00" level=info msg="running: 'qtsetup prep'"
time="2017-10-27T16:39:14+08:00" level=error msg="failed to run command" cmd="cmd /C mklink /H G:\\studying\\golang\\usr\\bi                                                                                                                 n\\qtrcc.exe C:\\Go\\bin\\qtrcc.exe" env= error="exit status 1" func=RunCmdOptional name="failed to create qtrcc symlink in                                                                                                                  your PATH (G:\\studying\\golang\\usr\\bin\\qtrcc.exe); please use C:\\Go\\bin\\qtrcc.exe instead"
ϵͳ▒Ҳ▒▒▒ָ▒▒▒▒▒ļ▒▒▒

time="2017-10-27T16:39:14+08:00" level=error msg="failed to run command" cmd="cmd /C mklink /H G:\\studying\\golang\\usr\\bi                                                                                                                 n\\qtmoc.exe C:\\Go\\bin\\qtmoc.exe" env= error="exit status 1" func=RunCmdOptional name="failed to create qtmoc symlink in                                                                                                                  your PATH (G:\\studying\\golang\\usr\\bin\\qtmoc.exe); please use C:\\Go\\bin\\qtmoc.exe instead"
ϵͳ▒Ҳ▒▒▒ָ▒▒▒▒▒ļ▒▒▒

time="2017-10-27T16:39:14+08:00" level=error msg="failed to run command" cmd="cmd /C mklink /H G:\\studying\\golang\\usr\\bi                                                                                                                 n\\qtminimal.exe C:\\Go\\bin\\qtminimal.exe" env= error="exit status 1" func=RunCmdOptional name="failed to create qtminimal                                                                                                                  symlink in your PATH (G:\\studying\\golang\\usr\\bin\\qtminimal.exe); please use C:\\Go\\bin\\qtminimal.exe instead"
ϵͳ▒Ҳ▒▒▒ָ▒▒▒▒▒ļ▒▒▒

time="2017-10-27T16:39:14+08:00" level=error msg="failed to run command" cmd="cmd /C mklink /H G:\\studying\\golang\\usr\\bi                                                                                                                 n\\qtdeploy.exe C:\\Go\\bin\\qtdeploy.exe" env= error="exit status 1" func=RunCmdOptional name="failed to create qtdeploy sy                                                                                                                 mlink in your PATH (G:\\studying\\golang\\usr\\bin\\qtdeploy.exe); please use C:\\Go\\bin\\qtdeploy.exe instead"
ϵͳ▒Ҳ▒▒▒ָ▒▒▒▒▒ļ▒▒▒

time="2017-10-27T16:39:14+08:00" level=error msg="failed to run command" cmd="cmd /C mklink /H G:\\studying\\golang\\usr\\bi                                                                                                                 n\\go.exe C:\\Go\\bin\\go.exe" env= error="exit status 1" func=RunCmdOptional name="failed to create go symlink in your PATH                                                                                                                  (G:\\studying\\golang\\usr\\bin\\go.exe); please use C:\\Go\\bin\\go.exe instead"
ϵͳ▒Ҳ▒▒▒ָ▒▒▒▒·▒▒▒▒

time="2017-10-27T16:39:14+08:00" level=info msg="running: 'qtsetup check windows' [docker=false] [vagrant=false]"
time="2017-10-27T16:39:15+08:00" level=info msg="GOOS:                        'windows'"
time="2017-10-27T16:39:15+08:00" level=info msg="GOARCH:                      'amd64'"
time="2017-10-27T16:39:15+08:00" level=info msg="GOVERSION:                   'go1.9.2'"
time="2017-10-27T16:39:15+08:00" level=info msg="GOROOT:                   *  'C:\\Go\\'"
time="2017-10-27T16:39:15+08:00" level=info msg="GOPATH:                   *  'G:\\studying\\golang'"
time="2017-10-27T16:39:15+08:00" level=info msg="GOBIN:                    *  'C:\\Go\\bin'"
time="2017-10-27T16:39:15+08:00" level=info msg="QT_HASH:                     '599f8bc2c975802ea592c43d110209f0a267b188'"
time="2017-10-27T16:39:15+08:00" level=info msg="QT_VERSION:                  '5.9.1'"
time="2017-10-27T16:39:15+08:00" level=info msg="QT_VERSION_MAJOR:            '5.9.1'"
time="2017-10-27T16:39:15+08:00" level=info msg="QT_DIR:                   *  'C:\\Qt\\Qt5.9.2'"
time="2017-10-27T16:39:15+08:00" level=info msg="QT_STUB:                     'true'"
time="2017-10-27T16:39:15+08:00" level=info msg="QT_DEBUG:                    'false'"
time="2017-10-27T16:39:15+08:00" level=info msg="QT_QMAKE_DIR:                ''"
time="2017-10-27T16:39:15+08:00" level=info msg="QT_WEBKIT:                   'false'"
time="2017-10-27T16:39:15+08:00" level=info msg="QT_MSYS2:                 *  'true'"
time="2017-10-27T16:39:15+08:00" level=info msg="QT_MSYS2_DIR:             *  'G:\\studying\\golang\\mingw64'"
time="2017-10-27T16:39:15+08:00" level=panic msg="failed to find QT_MSYS2_DIR (G:\\studying\\golang\\mingw64)" error="open G                                                                                                                 :\\studying\\golang\\mingw64: The system cannot find the file specified."
panic: (*logrus.Entry) (0x7fa220,0xc042082fa0)

goroutine 1 [running]:
github.com/Sirupsen/logrus.Entry.log(0xc0420820a0, 0xc042308cc0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        G:/studying/golang/src/github.com/Sirupsen/logrus/entry.go:128 +0x61c
github.com/Sirupsen/logrus.(*Entry).Panic(0xc042082f50, 0xc0420697a0, 0x1, 0x1)
        G:/studying/golang/src/github.com/Sirupsen/logrus/entry.go:173 +0xb1
github.com/Sirupsen/logrus.(*Entry).Panicf(0xc042082f50, 0x8296b8, 0x16, 0xc042069b48, 0x2, 0x2)
        G:/studying/golang/src/github.com/Sirupsen/logrus/entry.go:221 +0xfe
github.com/therecipe/qt/internal/cmd/setup.Check(0x80636d, 0x7, 0x800000)
        G:/studying/golang/src/github.com/therecipe/qt/internal/cmd/setup/check.go:141 +0x1417
main.main()
        G:/studying/golang/src/github.com/therecipe/qt/cmd/qtsetup/main.go:87 +0x236

```

**Comment by skiy** [comment]
Like #467
