### ISSUE TITLE
Arch Linux - windows is not supported with PkgConfig

### ISSUE THREAD

**Issue by PapiCZ** [therecipe/qt#546]
Hello.
I wanted to build app for windows, but I am getting following error...
```
❯ QT_PKG_CONFIG=true ~/go/bin/qtdeploy build windows .
FATA[0000] windows is not supported as a deploy target on linux with PkgConfig -> install the official Qt version instead and try again
```

I can't set `QT_PKG_CONFIG` to `false`, because then I get totally bad paths. For example `/home/papi/Qt5.10.0/Docs/Qt-5.10.0/qtpositioning/qtpositioning.index` is for me in `/usr/share/doc/qt/qtpositioning/qtpositioning.index`, so changing `QT_DIR` wouldn't help me.
```
❯ QT_PKG_CONFIG=false ~/go/bin/qtdeploy build windows .
ERRO[0000] failed to load /home/papi/Qt5.10.0/Docs/Qt-5.10.0/qtpositioning/qtpositioning.index  error="open /home/papi/Qt5.10.0/Docs/Qt-5.10.0/qtpositioning/qtpositioning.index: no such file or directory"
WARN[0000] parser.LoadModule                             error=EOF module=Positioning
ERRO[0000] failed to load /home/papi/Qt5.10.0/Docs/Qt-5.10.0/qtwebchannel/qtwebchannel.index  error="open /home/papi/Qt5.10.0/Docs/Qt-5.10.0/qtwebchannel/qtwebchannel.index: no such file or directory"
WARN[0000] parser.LoadModule                             error=EOF module=WebChannel
ERRO[0000] failed to load /home/papi/Qt5.10.0/Docs/Qt-5.10.0/qtwebsockets/qtwebsockets.index  error="open /home/papi/Qt5.10.0/Docs/Qt-5.10.0/qtwebsockets/qtwebsockets.index: no such file or directory"
WARN[0000] parser.LoadModule                             error=EOF module=WebSockets
ERRO[0000] failed to load /home/papi/Qt5.10.0/Docs/Qt-5.10.0/qthelp/qthelp.index  error="open /home/papi/Qt5.10.0/Docs/Qt-5.10.0/qthelp/qthelp.index: no such file or directory"
WARN[0000] parser.LoadModule                             error=EOF module=Help
ERRO[0000] failed to load /home/papi/Qt5.10.0/Docs/Qt-5.10.0/qtsql/qtsql.index  error="open /home/papi/Qt5.10.0/Docs/Qt-5.10.0/qtsql/qtsql.index: no such file or directory"
WARN[0000] parser.LoadModule                             error=EOF module=Sql
ERRO[0000] failed to load /home/papi/Qt5.10.0/Docs/Qt-5.10.0/qtxmlpatterns/qtxmlpatterns.index  error="open /home/papi/Qt5.10.0/Docs/Qt-5.10.0/qtxmlpatterns/qtxmlpatterns.index: no such file or directory"
WARN[0000] parser.LoadModule                             error=EOF module=XmlPatterns
ERRO[0000] failed to load /home/papi/Qt5.10.0/Docs/Qt-5.10.0/qtpurchasing/qtpurchasing.index  error="open /home/papi/Qt5.10.0/Docs/Qt-5.10.0/qtpurchasing/qtpurchasing.index: no such file or directory"
WARN[0000] parser.LoadModule                             error=EOF module=Purchasing
ERRO[0000] failed to load /home/papi/Qt5.10.0/Docs/Qt-5.10.0/qtsensors/qtsensors.index  error="open /home/papi/Qt5.10.0/Docs/Qt-5.10.0/qtsensors/qtsensors.index: no such file or directory"
WARN[0000] parser.LoadModule                             error=EOF module=Sensors
ERRO[0000] failed to load /home/papi/Qt5.10.0/Docs/Qt-5.10.0/qtprintsupport/qtprintsupport.index  error="open /home/papi/Qt5.10.0/Docs/Qt-5.10.0/qtprintsupport/qtprintsupport.index: no such file or directory"
WARN[0000] parser.LoadModule                             error=EOF module=PrintSupport
ERRO[0000] failed to load /home/papi/Qt5.10.0/Docs/Qt-5.10.0/qtqml/qtqml.index  error="open /home/papi/Qt5.10.0/Docs/Qt-5.10.0/qtqml/qtqml.index: no such file or directory"
WARN[0000] parser.LoadModule                             error=EOF module=Qml
ERRO[0000] failed to load /home/papi/Qt5.10.0/Docs/Qt-5.10.0/qtcore/qtcore.index  error="open /home/papi/Qt5.10.0/Docs/Qt-5.10.0/qtcore/qtcore.index: no such file or directory"
WARN[0000] parser.LoadModule                             error=EOF module=Core
ERRO[0000] failed to load /home/papi/Qt5.10.0/Docs/Qt-5.10.0/qtsvg/qtsvg.index  error="open /home/papi/Qt5.10.0/Docs/Qt-5.10.0/qtsvg/qtsvg.index: no such file or directory"
WARN[0000] parser.LoadModule                             error=EOF module=Svg
ERRO[0000] failed to load /home/papi/Qt5.10.0/Docs/Qt-5.10.0/qtdbus/qtdbus.index  error="open /home/papi/Qt5.10.0/Docs/Qt-5.10.0/qtdbus/qtdbus.index: no such file or directory"
WARN[0000] parser.LoadModule                             error=EOF module=DBus
ERRO[0000] failed to load /home/papi/Qt5.10.0/Docs/Qt-5.10.0/qtandroidextras/qtandroidextras.index  error="open /home/papi/Qt5.10.0/Docs/Qt-5.10.0/qtandroidextras/qtandroidextras.index: no such file or directory"
WARN[0000] parser.LoadModule                             error=EOF module=AndroidExtras
ERRO[0000] failed to load /home/papi/Qt5.10.0/Docs/Qt-5.10.0/qtlocation/qtlocation.index  error="open /home/papi/Qt5.10.0/Docs/Qt-5.10.0/qtlocation/qtlocation.index: no such file or directory"
WARN[0000] parser.LoadModule                             error=EOF module=Location
ERRO[0000] failed to load /home/papi/Qt5.10.0/Docs/Qt-5.10.0/qtgui/qtgui.index  error="open /home/papi/Qt5.10.0/Docs/Qt-5.10.0/qtgui/qtgui.index: no such file or directory"
WARN[0000] parser.LoadModule                             error=EOF module=Gui
ERRO[0000] failed to load /home/papi/Qt5.10.0/Docs/Qt-5.10.0/qtnfc/qtnfc.index  error="open /home/papi/Qt5.10.0/Docs/Qt-5.10.0/qtnfc/qtnfc.index: no such file or directory"
WARN[0000] parser.LoadModule                             error=EOF module=Nfc
ERRO[0000] failed to load /home/papi/Qt5.10.0/Docs/Qt-5.10.0/qtscripttools/qtscripttools.index  error="open /home/papi/Qt5.10.0/Docs/Qt-5.10.0/qtscripttools/qtscripttools.index: no such file or directory"
WARN[0000] parser.LoadModule                             error=EOF module=ScriptTools
ERRO[0000] failed to load /home/papi/Qt5.10.0/Docs/Qt-5.10.0/qtnetwork/qtnetwork.index  error="open /home/papi/Qt5.10.0/Docs/Qt-5.10.0/qtnetwork/qtnetwork.index: no such file or directory"
WARN[0000] parser.LoadModule                             error=EOF module=Network
ERRO[0000] failed to load /home/papi/Qt5.10.0/Docs/Qt-5.10.0/qtscript/qtscript.index  error="open /home/papi/Qt5.10.0/Docs/Qt-5.10.0/qtscript/qtscript.index: no such file or directory"
WARN[0000] parser.LoadModule                             error=EOF module=Script
ERRO[0000] failed to load /home/papi/Qt5.10.0/Docs/Qt-5.10.0/qtuitools/qtuitools.index  error="open /home/papi/Qt5.10.0/Docs/Qt-5.10.0/qtuitools/qtuitools.index: no such file or directory"
WARN[0000] parser.LoadModule                             error=EOF module=UiTools
ERRO[0000] failed to load /home/papi/Qt5.10.0/Docs/Qt-5.10.0/qtbluetooth/qtbluetooth.index  error="open /home/papi/Qt5.10.0/Docs/Qt-5.10.0/qtbluetooth/qtbluetooth.index: no such file or directory"
WARN[0000] parser.LoadModule                             error=EOF module=Bluetooth
ERRO[0000] failed to load /home/papi/Qt5.10.0/Docs/Qt-5.10.0/qtxml/qtxml.index  error="open /home/papi/Qt5.10.0/Docs/Qt-5.10.0/qtxml/qtxml.index: no such file or directory"
WARN[0000] parser.LoadModule                             error=EOF module=Xml
ERRO[0000] failed to load /home/papi/Qt5.10.0/Docs/Qt-5.10.0/qtremoteobjects/qtremoteobjects.index  error="open /home/papi/Qt5.10.0/Docs/Qt-5.10.0/qtremoteobjects/qtremoteobjects.index: no such file or directory"
WARN[0000] parser.LoadModule                             error=EOF module=RemoteObjects
ERRO[0000] failed to load /home/papi/Qt5.10.0/Docs/Qt-5.10.0/qtwebengine/qtwebengine.index  error="open /home/papi/Qt5.10.0/Docs/Qt-5.10.0/qtwebengine/qtwebengine.index: no such file or directory"
WARN[0000] parser.LoadModule                             error=EOF module=WebEngine
ERRO[0000] failed to load /home/papi/Qt5.10.0/Docs/Qt-5.10.0/qtgamepad/qtgamepad.index  error="open /home/papi/Qt5.10.0/Docs/Qt-5.10.0/qtgamepad/qtgamepad.index: no such file or directory"
WARN[0000] parser.LoadModule                             error=EOF module=Gamepad
ERRO[0000] failed to load /home/papi/Qt5.10.0/Docs/Qt-5.10.0/qtmultimedia/qtmultimedia.index  error="open /home/papi/Qt5.10.0/Docs/Qt-5.10.0/qtmultimedia/qtmultimedia.index: no such file or directory"
WARN[0000] parser.LoadModule                             error=EOF module=Multimedia
ERRO[0000] failed to load /home/papi/Qt5.10.0/Docs/Qt-5.10.0/qtdatavisualization/qtdatavisualization.index  error="open /home/papi/Qt5.10.0/Docs/Qt-5.10.0/qtdatavisualization/qtdatavisualization.index: no such file or directory"
ERRO[0000] failed to load /home/papi/Qt5.10.0/Docs/Qt-5.10.0/qtquickcontrols2/qtquickcontrols2.index  error="open /home/papi/Qt5.10.0/Docs/Qt-5.10.0/qtquickcontrols2/qtquickcontrols2.index: no such file or directory"
WARN[0000] parser.LoadModule                             error=EOF module=QuickControls2
ERRO[0000] failed to load /home/papi/Qt5.10.0/Docs/Qt-5.10.0/qttestlib/qttestlib.index  error="open /home/papi/Qt5.10.0/Docs/Qt-5.10.0/qttestlib/qttestlib.index: no such file or directory"
WARN[0000] parser.LoadModule                             error=EOF module=TestLib
ERRO[0000] failed to load /home/papi/Qt5.10.0/Docs/Qt-5.10.0/qtcharts/qtcharts.index  error="open /home/papi/Qt5.10.0/Docs/Qt-5.10.0/qtcharts/qtcharts.index: no such file or directory"
ERRO[0000] failed to load /home/papi/Qt5.10.0/Docs/Qt-5.10.0/qtserialport/qtserialport.index  error="open /home/papi/Qt5.10.0/Docs/Qt-5.10.0/qtserialport/qtserialport.index: no such file or directory"
WARN[0000] parser.LoadModule                             error=EOF module=SerialPort
ERRO[0000] failed to load /home/papi/Qt5.10.0/Docs/Qt-5.10.0/qtwebview/qtwebview.index  error="open /home/papi/Qt5.10.0/Docs/Qt-5.10.0/qtwebview/qtwebview.index: no such file or directory"
WARN[0000] parser.LoadModule                             error=EOF module=WebView
ERRO[0000] failed to load /home/papi/Qt5.10.0/Docs/Qt-5.10.0/qtspeech/qtspeech.index  error="open /home/papi/Qt5.10.0/Docs/Qt-5.10.0/qtspeech/qtspeech.index: no such file or directory"
WARN[0000] parser.LoadModule                             error=EOF module=Speech
ERRO[0000] failed to load /home/papi/Qt5.10.0/Docs/Qt-5.10.0/qtdesigner/qtdesigner.index  error="open /home/papi/Qt5.10.0/Docs/Qt-5.10.0/qtdesigner/qtdesigner.index: no such file or directory"
WARN[0000] parser.LoadModule                             error=EOF module=Designer
ERRO[0000] failed to load /home/papi/Qt5.10.0/Docs/Qt-5.10.0/qtwidgets/qtwidgets.index  error="open /home/papi/Qt5.10.0/Docs/Qt-5.10.0/qtwidgets/qtwidgets.index: no such file or directory"
WARN[0000] parser.LoadModule                             error=EOF module=Widgets
ERRO[0000] failed to load /home/papi/Qt5.10.0/Docs/Qt-5.10.0/qtserialbus/qtserialbus.index  error="open /home/papi/Qt5.10.0/Docs/Qt-5.10.0/qtserialbus/qtserialbus.index: no such file or directory"
WARN[0000] parser.LoadModule                             error=EOF module=SerialBus
ERRO[0000] failed to load /home/papi/Qt5.10.0/Docs/Qt-5.10.0/qtquick/qtquick.index  error="open /home/papi/Qt5.10.0/Docs/Qt-5.10.0/qtquick/qtquick.index: no such file or directory"
WARN[0000] parser.LoadModule                             error=EOF module=Quick
ERRO[0000] failed to load /home/papi/Qt5.10.0/Docs/Qt-5.10.0/qtscxml/qtscxml.index  error="open /home/papi/Qt5.10.0/Docs/Qt-5.10.0/qtscxml/qtscxml.index: no such file or directory"
WARN[0000] parser.LoadModule                             error=EOF module=Scxml
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x110 pc=0x6e5add]

goroutine 1 [running]:
github.com/therecipe/qt/internal/cmd/minimal.Minimal(0xc420080660, 0x21, 0x7fffb74c3530, 0x7, 0x0, 0x0)
	/home/papi/go/src/github.com/therecipe/qt/internal/cmd/minimal/minimal.go:150 +0xb0d
github.com/therecipe/qt/internal/cmd/deploy.Deploy(0x7fffb74c352a, 0x5, 0x7fffb74c3530, 0x7, 0xc420080660, 0x21, 0x0, 0x0, 0x0, 0x0, ...)
	/home/papi/go/src/github.com/therecipe/qt/internal/cmd/deploy/deploy.go:54 +0xd42
main.main()
	/home/papi/go/src/github.com/therecipe/qt/cmd/qtdeploy/main.go:117 +0x517
```

**Comment by therecipe** [comment]
Hey

Yeah, to deploy from linux to windows you will need to use the docker images:
https://github.com/therecipe/qt/wiki/Deploying-Linux-to-Windows-32-bit-Shared
