### ISSUE TITLE
Can I build qt project under andriod with qtdeploy

### ISSUE THREAD

**Issue by HardDie** [therecipe/qt#579]
I'm not clearly understand this project only for go application?
And if I can build qt application how can I do that?
qtsetup -docker was finised successfull and show me few examples application.

**Comment by therecipe** [comment]
Hey

Yes, you can build for android.
Just run `docker pull therecipe/qt:android` and then `qtdeploy -docker build android` inside the folder containing your code. 
(For example in `$GOPATH/src/github.com/therecipe/qt/internal/examples/widgets/line_edits`)

**Comment by HardDie** [comment]
No I mean build Qt project under android, not go.
I did what you said and what I saw
```╭─root@ICONIA /home/harddie/go/src/TestMaker (19:13:56)
╰─# ../../bin/qtdeploy -docker build android                                                                                                                                                                   127 ↵
PANI[0000] Project needs to be inside GOPATH /home/harddie/go/src/TestMaker /root/go
panic: (*logrus.Entry) (0x7d8680,0xc4200988c0)

goroutine 1 [running]:
github.com/sirupsen/logrus.Entry.log(0xc420098190, 0xc42008b380, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /home/harddie/go/src/github.com/sirupsen/logrus/entry.go:112 +0x254
github.com/sirupsen/logrus.(*Entry).Panic(0xc4200985a0, 0xc420057458, 0x1, 0x1)
        /home/harddie/go/src/github.com/sirupsen/logrus/entry.go:182 +0xaa
github.com/sirupsen/logrus.(*Entry).Panicln(0xc4200985a0, 0xc4200579c0, 0x3, 0x3)
        /home/harddie/go/src/github.com/sirupsen/logrus/entry.go:277 +0xd5
github.com/sirupsen/logrus.(*Logger).Panicln(0xc420098190, 0xc4200579c0, 0x3, 0x3)
        /home/harddie/go/src/github.com/sirupsen/logrus/logger.go:299 +0x6d
github.com/therecipe/qt/internal/cmd.virtual(0xc4200d4a00, 0x6, 0xa, 0x7ffd5e85b76f, 0x7, 0xc42001c034, 0x1e, 0x100, 0x7e348c, 0x5)
        /home/harddie/go/src/github.com/therecipe/qt/internal/cmd/cmd.go:234 +0x24ed
github.com/therecipe/qt/internal/cmd.Docker(0xc4200987d0, 0x5, 0x5, 0x7ffd5e85b76f, 0x7, 0xc42001c034, 0x1e, 0x0)
        /home/harddie/go/src/github.com/therecipe/qt/internal/cmd/cmd.go:54 +0x8d
github.com/therecipe/qt/internal/cmd/deploy.Deploy(0x7ffd5e85b769, 0x5, 0x7ffd5e85b76f, 0x7, 0xc42001c034, 0x1e, 0x1, 0x0, 0x0, 0x0, ...)
        /home/harddie/go/src/github.com/therecipe/qt/internal/cmd/deploy/deploy.go:34 +0x704
main.main()
        /home/harddie/go/src/github.com/therecipe/qt/cmd/qtdeploy/main.go:117 +0x4f8
╭─root@ICONIA /home/harddie/go/src/TestMaker (19:14:10)
╰─# ls -la                                                                                                                                                                                                           
total 68K
-rw-r--r-- 1 root    root    82 Mar 28 21:38 cgo_main_wrapper.go
-rw-r--r-- 1 harddie users  175 Mar 28 20:58 global.cpp
-rw-r--r-- 1 harddie users  109 Mar 28 20:58 global.h
-rw-r--r-- 1 harddie users  439 Mar 28 20:58 main.cpp
-rw-r--r-- 1 harddie users 5.9K Mar 28 20:58 testchartranslate.cpp
-rw-r--r-- 1 harddie users  645 Mar 28 20:58 testchartranslate.h
-rw-r--r-- 1 harddie users   28 Mar 28 20:58 testfunctions.cpp
-rw-r--r-- 1 harddie users  211 Mar 28 20:58 testfunctions.h
-rw-r--r-- 1 harddie users 4.4K Mar 28 20:58 testmaker.cpp
-rw-r--r-- 1 harddie users 1.6K Mar 28 20:58 testmaker.h
-rw-r--r-- 1 harddie users  574 Mar 28 20:58 TestMaker.pro
-rw-r--r-- 1 harddie users  11K Mar 28 20:58 uitestmaker.cpp
-rw-r--r-- 1 harddie users 1.4K Mar 28 20:58 uitestmaker.h
```

What's wrong?

And that I did in $GOPATH/src/github.com/therecipe/qt/internal/examples/widgets/line_edits
```
╭─root@ICONIA /home/harddie/go/src/github.com/therecipe/qt/internal/examples/widgets/line_edits (19:17:38)
╰─# /home/harddie/go/bin/qtdeploy -docker build android
PANI[0000] Project needs to be inside GOPATH /home/harddie/go/src/github.com/therecipe/qt/internal/examples/widgets/line_edits /root/go
panic: (*logrus.Entry) (0x7d8680,0xc4200968c0)

goroutine 1 [running]:
github.com/sirupsen/logrus.Entry.log(0xc420096190, 0xc420089380, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /home/harddie/go/src/github.com/sirupsen/logrus/entry.go:112 +0x254
github.com/sirupsen/logrus.(*Entry).Panic(0xc4200965a0, 0xc420057458, 0x1, 0x1)
        /home/harddie/go/src/github.com/sirupsen/logrus/entry.go:182 +0xaa
github.com/sirupsen/logrus.(*Entry).Panicln(0xc4200965a0, 0xc4200579c0, 0x3, 0x3)
        /home/harddie/go/src/github.com/sirupsen/logrus/entry.go:277 +0xd5
github.com/sirupsen/logrus.(*Logger).Panicln(0xc420096190, 0xc4200579c0, 0x3, 0x3)
        /home/harddie/go/src/github.com/sirupsen/logrus/logger.go:299 +0x6d
github.com/therecipe/qt/internal/cmd.virtual(0xc4200d4aa0, 0x6, 0xa, 0x7fff0ed6e745, 0x7, 0xc42001e004, 0x51, 0x100, 0x7e348c, 0x5)
        /home/harddie/go/src/github.com/therecipe/qt/internal/cmd/cmd.go:234 +0x24ed
github.com/therecipe/qt/internal/cmd.Docker(0xc4200967d0, 0x5, 0x5, 0x7fff0ed6e745, 0x7, 0xc42001e004, 0x51, 0x0)
        /home/harddie/go/src/github.com/therecipe/qt/internal/cmd/cmd.go:54 +0x8d
github.com/therecipe/qt/internal/cmd/deploy.Deploy(0x7fff0ed6e73f, 0x5, 0x7fff0ed6e745, 0x7, 0xc42001e004, 0x51, 0x1, 0x0, 0x0, 0x0, ...)
        /home/harddie/go/src/github.com/therecipe/qt/internal/cmd/deploy/deploy.go:34 +0x704
main.main()
        /home/harddie/go/src/github.com/therecipe/qt/cmd/qtdeploy/main.go:117 +0x4f8
```

**Comment by therecipe** [comment]
Ah, sorry yeah you should be able to use this images for plain C++ Qt developments as well.
As the images contain a regular linux + android installation of Qt.

You can probably use something like this:
```
docker run --rm -v /path/one/the/host:/media/sharedhost -i therecipe/qt:android qmake -spec android-g++ /media/sharedhost/path/to/projectfile.pro
```
and then
```
docker run --rm -v /path/one/the/host:/media/sharedhost -i therecipe/qt:android make /media/sharedhost/path/to/Makefile
```

but you will need to tweak these commands yourself and also learn the basics or docker.

(Also if you don't want to use this for Go development, then you don't need Go or `qtdeploy` at all.
As you can directly pull the images with `docker pull ...` and run your commands with `docker run ...`)

Hope this helps.

**Comment by HardDie** [comment]
Yes, it's really helpful, thank you very much!

**Comment by HardDie** [comment]
Yes it's really helpful thank you very much!
(sorry I'm not specialy reopen issue=) )

**Comment by HardDie** [comment]
Sorry, i have another question)
I'm already very close I feel it but it was not so easy as you write.
Because then I run 'qmake' and 'make' I got only libTestMaker.so binary, but I want get apk file.

First of all I'm start docker image and type command by myself
```
Start docker:
docker run --rm -v /home/harddie/go/src/TestMaker:/home/user/qt -i therecipe/qt:android

Run in docker:
ln -s /home/user/android-ndk-r14b /opt/android/android-r10e
ls -s /opt/Qt/5.10.0/android_armv7/bin/qmake /bin/
ln -s /home/user/android-sdk-linux /opt/android/sdk
ln -s /opt/Qt/5.10.0/android_armv7/bin/androiddeployqt /bin/
ln -s /home/user/android-sdk-linux/tools/proguard/ant /bin/

make install INSTALL_ROOT=/home/user/qt/
qmake -spec android-g++
make
androiddeployqt --output /home/user/qt/ --input android-libTestMaker.so-deployment-settings.json --ant /home/user/android-sdk-linux/tools/proguard/ant/
```
Everything I type in directory with project, but on last command I get error message and can't understand how resolve it
```
androiddeployqt --output /home/user/qt/ --input android-libTestMaker.so-deployment-settings.json
Cannot find ant in PATH. Please use --ant option to pass in the correct path.
Generating Android Package
  Input file: android-libTestMaker.so-deployment-settings.json
  Output directory: /home/user/qt/
  Application binary: /home/user/qt/libTestMaker.so
  Android build platform: android-25
  Install to device: No
```
Yes, I understand what it can't find some binary file ant, but I too can't find it in docker image only few folder with the same name.
Maybe you can help me? Or show what I did wrong.

My working directory now looking like that
```
╭─root@ICONIA /home/harddie/go/src/TestMaker (0:01:33)
╰─# ll
total 324K
-rw-r--r--  1 root    root   679 Mar 29 23:30 android-libTestMaker.so-deployment-settings.json
-rw-rw-r--  1 root    root  5.5K Mar 29 23:57 AndroidManifest.xml
drwxr-xr-x  3 root    root  4.0K Mar 29 23:35 assets/
-rw-rw-r--  1 root    root  1.5K Mar 29 23:33 build.gradle
-rw-r--r--  1 harddie users  175 Mar 28 20:58 global.cpp
-rw-r--r--  1 harddie users  109 Mar 28 20:58 global.h
-rw-r--r--  1 root    root  1.6K Mar 29 23:33 global.o
drwxr-xr-x  3 root    root  4.0K Mar 29 23:33 libs/
-rwxr-xr-x  1 root    root   42K Mar 29 23:33 libTestMaker.so*
-rw-r--r--  1 harddie users  439 Mar 28 20:58 main.cpp
-rw-r--r--  1 root    root  2.4K Mar 29 23:33 main.o
-rw-r--r--  1 root    root   97K Mar 29 23:30 Makefile
-rw-r--r--  1 root    root   13K Mar 29 23:33 moc_predefs.h
-rw-r--r--  1 root    root  5.1K Mar 29 23:33 moc_uitestmaker.cpp
-rw-r--r--  1 root    root  8.0K Mar 29 23:33 moc_uitestmaker.o
drwxr-xr-x 23 root    root  4.0K Mar 29 23:33 res/
drwxr-xr-x  3 root    root  4.0K Mar 29 23:33 src/
-rw-r--r--  1 harddie users 5.9K Mar 28 20:58 testchartranslate.cpp
-rw-r--r--  1 harddie users  645 Mar 28 20:58 testchartranslate.h
-rw-r--r--  1 root    root  2.0K Mar 29 23:33 testchartranslate.o
-rw-r--r--  1 harddie users   28 Mar 28 20:58 testfunctions.cpp
-rw-r--r--  1 harddie users  211 Mar 28 20:58 testfunctions.h
-rw-r--r--  1 root    root  1.6K Mar 29 23:33 testfunctions.o
drwxr-xr-x  2 root    root  4.0K Mar 29 23:30 TestMaker/
-rw-r--r--  1 harddie users 4.4K Mar 28 20:58 testmaker.cpp
-rw-r--r--  1 harddie users 1.6K Mar 28 20:58 testmaker.h
-rw-r--r--  1 root    root  8.2K Mar 29 23:33 testmaker.o
-rw-r--r--  1 harddie users  574 Mar 28 20:58 TestMaker.pro
-rw-r--r--  1 harddie users  11K Mar 28 20:58 uitestmaker.cpp
-rw-r--r--  1 harddie users 1.4K Mar 28 20:58 uitestmaker.h
-rw-r--r--  1 root    root   17K Mar 29 23:33 uitestmaker.o
```
Thank you in advance, really hope what you know how help me)

**Comment by therecipe** [comment]
No problem :)
Yeah, I switched from "ant" to "gradle" sometime ago because it was necessary to get it working with certain android libs.

You just need to call your androiddeployqt like this: 
https://github.com/therecipe/qt/blob/master/internal/cmd/deploy/bundle.go#L398:L407

And maybe you need to set JAVA_HOME as well, then you should just need to run
`export JAVA_HOME=$JDK_DIR`

Also maybe the gradle build will complain about old gradle libs or something, then create a file called: 
`gradle-wrapper.properties` three folders down (of your TestMaker folder)  in `TestMaker /build/gradle/wrapper`
https://github.com/therecipe/qt/blob/master/internal/cmd/deploy/bundle.go#L341:L343

with this content: https://github.com/therecipe/qt/blob/master/internal/cmd/deploy/assets.go#L112:L118

or look for the `gradle-wrapper.properties` somewhere on the system and change it to point to the other url.

**Comment by HardDie** [comment]
Yes!!! Everything work! I got APK file!!!
Thank you very much for your help!
