### ISSUE TITLE
support custom build mingw static qt

### ISSUE THREAD

**Issue by ismlsmile** [therecipe/qt#599]
I build a mingw static qt myself, and try to use qtsetup. The static mingw qt is in "D:\Dev\Qt5.10.0-static". I use the mingw inclueded in qt installer.
1. I open the mingw shell and set QT_DIR and QT_VERSION
2. qtsetup

The command failed as it want to find "D:\Dev\Qt5.10.0-static\5.10.0\mingw53_32\bin\qmake". Then I move the staitc mingw qt dirs to "D:\Dev\Qt5.10.0-static\5.10.0\mingw53_32" and this error disappers.

And I tried qtsetup again, there are many erros, the program crashed at:

[33mWARN[0m[0266] parser.LoadModule                             [33merror[0m=EOF [33mmodule[0m=QuickControls2
[33mWARN[0m[0266] parser.LoadModule                             [33merror[0m=EOF [33mmodule[0m=Quick
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x1 addr=0x110 pc=0x6efde3]

goroutine 1 [running]:
github.com/therecipe/qt/internal/cmd/minimal.Minimal(0xc0422436e0, 0x54, 0x80932f, 0x7, 0x0, 0x0)
        J:/Code/oschina/GOPATH/src/github.com/therecipe/qt/internal/cmd/minimal/minimal.go:150 +0xad3
github.com/therecipe/qt/internal/cmd/deploy.Deploy(0x807ca4, 0x4, 0x80932f, 0x7, 0xc0422436e0, 0x54, 0xc042018000, 0x0, 0x0, 0x0, ...)
        J:/Code/oschina/GOPATH/src/github.com/therecipe/qt/internal/cmd/deploy/deploy.go:61 +0xe29
github.com/therecipe/qt/internal/cmd/setup.Test(0x80932f, 0x7, 0x800000, 0x0, 0x0)
        J:/Code/oschina/GOPATH/src/github.com/therecipe/qt/internal/cmd/setup/test.go:148 +0x72c
main.main()
        J:/Code/oschina/GOPATH/src/github.com/therecipe/qt/cmd/qtsetup/main.go:99 +0x336

**Comment by ismlsmile** [comment]
sorry, I did not make it clear how I setup the env. I tried QT_QMAKE_DIR, but still failed.Here is the detail:
1. OS: Win10
2. I did not install msys2, I used the mingw versin included in Qt 5.10.0 installer.
3. I used the above mingw and compiled a static mingw version to "D:\Dev\Qt5.10.0-static". The folder is created by "mingw32-make install". And this folder contains "bin, include, lib..."
4. I add the mingw/bin dir to path env
5. I open a cmd window
(1) set QT_DIR=D:\Dev\Qt5.10.0-static
(2) set QT_QMAKE_DIR=D:\Dev\Qt5.10.0-static\bin
(3) set QT_VERSION=5.10.0
(4) qtsetup

finally, the program crashed at:

[36mINFO[0m[0259] installing full qt/speech
[36mINFO[0m[0265] installing full qt/quickcontrols2
[36mINFO[0m[0271] installing full qt/sailfish
[36mINFO[0m[0271] installing full qt/remoteobjects
[33mWARN[0m[0277] failed to install:
[33mWARN[0m[0277] androidextras
[36mINFO[0m[0277] running: 'qtsetup test windows' [docker=false] [vagrant=false]
[36mINFO[0m[0277] testing qml\application
[31mERRO[0m[0282] failed to load D:\Dev\Qt5.10.0-static\Docs\Qt-5.10.0\qtnetwork\qtnetwork.index  [31merror[0m="open D:\\Dev\\Qt5.10.0-static\\Docs\\Qt-5.10.0\\qtnetwork\\qtnetwork.index: The system cannot find the path specified."
[33mWARN[0m[0282] parser.LoadModule                             [33merror[0m=EOF [33mmodule[0m=Network
[31mERRO[0m[0282] failed to load D:\Dev\Qt5.10.0-static\Docs\Qt-5.10.0\qthelp\qthelp.index  [31merror[0m="open D:\\Dev\\Qt5.10.0-static\\Docs\\Qt-5.10.0\\qthelp\\qthelp.index: The system cannot find the path specified."
[33mWARN[0m[0282] parser.LoadModule                             [33merror[0m=EOF [33mmodule[0m=Help
[31mERRO[0m[0282] failed to load D:\Dev\Qt5.10.0-static\Docs\Qt-5.10.0\qtspeech\qtspeech.index  [31merror[0m="open D:\\Dev\\Qt5.10.0-static\\Docs\\Qt-5.10.0\\qtspeech\\qtspeech.index: The system cannot find the path specified."
[33mWARN[0m[0282] parser.LoadModule                             [33merror[0m=EOF [33mmodule[0m=Speech
[31mERRO[0m[0282] failed to load D:\Dev\Qt5.10.0-static\Docs\Qt-5.10.0\qtscxml\qtscxml.index  [31merror[0m="open D:\\Dev\\Qt5.10.0-static\\Docs\\Qt-5.10.0\\qtscxml\\qtscxml.index: The system cannot find the path specified."
[33mWARN[0m[0282] parser.LoadModule                             [33merror[0m=EOF [33mmodule[0m=Scxml
[31mERRO[0m[0282] failed to load D:\Dev\Qt5.10.0-static\Docs\Qt-5.10.0\qtquickcontrols2\qtquickcontrols2.index  [31merror[0m="open D:\\Dev\\Qt5.10.0-static\\Docs\\Qt-5.10.0\\qtquickcontrols2\\qtquickcontrols2.index: The system cannot find the path specified."
[33mWARN[0m[0282] parser.LoadModule                             [33merror[0m=EOF [33mmodule[0m=QuickControls2
[31mERRO[0m[0282] failed to load D:\Dev\Qt5.10.0-static\Docs\Qt-5.10.0\qtsql\qtsql.index  [31merror[0m="open D:\\Dev\\Qt5.10.0-static\\Docs\\Qt-5.10.0\\qtsql\\qtsql.index: The system cannot find the path specified."
[33mWARN[0m[0282] parser.LoadModule                             [33merror[0m=EOF [33mmodule[0m=Sql
[31mERRO[0m[0282] failed to load D:\Dev\Qt5.10.0-static\Docs\Qt-5.10.0\qtqml\qtqml.index  [31merror[0m="open D:\\Dev\\Qt5.10.0-static\\Docs\\Qt-5.10.0\\qtqml\\qtqml.index: The system cannot find the path specified."
[33mWARN[0m[0282] parser.LoadModule                             [33merror[0m=EOF [33mmodule[0m=Qml
[31mERRO[0m[0282] failed to load D:\Dev\Qt5.10.0-static\Docs\Qt-5.10.0\qtscript\qtscript.index  [31merror[0m="open D:\\Dev\\Qt5.10.0-static\\Docs\\Qt-5.10.0\\qtscript\\qtscript.index: The system cannot find the path specified."
[33mWARN[0m[0282] parser.LoadModule                             [33merror[0m=EOF [33mmodule[0m=Script
[31mERRO[0m[0282] failed to load D:\Dev\Qt5.10.0-static\Docs\Qt-5.10.0\qtsensors\qtsensors.index  [31merror[0m="open D:\\Dev\\Qt5.10.0-static\\Docs\\Qt-5.10.0\\qtsensors\\qtsensors.index: The system cannot find the path specified."
[33mWARN[0m[0282] parser.LoadModule                             [33merror[0m=EOF [33mmodule[0m=Sensors
[31mERRO[0m[0282] failed to load D:\Dev\Qt5.10.0-static\Docs\Qt-5.10.0\qtsvg\qtsvg.index  [31merror[0m="open D:\\Dev\\Qt5.10.0-static\\Docs\\Qt-5.10.0\\qtsvg\\qtsvg.index: The system cannot find the path specified."
[33mWARN[0m[0282] parser.LoadModule                             [33merror[0m=EOF [33mmodule[0m=Svg
[31mERRO[0m[0282] failed to load D:\Dev\Qt5.10.0-static\Docs\Qt-5.10.0\qtgui\qtgui.index  [31merror[0m="open D:\\Dev\\Qt5.10.0-static\\Docs\\Qt-5.10.0\\qtgui\\qtgui.index: The system cannot find the path specified."
[31mERRO[0m[0282] failed to load D:\Dev\Qt5.10.0-static\Docs\Qt-5.10.0\qtremoteobjects\qtremoteobjects.index  [31merror[0m="open D:\\Dev\\Qt5.10.0-static\\Docs\\Qt-5.10.0\\qtremoteobjects\\qtremoteobjects.index: The system cannot find the path specified."
[31mERRO[0m[0282] failed to load D:\Dev\Qt5.10.0-static\Docs\Qt-5.10.0\qtpositioning\qtpositioning.index  [31merror[0m="open D:\\Dev\\Qt5.10.0-static\\Docs\\Qt-5.10.0\\qtpositioning\\qtpositioning.index: The system cannot find the path specified."
[31mERRO[0m[0282] failed to load D:\Dev\Qt5.10.0-static\Docs\Qt-5.10.0\qtmultimedia\qtmultimedia.index  [31merror[0m="open D:\\Dev\\Qt5.10.0-static\\Docs\\Qt-5.10.0\\qtmultimedia\\qtmultimedia.index: The system cannot find the path specified."
[33mWARN[0m[0282] parser.LoadModule                             [33merror[0m=EOF [33mmodule[0m=Multimedia
[31mERRO[0m[0282] failed to load D:\Dev\Qt5.10.0-static\Docs\Qt-5.10.0\qtwebsockets\qtwebsockets.index  [31merror[0m="open D:\\Dev\\Qt5.10.0-static\\Docs\\Qt-5.10.0\\qtwebsockets\\qtwebsockets.index: The system cannot find the path specified."
[31mERRO[0m[0282] failed to load D:\Dev\Qt5.10.0-static\Docs\Qt-5.10.0\qtxml\qtxml.index  [31merror[0m="open D:\\Dev\\Qt5.10.0-static\\Docs\\Qt-5.10.0\\qtxml\\qtxml.index: The system cannot find the path specified."
[31mERRO[0m[0282] failed to load D:\Dev\Qt5.10.0-static\Docs\Qt-5.10.0\qtandroidextras\qtandroidextras.index  [31merror[0m="open D:\\Dev\\Qt5.10.0-static\\Docs\\Qt-5.10.0\\qtandroidextras\\qtandroidextras.index: The system cannot find the path specified."
[31mERRO[0m[0282] failed to load D:\Dev\Qt5.10.0-static\Docs\Qt-5.10.0\qtgamepad\qtgamepad.index  [31merror[0m="open D:\\Dev\\Qt5.10.0-static\\Docs\\Qt-5.10.0\\qtgamepad\\qtgamepad.index: The system cannot find the path specified."
[31mERRO[0m[0282] failed to load D:\Dev\Qt5.10.0-static\Docs\Qt-5.10.0\qtuitools\qtuitools.index  [31merror[0m="open D:\\Dev\\Qt5.10.0-static\\Docs\\Qt-5.10.0\\qtuitools\\qtuitools.index: The system cannot find the path specified."
[31mERRO[0m[0282] failed to load D:\Dev\Qt5.10.0-static\Docs\Qt-5.10.0\qtcharts\qtcharts.index  [31merror[0m="open D:\\Dev\\Qt5.10.0-static\\Docs\\Qt-5.10.0\\qtcharts\\qtcharts.index: The system cannot find the path specified."
[31mERRO[0m[0282] failed to load D:\Dev\Qt5.10.0-static\Docs\Qt-5.10.0\qtdbus\qtdbus.index  [31merror[0m="open D:\\Dev\\Qt5.10.0-static\\Docs\\Qt-5.10.0\\qtdbus\\qtdbus.index: The system cannot find the path specified."
[31mERRO[0m[0282] failed to load D:\Dev\Qt5.10.0-static\Docs\Qt-5.10.0\qtwinextras\qtwinextras.index  [31merror[0m="open D:\\Dev\\Qt5.10.0-static\\Docs\\Qt-5.10.0\\qtwinextras\\qtwinextras.index: The system cannot find the path specified."
[31mERRO[0m[0282] failed to load D:\Dev\Qt5.10.0-static\Docs\Qt-5.10.0\qtpurchasing\qtpurchasing.index  [31merror[0m="open D:\\Dev\\Qt5.10.0-static\\Docs\\Qt-5.10.0\\qtpurchasing\\qtpurchasing.index: The system cannot find the path specified."
[31mERRO[0m[0282] failed to load D:\Dev\Qt5.10.0-static\Docs\Qt-5.10.0\qtserialbus\qtserialbus.index  [31merror[0m="open D:\\Dev\\Qt5.10.0-static\\Docs\\Qt-5.10.0\\qtserialbus\\qtserialbus.index: The system cannot find the path specified."
[31mERRO[0m[0282] failed to load D:\Dev\Qt5.10.0-static\Docs\Qt-5.10.0\qtdatavisualization\qtdatavisualization.index  [31merror[0m="open D:\\Dev\\Qt5.10.0-static\\Docs\\Qt-5.10.0\\qtdatavisualization\\qtdatavisualization.index: The system cannot find the path specified."
[31mERRO[0m[0282] failed to load D:\Dev\Qt5.10.0-static\Docs\Qt-5.10.0\qtprintsupport\qtprintsupport.index  [31merror[0m="open D:\\Dev\\Qt5.10.0-static\\Docs\\Qt-5.10.0\\qtprintsupport\\qtprintsupport.index: The system cannot find the path specified."
[31mERRO[0m[0282] failed to load D:\Dev\Qt5.10.0-static\Docs\Qt-5.10.0\qtwidgets\qtwidgets.index  [31merror[0m="open D:\\Dev\\Qt5.10.0-static\\Docs\\Qt-5.10.0\\qtwidgets\\qtwidgets.index: The system cannot find the path specified."
[31mERRO[0m[0282] failed to load D:\Dev\Qt5.10.0-static\Docs\Qt-5.10.0\qtdesigner\qtdesigner.index  [31merror[0m="open D:\\Dev\\Qt5.10.0-static\\Docs\\Qt-5.10.0\\qtdesigner\\qtdesigner.index: The system cannot find the path specified."
[31mERRO[0m[0282] failed to load D:\Dev\Qt5.10.0-static\Docs\Qt-5.10.0\qtnfc\qtnfc.index  [31merror[0m="open D:\\Dev\\Qt5.10.0-static\\Docs\\Qt-5.10.0\\qtnfc\\qtnfc.index: The system cannot find the path specified."
[31mERRO[0m[0282] failed to load D:\Dev\Qt5.10.0-static\Docs\Qt-5.10.0\qtserialport\qtserialport.index  [31merror[0m="open D:\\Dev\\Qt5.10.0-static\\Docs\\Qt-5.10.0\\qtserialport\\qtserialport.index: The system cannot find the path specified."
[31mERRO[0m[0282] failed to load D:\Dev\Qt5.10.0-static\Docs\Qt-5.10.0\qtwebchannel\qtwebchannel.index  [31merror[0m="open D:\\Dev\\Qt5.10.0-static\\Docs\\Qt-5.10.0\\qtwebchannel\\qtwebchannel.index: The system cannot find the path specified."
[31mERRO[0m[0282] failed to load D:\Dev\Qt5.10.0-static\Docs\Qt-5.10.0\qtxmlpatterns\qtxmlpatterns.index  [31merror[0m="open D:\\Dev\\Qt5.10.0-static\\Docs\\Qt-5.10.0\\qtxmlpatterns\\qtxmlpatterns.index: The system cannot find the path specified."
[31mERRO[0m[0282] failed to load D:\Dev\Qt5.10.0-static\Docs\Qt-5.10.0\qtbluetooth\qtbluetooth.index  [31merror[0m="open D:\\Dev\\Qt5.10.0-static\\Docs\\Qt-5.10.0\\qtbluetooth\\qtbluetooth.index: The system cannot find the path specified."
[31mERRO[0m[0282] failed to load D:\Dev\Qt5.10.0-static\Docs\Qt-5.10.0\qtlocation\qtlocation.index  [31merror[0m="open D:\\Dev\\Qt5.10.0-static\\Docs\\Qt-5.10.0\\qtlocation\\qtlocation.index: The system cannot find the path specified."
[33mWARN[0m[0282] parser.LoadModule                             [33merror[0m=EOF [33mmodule[0m=Location
[33mWARN[0m[0282] parser.LoadModule                             [33merror[0m=EOF [33mmodule[0m=RemoteObjects
[31mERRO[0m[0282] failed to load D:\Dev\Qt5.10.0-static\Docs\Qt-5.10.0\qtquick\qtquick.index  [31merror[0m="open D:\\Dev\\Qt5.10.0-static\\Docs\\Qt-5.10.0\\qtquick\\qtquick.index: The system cannot find the path specified."
[31mERRO[0m[0282] failed to load D:\Dev\Qt5.10.0-static\Docs\Qt-5.10.0\qtscripttools\qtscripttools.index  [31merror[0m="open D:\\Dev\\Qt5.10.0-static\\Docs\\Qt-5.10.0\\qtscripttools\\qtscripttools.index: The system cannot find the path specified."
[33mWARN[0m[0282] parser.LoadModule                             [33merror[0m=EOF [33mmodule[0m=ScriptTools
[33mWARN[0m[0282] parser.LoadModule                             [33merror[0m=EOF [33mmodule[0m=Positioning
[33mWARN[0m[0282] parser.LoadModule                             [33merror[0m=EOF [33mmodule[0m=Xml
[33mWARN[0m[0282] parser.LoadModule                             [33merror[0m=EOF [33mmodule[0m=Gui
[33mWARN[0m[0282] parser.LoadModule                             [33merror[0m=EOF [33mmodule[0m=Gamepad
[31mERRO[0m[0282] failed to load D:\Dev\Qt5.10.0-static\Docs\Qt-5.10.0\qtcore\qtcore.index  [31merror[0m="open D:\\Dev\\Qt5.10.0-static\\Docs\\Qt-5.10.0\\qtcore\\qtcore.index: The system cannot find the path specified."
[31mERRO[0m[0282] failed to load D:\Dev\Qt5.10.0-static\Docs\Qt-5.10.0\qttestlib\qttestlib.index  [31merror[0m="open D:\\Dev\\Qt5.10.0-static\\Docs\\Qt-5.10.0\\qttestlib\\qttestlib.index: The system cannot find the path specified."
[33mWARN[0m[0282] parser.LoadModule                             [33merror[0m=EOF [33mmodule[0m=AndroidExtras
[33mWARN[0m[0282] parser.LoadModule                             [33merror[0m=EOF [33mmodule[0m=UiTools
[33mWARN[0m[0282] parser.LoadModule                             [33merror[0m=EOF [33mmodule[0m=DBus
[33mWARN[0m[0282] parser.LoadModule                             [33merror[0m=EOF [33mmodule[0m=WinExtras
[33mWARN[0m[0282] parser.LoadModule                             [33merror[0m=EOF [33mmodule[0m=SerialBus
[33mWARN[0m[0282] parser.LoadModule                             [33merror[0m=EOF [33mmodule[0m=Purchasing
[33mWARN[0m[0282] parser.LoadModule                             [33merror[0m=EOF [33mmodule[0m=PrintSupport
[33mWARN[0m[0282] parser.LoadModule                             [33merror[0m=EOF [33mmodule[0m=Widgets
[33mWARN[0m[0282] parser.LoadModule                             [33merror[0m=EOF [33mmodule[0m=Designer
[33mWARN[0m[0282] parser.LoadModule                             [33merror[0m=EOF [33mmodule[0m=Nfc
[33mWARN[0m[0282] parser.LoadModule                             [33merror[0m=EOF [33mmodule[0m=SerialPort
[33mWARN[0m[0282] parser.LoadModule                             [33merror[0m=EOF [33mmodule[0m=WebChannel
[33mWARN[0m[0282] parser.LoadModule                             [33merror[0m=EOF [33mmodule[0m=XmlPatterns
[33mWARN[0m[0282] parser.LoadModule                             [33merror[0m=EOF [33mmodule[0m=Bluetooth
[33mWARN[0m[0282] parser.LoadModule                             [33merror[0m=EOF [33mmodule[0m=Quick
[33mWARN[0m[0282] parser.LoadModule                             [33merror[0m=EOF [33mmodule[0m=WebSockets
[33mWARN[0m[0282] parser.LoadModule                             [33merror[0m=EOF [33mmodule[0m=TestLib
[33mWARN[0m[0282] parser.LoadModule                             [33merror[0m=EOF [33mmodule[0m=Core
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x1 addr=0x110 pc=0x6efe23]

goroutine 1 [running]:
github.com/therecipe/qt/internal/cmd/minimal.Minimal(0xc0424061e0, 0x54, 0x809374, 0x7, 0x0, 0x0)
        J:/Code/GOPATH/src/github.com/therecipe/qt/internal/cmd/minimal/minimal.go:150 +0xad3
github.com/therecipe/qt/internal/cmd/deploy.Deploy(0x807ce4, 0x4, 0x809374, 0x7, 0xc0424061e0, 0x54, 0xc04201a500, 0x0, 0x0, 0x0, ...)
        J:/Code/GOPATH/src/github.com/therecipe/qt/internal/cmd/deploy/deploy.go:61 +0xe29
github.com/therecipe/qt/internal/cmd/setup.Test(0x809374, 0x7, 0x800000, 0x0, 0x0)
        J:/Code/GOPATH/src/github.com/therecipe/qt/internal/cmd/setup/test.go:148 +0x72c
main.main()
        J:/Code/GOPATH/src/github.com/therecipe/qt/cmd/qtsetup/main.go:99 +0x336

**Comment by therecipe** [comment]
Ah, sorry for the mix up.
For a plain normal mingw version the process should be pretty straightforward.

You probably just need to do:
- set QT_DIR=path/to/the/initial/root/Qt/dir (the folder containing: `5.10.0`, `dist`, `Docs`, `Examples`, ...)
- set QT_QMAKE_DIR=D:\Dev\Qt5.10.0-static\bin
- set QT_VERSION=5.10.0
- qtsetup

`QT_DIR` needs to be set to the root folder otherwise the generator can't find the `*.index` files at the place it expects them to be.
And then you will get something like this:
>�[31mERRO�[0m[0282] failed to load D:\Dev\Qt5.10.0-static\Docs\Qt-5.10.0\qtcore\qtcore.index 



If this won't work, then maybe try to symlink the `D:\Dev\Qt5.10.0-static` as `mingw53_32` in `path/to/the/initial/root/Qt/dir/5.10.0/` instead and unset `QT_QMAKE_DIR`

**Comment by ismlsmile** [comment]
I tried these two methods, they report the same error:
github.com/therecipe/qt/core
# github.com/therecipe/qt/core
core.cpp:9:30: fatal error: QAbstractAnimation: No such file or directory
compilation terminated.

**Comment by therecipe** [comment]
>I tried these two methods, they report the same error:
core.cpp:9:30: fatal error: QAbstractAnimation: No such file or directory
compilation terminated.

Mh, did you get any errors while running `qtsetup` ?
This error usually comes up, if the setup failed to generate proper `cgo_*` files.
(If you take a look into the `$GOPATH/src/github.com/therecipe/qt/core/cgo_*` file, it should be probably pretty empty.
