### ISSUE TITLE
Panic when using QtCharts

### ISSUE THREAD

**Issue by arknable** [therecipe/qt#601]
Hi,

I'm using latest version of the binding but it crashes loading qml that uses `QtCharts`, 
[sample project](https://github.com/therecipe/qt/files/1931135/therecipe-issue.zip) attached.

Thanks.

**Comment by arknable** [comment]
sorry, this is the panic messages

```
arknables-MacBook-Pro:therecipe-issue arknable$ ./app
fatal error: unexpected signal during runtime execution
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x6357899]

runtime stack:
runtime.throw(0x46148cf, 0x2a)
	/usr/local/Cellar/go@1.9/1.9.5/libexec/src/runtime/panic.go:605 +0x95
runtime.sigpanic()
	/usr/local/Cellar/go@1.9/1.9.5/libexec/src/runtime/signal_unix.go:351 +0x2b8

goroutine 1 [syscall, locked to thread]:
runtime.cgocall(0x4497000, 0xc420051ed8, 0x40ed130)
	/usr/local/Cellar/go@1.9/1.9.5/libexec/src/runtime/cgocall.go:132 +0xe4 fp=0xc420051ea8 sp=0xc420051e68 pc=0x4022da4
github.com/therecipe/qt/qml._Cfunc_QQmlApplicationEngine_Load(0x8915a20, 0x89738f0)
	github.com/therecipe/qt/qml/_obj/_cgo_gotypes.go:1496 +0x41 fp=0xc420051ed8 sp=0xc420051ea8 pc=0x41e8871
github.com/therecipe/qt/qml.(*QQmlApplicationEngine).Load.func1(0x8915a20, 0x89738f0)
	/Users/arknable/Documents/Cats/src/github.com/therecipe/qt/qml/qml.go:1261 +0xa3 fp=0xc420051f10 sp=0xc420051ed8 pc=0x42005f3
github.com/therecipe/qt/qml.(*QQmlApplicationEngine).Load(0xc42000e050, 0x48e2d80, 0xc42000e060)
	/Users/arknable/Documents/Cats/src/github.com/therecipe/qt/qml/qml.go:1261 +0x7c fp=0xc420051f40 sp=0xc420051f10 pc=0x41f302c
main.main()
	/Users/arknable/Downloads/therecipe-issue/application.go:14 +0xbb fp=0xc420051f80 sp=0xc420051f40 pc=0x42041cb
runtime.main()
	/usr/local/Cellar/go@1.9/1.9.5/libexec/src/runtime/proc.go:195 +0x226 fp=0xc420051fe0 sp=0xc420051f80 pc=0x404ac96
runtime.goexit()
	/usr/local/Cellar/go@1.9/1.9.5/libexec/src/runtime/asm_amd64.s:2337 +0x1 fp=0xc420051fe8 sp=0xc420051fe0 pc=0x40730e1
```

**Comment by arknable** [comment]
ah sorry I think this is false alarm, I should use `QApplication` on the sample then `QGuiApplication`. let me confirm first with latest binding again, I reverted to old version.

**Comment by arknable** [comment]
ok, confirmed, this is false alarm. sorry.
