### ISSUE TITLE
Install qt/gui always out of memory

### ISSUE THREAD

**Issue by arknable** [therecipe/qt#603]
Hi,
Somehow everytime I run `qtsetup install` I always got out of memory error when `qtsetup` trying to install `qt/gui` module. That being said, it always looks stucked first, then if I press ctrl+C then I can see the error and it continues to install other module

```
[36mINFO[0m[0018] installing full qt/gui
[31mERRO[0m[0663] failed to run command                         [31mcmd[0m="go install -p 4 -v github.com/therecipe/qt/gui" [31menv[0m="CGO_ENABLED=1 PATH=C:\\Dev\\Tools\\Qt\\Tools\\mingw530_32\\bin;C:\\Windows\\system32;C:\\Windows;C:\\Windows\\System32\\Wbem;C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\;C:\\Program Files (x86)\\Git\\cmd;C:\\Program Files\\TortoiseGit\\bin;C:\\Dev\\Tools\\Go\\bin;C:\\Users\\arknable\\AppData\\Local\\Microsoft\\WindowsApps;C:\\Dev\\Tools\\InfluxDB;C:\\Dev\\Tools\\Qt\\Tools\\mingw530_32\\bin;C:\\Dev\\Cats\\bin;C:\\Program Files\\Microsoft VS Code\\bin GOPATH=C:\\Dev\\Cats;C:\\Dev\\Cats\\src\\git.robotinfra.tools\\wl\\godeps TEMP=C:\\Users\\arknable\\AppData\\Local\\Temp CGO_CFLAGS_ALLOW=.* CGO_CXXFLAGS_ALLOW=.* GOOS=windows GOROOT=C:\\Dev\\Tools\\Go TMP=C:\\Users\\arknable\\AppData\\Local\\Temp CGO_LDFLAGS_ALLOW=.* GOARCH=386" [31merror[0m="exit status 2" [31mfunc[0m=RunCmdOptionalError [31mname[0m="install gui"
github.com/therecipe/qt/gui
# github.com/therecipe/qt/gui
runtime: out of memory: cannot allocate 1572864-byte block (1773740032 in use)
fatal error: out of memory

runtime stack:
runtime.throw(0xa72b9a, 0xd)
        c:/go/src/runtime/panic.go:605 +0x7c
runtime.largeAlloc(0x179def, 0x440100, 0x13fd8004)
        c:/go/src/runtime/malloc.go:829 +0xe0
runtime.mallocgc.func1()
        c:/go/src/runtime/malloc.go:722 +0x39
runtime.systemstack(0x13ba6a80)
        c:/go/src/runtime/asm_386.s:393 +0x5e
runtime.mstart()
        c:/go/src/runtime/proc.go:1135

goroutine 5 [running]:
runtime.systemstack_switch()
        c:/go/src/runtime/asm_386.s:347 fp=0x13bbdc2c sp=0x13bbdc28 pc=0x44c6e0
runtime.mallocgc(0x179def, 0x0, 0x3bec8c00, 0x3)
        c:/go/src/runtime/malloc.go:721 +0x67e fp=0x13bbdc80 sp=0x13bbdc2c pc=0x40e79e
runtime.rawstring(0x179def, 0x0, 0x0, 0x0, 0x0, 0x0)
        c:/go/src/runtime/string.go:245 +0x56 fp=0x13bbdc94 sp=0x13bbdc80 pc=0x43c946
runtime.rawstringtmp(0x0, 0x179def, 0x449ea0, 0x13bb4240, 0x3bec8cb9, 0x2f619a88, 0x4101f5)
        c:/go/src/runtime/string.go:115 +0x51 fp=0x13bbdcb0 sp=0x13bbdc94 pc=0x43c491
runtime.concatstrings(0x0, 0x13bbdd18, 0x2, 0x2, 0x13bd00c0, 0x179d90)
        c:/go/src/runtime/string.go:46 +0xc8 fp=0x13bbdcf8 sp=0x13bbdcb0 pc=0x43c0e8
runtime.concatstring2(0x0, 0x7fb60000, 0x179d90, 0x33aa09c0, 0x5f, 0x33aa09c0, 0x5f)
        c:/go/src/runtime/string.go:55 +0x39 fp=0x13bbdd14 sp=0x13bbdcf8 pc=0x43c259
cmd/compile/internal/gc.(*noder).pragma(0x13d87340, 0x13db4000, 0x4420d03, 0x26c64bd0, 0x61, 0x13bbde38)
        c:/go/src/cmd/compile/internal/gc/noder.go:1193 +0x8c0 fp=0x13bbddec sp=0x13bbdd14 pc=0x912ac0
cmd/compile/internal/gc.(*noder).(cmd/compile/internal/gc.pragma)-fm(0x13db4000, 0x4420d03, 0x26c64bd0, 0x61, 0x0)
        c:/go/src/cmd/compile/internal/gc/noder.go:44 +0x40 fp=0x13bbde08 sp=0x13bbddec pc=0x9c1a60
cmd/compile/internal/syntax.(*parser).init.func2(0x4420d, 0x3, 0x26c64bd0, 0x61)
        c:/go/src/cmd/compile/internal/syntax/parser.go:54 +0xc9 fp=0x13bbde2c sp=0x13bbde08 pc=0x4f38b9
cmd/compile/internal/syntax.(*scanner).lineComment(0x13dd7310)
        c:/go/src/cmd/compile/internal/syntax/scanner.go:608 +0x266 fp=0x13bbde9c sp=0x13bbde2c pc=0x4f2426
cmd/compile/internal/syntax.(*scanner).next(0x13dd7310)
        c:/go/src/cmd/compile/internal/syntax/scanner.go:184 +0x796 fp=0x13bbded0 sp=0x13bbde9c pc=0x4f0b96
cmd/compile/internal/syntax.(*parser).got(0x13dd7300, 0x12, 0xd301)
        c:/go/src/cmd/compile/internal/syntax/parser.go:90 +0x34 fp=0x13bbded8 sp=0x13bbded0 pc=0x4dea04
cmd/compile/internal/syntax.(*parser).fileOrNil(0x13dd7300, 0x13db4000)
        c:/go/src/cmd/compile/internal/syntax/parser.go:314 +0x30a fp=0x13bbdf50 sp=0x13bbded8 pc=0x4df69a
cmd/compile/internal/syntax.Parse(0x13db4000, 0xd41ce0, 0x13dcc020, 0x13dcc028, 0x13dcc030, 0xa8b408, 0x1, 0x0, 0x0, 0x0)
        c:/go/src/cmd/compile/internal/syntax/syntax.go:80 +0xc8 fp=0x13bbdf78 sp=0x13bbdf50 pc=0x4f31b8
cmd/compile/internal/gc.parseFiles.func1(0x13b9e500, 0x13d87340, 0x13be8000, 0x67)
        c:/go/src/cmd/compile/internal/gc/noder.go:44 +0x24c fp=0x13bbdfe0 sp=0x13bbdf78 pc=0x9b90fc
runtime.goexit()
        c:/go/src/runtime/asm_386.s:1635 +0x1 fp=0x13bbdfe4 sp=0x13bbdfe0 pc=0x44e311
created by cmd/compile/internal/gc.parseFiles
        c:/go/src/cmd/compile/internal/gc/noder.go:31 +0xa9

goroutine 1 [chan receive]:
cmd/compile/internal/gc.parseFiles(0x13be6090, 0x4, 0xe, 0x2)
        c:/go/src/cmd/compile/internal/gc/noder.go:49 +0x2c1
cmd/compile/internal/gc.Main(0xa8b664)
        c:/go/src/cmd/compile/internal/gc/main.go:428 +0x17a9
main.main()
        c:/go/src/cmd/compile/main.go:49 +0x7e

[36mINFO[0m[1644] installing full qt/network
```

I'm using Windows 10 with 8GB RAM and Qt 5.9.4 + mingw 5.3-32 bit. I'm pretty sure it's because I only have 8 GB RAM.

Thanks.

**Comment by hick** [comment]
I got something like this ,  even using Administrator priviledge, and tried serveral times,   when qtsetup  try to installing qt/widgets

![image](https://user-images.githubusercontent.com/38886/56453979-abbe9800-637c-11e9-8dfe-00ca89da7051.png)

**Comment by hick** [comment]
time="2019-04-20T13:57:02+08:00" level=info msg="installing full qt/dbus "
time="2019-04-20T13:57:05+08:00" level=info msg="installing full qt/nfc "
time="2019-04-20T13:57:07+08:00" level=info msg="installing full qt/script "
time="2019-04-20T13:57:10+08:00" level=info msg="installing full qt/sensors "
time="2019-04-20T13:57:13+08:00" level=info msg="installing full qt/positioning
"
time="2019-04-20T13:57:16+08:00" level=info msg="installing full qt/widgets "
github.com/therecipe/qt/widgets
# github.com/therecipe/qt/widgets
runtime: out of memory: cannot allocate 401408-byte block (1681555456 in use)
fatal error: out of memory

runtime stack:
runtime.throw(0xbe2a8d, 0xd)
        c:/go/src/runtime/panic.go:608 +0x64
runtime.largeAlloc(0x60bc8, 0x13810101, 0x44bc20)
        c:/go/src/runtime/malloc.go:1021 +0x107
runtime.mallocgc.func1()
        c:/go/src/runtime/malloc.go:914 +0x39
runtime.systemstack(0x0)
        c:/go/src/runtime/asm_386.s:396 +0x53
runtime.mstart()
        c:/go/src/runtime/proc.go:1229

goroutine 5 [running]:
runtime.systemstack_switch()
        c:/go/src/runtime/asm_386.s:357 fp=0x37822b98 sp=0x37822b94 pc=0x44d2e0
runtime.mallocgc(0x60bc8, 0xb8f320, 0x479ef901, 0x479ef960)
        c:/go/src/runtime/malloc.go:913 +0x676 fp=0x37822bec sp=0x37822b98 pc=0x
409cb6
runtime.makeslice(0xb8f320, 0x182f2, 0x182f2, 0x479ef998, 0x143d7d08, 0x143d7ce4
)
        c:/go/src/runtime/slice.go:70 +0x59 fp=0x37822c00 sp=0x37822bec pc=0x439
409
cmd/compile/internal/ssa.newSparseMap(...)
        c:/go/src/cmd/compile/internal/ssa/sparsemap.go:26
cmd/compile/internal/ssa.newBiasedSparseMap(...)
        c:/go/src/cmd/compile/internal/ssa/biasedsparsemap.go:27
cmd/compile/internal/ssa.numberLines(0x16a046e0)
        c:/go/src/cmd/compile/internal/ssa/numberlines.go:171 +0x6e6 fp=0x37822d
2c sp=0x37822c00 pc=0x5d5086
cmd/compile/internal/ssa.Compile(0x16a046e0)
        c:/go/src/cmd/compile/internal/ssa/compile.go:70 +0x26c fp=0x37825f04 sp
=0x37822d2c pc=0x5a896c
cmd/compile/internal/gc.buildssa(0x1ce9e300, 0x0, 0x0)
        c:/go/src/cmd/compile/internal/gc/ssa.go:211 +0x8ca fp=0x37825f98 sp=0x3
7825f04 pc=0xaa6f4a
cmd/compile/internal/gc.compileSSA(0x1ce9e300, 0x0)
        c:/go/src/cmd/compile/internal/gc/pgen.go:259 +0x2d fp=0x37825fcc sp=0x3
7825f98 pc=0xa7ba5d
cmd/compile/internal/gc.compileFunctions.func2(0x2c1f68c0, 0x1883af40, 0x0)
        c:/go/src/cmd/compile/internal/gc/pgen.go:323 +0x3b fp=0x37825fe0 sp=0x3
7825fcc pc=0xb17bbb
runtime.goexit()
        c:/go/src/runtime/asm_386.s:1324 +0x1 fp=0x37825fe4 sp=0x37825fe0 pc=0x4
4eb11
created by cmd/compile/internal/gc.compileFunctions
        c:/go/src/cmd/compile/internal/gc/pgen.go:321 +0xee

goroutine 1 [chan send]:
cmd/compile/internal/gc.compileFunctions()
        c:/go/src/cmd/compile/internal/gc/pgen.go:329 +0x136
cmd/compile/internal/gc.Main(0xbfe770)
        c:/go/src/cmd/compile/internal/gc/main.go:651 +0x2381
main.main()
        c:/go/src/cmd/compile/main.go:51 +0x7e

goroutine 6 [runnable]:
cmd/compile/internal/ssa.(*sortvalues).Less(0x22ffad40, 0x21, 0x20, 0x14330101)
        <autogenerated>:1 +0x6c
sort.insertionSort(0xd326b0, 0x22ffad40, 0x1c, 0x23)
        c:/go/src/sort/sort.go:27 +0x88
sort.quickSort(0xd326b0, 0x22ffad40, 0x1c, 0x23, 0xa)
        c:/go/src/sort/sort.go:209 +0x196
sort.quickSort(0xd326b0, 0x22ffad40, 0x0, 0x23, 0xa)
        c:/go/src/sort/sort.go:197 +0xf2
sort.Sort(0xd326b0, 0x22ffad40)
        c:/go/src/sort/sort.go:218 +0x61
cmd/compile/internal/ssa.partitionValues(0x5a447a40, 0x27, 0x75, 0x143301e0, 0x0
, 0x75, 0x2f46ebe0)
        c:/go/src/cmd/compile/internal/ssa/cse.go:287 +0x83
cmd/compile/internal/ssa.cse(0x5d517d90)
        c:/go/src/cmd/compile/internal/ssa/cse.go:49 +0x2d8
cmd/compile/internal/ssa.Compile(0x5d517d90)
        c:/go/src/cmd/compile/internal/ssa/compile.go:70 +0x26c
cmd/compile/internal/gc.buildssa(0x1cf66a80, 0x1, 0x0)
        c:/go/src/cmd/compile/internal/gc/ssa.go:211 +0x8ca
cmd/compile/internal/gc.compileSSA(0x1cf66a80, 0x1)
        c:/go/src/cmd/compile/internal/gc/pgen.go:259 +0x2d
cmd/compile/internal/gc.compileFunctions.func2(0x2c1f68c0, 0x1883af40, 0x1)
        c:/go/src/cmd/compile/internal/gc/pgen.go:323 +0x3b
created by cmd/compile/internal/gc.compileFunctions
        c:/go/src/cmd/compile/internal/gc/pgen.go:321 +0xee

time="2019-04-20T14:23:25+08:00" level=info msg="installing full qt/sql "
github.com/therecipe/qt/widgets
# github.com/therecipe/qt/widgets
runtime: out of memory: cannot allocate 221184-byte block (1681555456 in use)
fatal error: out of memory

runtime stack:
runtime.throw(0xbe2a8d, 0xd)
        c:/go/src/runtime/panic.go:608 +0x64
runtime.largeAlloc(0x34aa0, 0x13810101, 0x44bc20)
        c:/go/src/runtime/malloc.go:1021 +0x107
runtime.mallocgc.func1()
        c:/go/src/runtime/malloc.go:914 +0x39
runtime.systemstack(0x0)
        c:/go/src/runtime/asm_386.s:396 +0x53
runtime.mstart()
        c:/go/src/runtime/proc.go:1229

goroutine 7 [running]:
runtime.systemstack_switch()
        c:/go/src/runtime/asm_386.s:357 fp=0x3995eb98 sp=0x3995eb94 pc=0x44d2e0
runtime.mallocgc(0x34aa0, 0xb8f320, 0x7ebf4201, 0x7ebf4298)
        c:/go/src/runtime/malloc.go:913 +0x676 fp=0x3995ebec sp=0x3995eb98 pc=0x
409cb6
runtime.makeslice(0xb8f320, 0xd2a8, 0xd2a8, 0x7ebf42e8, 0x307ee028, 0x307edcc4)
        c:/go/src/runtime/slice.go:70 +0x59 fp=0x3995ec00 sp=0x3995ebec pc=0x439
409
cmd/compile/internal/ssa.newSparseMap(...)
        c:/go/src/cmd/compile/internal/ssa/sparsemap.go:26
cmd/compile/internal/ssa.newBiasedSparseMap(...)
        c:/go/src/cmd/compile/internal/ssa/biasedsparsemap.go:27
cmd/compile/internal/ssa.numberLines(0x7eb6c630)
        c:/go/src/cmd/compile/internal/ssa/numberlines.go:171 +0x6e6 fp=0x3995ed
2c sp=0x3995ec00 pc=0x5d5086
cmd/compile/internal/ssa.Compile(0x7eb6c630)
        c:/go/src/cmd/compile/internal/ssa/compile.go:70 +0x26c fp=0x39961f04 sp
=0x3995ed2c pc=0x5a896c
cmd/compile/internal/gc.buildssa(0x1b6a4480, 0x1, 0x0)
        c:/go/src/cmd/compile/internal/gc/ssa.go:211 +0x8ca fp=0x39961f98 sp=0x3
9961f04 pc=0xaa6f4a
cmd/compile/internal/gc.compileSSA(0x1b6a4480, 0x1)
        c:/go/src/cmd/compile/internal/gc/pgen.go:259 +0x2d fp=0x39961fcc sp=0x3
9961f98 pc=0xa7ba5d
cmd/compile/internal/gc.compileFunctions.func2(0x1f989d00, 0x13fbe890, 0x1)
        c:/go/src/cmd/compile/internal/gc/pgen.go:323 +0x3b fp=0x39961fe0 sp=0x3
9961fcc pc=0xb17bbb
runtime.goexit()
        c:/go/src/runtime/asm_386.s:1324 +0x1 fp=0x39961fe4 sp=0x39961fe0 pc=0x4
4eb11
created by cmd/compile/internal/gc.compileFunctions
        c:/go/src/cmd/compile/internal/gc/pgen.go:321 +0xee

goroutine 1 [runnable]:
cmd/compile/internal/gc.compileFunctions()
        c:/go/src/cmd/compile/internal/gc/pgen.go:329 +0x136
cmd/compile/internal/gc.Main(0xbfe770)
        c:/go/src/cmd/compile/internal/gc/main.go:651 +0x2381
main.main()
        c:/go/src/cmd/compile/main.go:51 +0x7e

goroutine 6 [running]:
        goroutine running on other thread; stack unavailable
created by cmd/compile/internal/gc.compileFunctions
        c:/go/src/cmd/compile/internal/gc/pgen.go:321 +0xee

time="2019-04-20T14:47:01+08:00" level=info msg="installing full qt/qml "
time="2019-04-20T14:47:04+08:00" level=info msg="installing full qt/websockets "

time="2019-04-20T14:47:05+08:00" level=info msg="installing full qt/xmlpatterns
"
time="2019-04-20T14:47:06+08:00" level=info msg="installing full qt/bluetooth "
time="2019-04-20T14:47:08+08:00" level=info msg="installing full qt/webchannel "

time="2019-04-20T14:47:11+08:00" level=info msg="installing full qt/svg "
