### ISSUE TITLE
QFileDialog

### ISSUE THREAD

**Issue by arpitjindal97** [therecipe/qt#625]
Please give an example of using QFileDialog

**Comment by therecipe** [comment]
Hey

Here is a very basic example: 

```go
package main

import (
	"fmt"
	"os"

	"github.com/therecipe/qt/widgets"
)

func main() {

	widgets.NewQApplication(len(os.Args), os.Args)

	//using the class
	fd := widgets.NewQFileDialog(nil, 0)
	fd.SetFileMode(widgets.QFileDialog__ExistingFiles)
	fd.ConnectFilesSelected(func(files []string) {
		fmt.Println(files)
	})
	fd.Exec()

	//using the static function
	fmt.Println(widgets.QFileDialog_GetOpenFileNames(nil, "some caption", "", "", "", 0))

	widgets.QApplication_Exec()
}
```

**Comment by PantsuDango** [comment]
> Hey
> 
> Here is a very basic example:
> 
> ```go
> package main
> 
> import (
> 	"fmt"
> 	"os"
> 
> 	"github.com/therecipe/qt/widgets"
> )
> 
> func main() {
> 
> 	widgets.NewQApplication(len(os.Args), os.Args)
> 
> 	//using the class
> 	fd := widgets.NewQFileDialog(nil, 0)
> 	fd.SetFileMode(widgets.QFileDialog__ExistingFiles)
> 	fd.ConnectFilesSelected(func(files []string) {
> 		fmt.Println(files)
> 	})
> 	fd.Exec()
> 
> 	//using the static function
> 	fmt.Println(widgets.QFileDialog_GetOpenFileNames(nil, "some caption", "", "", "", 0))
> 
> 	widgets.QApplication_Exec()
> }
> ```

the example  cannot execute：
```
goroutine 34 [running]:
reflect.Value.Convert({0x12d4720?, 0xc000222168?, 0xc00021c018?}, {0x1818008, 0x12d54e0})
        H:/app/Go/src/reflect/value.go:3257 +0x139
github.com/therecipe/qt/internal.handleCallback({0xc000094005, 0x51})
        C:/Users/admin/go/pkg/mod/github.com/therecipe/qt@v0.0.0-20200904063919-c0c124a5770d/internal/internal.go:69 +0x3f9
github.com/therecipe/qt/internal.syncCallbackHandler({0xc000094005?, 0x0?})
        C:/Users/admin/go/pkg/mod/github.com/therecipe/qt@v0.0.0-20200904063919-c0c124a5770d/internal/internal.go:113 +0x1e
created by github.com/therecipe/qt/internal.InitProcess.func3
        C:/Users/admin/go/pkg/mod/github.com/therecipe/qt@v0.0.0-20200904063919-c0c124a5770d/internal/internal.go:409 +0x1aa

进程 已完成，退出代码为 2ert: value of type []interface {} cannot be converted to type []string
```
Can you help check？
