### ISSUE TITLE
qtsetup.exe error: failed to find g++

### ISSUE THREAD

**Issue by GingerMoon** [therecipe/qt#629]
I met the error after I did the steps below according to the doc https://github.com/therecipe/qt/wiki/Installation-on-Windows 

Official Version (with Android support)
Install Go: https://golang.org/doc/install?download=go1.10.1.windows-amd64.msi
Clone the repo: go get -u -v github.com/therecipe/qt/cmd/...
Run the setup: $GOPATH/bin/qtsetup

As can see, g++ is not mentioned in the doc. Did I miss anything?
I would appreciate if you could share any insight on this. Below is my environment:
**********************
PS C:\GoWorkspace\bin> .\qtsetup.exe
[36mINFO[0m[0000] running: 'qtsetup prep'
[36mINFO[0m[0000] running: 'qtsetup check windows' [docker=false] [vagrant=false]
[31mPANI[0m[0000] failed to find g++, did you add the directory that contains g++ to your PATH?  [31merror[0m="exec: \"g++\": executable file not found in %PATH%"
panic: (*logrus.Entry) (0x7fd5a0,0xc04207a910)

goroutine 1 [running]:
github.com/sirupsen/logrus.Entry.log(0xc04207a0a0, 0xc0422b9dd0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0xc000000000, ...)
        C:/GoWorkspace/src/github.com/sirupsen/logrus/entry.go:112 +0x25b
github.com/sirupsen/logrus.(*Entry).Panic(0xc04207a8c0, 0xc04206da08, 0x1, 0x1)
        C:/GoWorkspace/src/github.com/sirupsen/logrus/entry.go:182 +0xb1
github.com/therecipe/qt/internal/cmd/setup.Check(0x809ee3, 0x7, 0x800000)
        C:/GoWorkspace/src/github.com/therecipe/qt/internal/cmd/setup/check.go:104 +0x2888
main.main()
        C:/GoWorkspace/src/github.com/therecipe/qt/cmd/qtsetup/main.go:96 +0x292
PS C:\GoWorkspace\bin> go env
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\37675\AppData\Local\go-build
set GOEXE=.exe
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOOS=windows
set GOPATH=C:\GoWorkspace
set GORACE=
set GOROOT=C:\Go
set GOTMPDIR=
set GOTOOLDIR=C:\Go\pkg\tool\windows_amd64
set GCCGO=gccgo
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=C:\Users\37675\AppData\Local\Temp\go-build112248710=/tmp/go-build -gno-record-gcc-switches
PS C:\GoWorkspace\bin> go version
go version go1.10.1 windows/amd64
**********************

**Comment by sndnvaps** [comment]
You should install qt 5.1.0 with mingw32 first,
then install github.com/therecipe/qt

**Comment by GingerMoon** [comment]
Hi sndnvaps, 
thank you for your reply. I tried to reinstall Qt with mingw32 installed.
But met some other errors like:
 failed to load ...
And I do check my file system and they don't exist on my file system.
I am using 
offline installer: https://download.qt.io/official_releases/qt/5.10/5.10.0/qt-opensource-windows-x86-5.10.0.exe mentioned in the document https://github.com/therecipe/qt/wiki/Installation-on-Windows.

Do you have any idea?


PS C:\Users\37675> cd C:\GoWorkspace\bin
PS C:\GoWorkspace\bin> .\qtsetup.exe
[36mINFO[0m[0000] running: 'qtsetup prep'
[36mINFO[0m[0000] running: 'qtsetup check windows' [docker=false] [vagrant=false]
[36mINFO[0m[0000] GOOS:                        'windows'
[36mINFO[0m[0000] GOARCH:                      'amd64'
[36mINFO[0m[0000] GOVERSION:                   'go1.10.1'
[36mINFO[0m[0000] GOROOT:                   *  'C:\Go\'
[36mINFO[0m[0000] GOPATH:                   *  'C:\GoWorkspace'
[36mINFO[0m[0000] GOBIN:                       'C:\GoWorkspace\bin'
[36mINFO[0m[0000] QT_HASH:                     '7038382d6c7bb5fd3957df56bbedf8ec4ca6b67c'
[36mINFO[0m[0000] QT_VERSION:                  '5.10.0'
[36mINFO[0m[0000] QT_VERSION_MAJOR:            '5.10.0'
[36mINFO[0m[0000] QT_DIR:                   *  'C:\Qt\Qt5.10.0'
[36mINFO[0m[0000] QT_STUB:                     'false'
[36mINFO[0m[0000] QT_DEBUG:                    'false'
[36mINFO[0m[0000] QT_QMAKE_DIR:                ''
[36mINFO[0m[0000] QT_WEBKIT:                   'false'
[36mINFO[0m[0000] QT_MSYS2:                    'false'
[36mINFO[0m[0000] running: 'qtsetup generate windows' [docker=false] [vagrant=false]
[31mERRO[0m[0000] failed to load C:\Qt\Qt5.10.0\Docs\Qt-5.10.0\qtremoteobjects\qtremoteobjects.index  [31merror[0m="open C:\\Qt\\Qt5.10.0\\Docs\\Qt-5.10.0\\qtremoteobjects\\qtremoteobjects.index: The system cannot find the path specified."
[33mWARN[0m[0000] parser.LoadModule                             [33merror[0m=EOF [33mmodule[0m=RemoteObjects
[31mERRO[0m[0000] failed to load C:\Qt\Qt5.10.0\Docs\Qt-5.10.0\qtcharts\qtcharts.index

**Comment by DBl4de** [comment]
Uh ... I just came across the same issue (the g++ one).

I resolved it by adding g++.exe (located in the bin of the MSYS2 installation directory). But this only works after you also followed the MSYS2 installation guide. So you need both: the official QT installation and then install QT again via the MSYS2. Or at least that what I had to do in order to make it work somehow... prefer ofc to remove one if possible, because now I have used up roughly 20-30 GB of space just for that without writing any code yet :-/

**Comment by NaniteFactory** [comment]
Forget about all the crap on the wiki page.
This is the genuine instruction that actually works:

- Set your enviroment variables. (Two. The picture. But that's just for my case and yours should point to the directory where you install your MSYS2 & Qt)
- Install MSYS2 & open it up.
- `pacman -Syyu`
- `pacman -S mingw-w64-x86_64-qt-creator mingw-w64-x86_64-qt5`
- `pacman -Scc`
- `go get -u -v github.com/therecipe/qt/cmd/...`
- `$GOPATH/bin/qtsetup`

![_](https://user-images.githubusercontent.com/10949969/40920001-40ad58d0-6846-11e8-9951-3100b3f8544b.PNG)

That's it. It may take about an hour or so.
Hope this helps.

**Comment by NaniteFactory** [comment]
Forget about all the crap on the wiki page.
This is the genuine instruction that actually works:

- Set your enviroment variables. (Two. The picture. But that's just for my case and yours should point to the directory where you install your MSYS2 & Qt)
- Install MSYS2 & open it up.
- `pacman -Syyu`
- `pacman -S gcc`
- `pacman -S mingw-w64-x86_64-qt-creator mingw-w64-x86_64-qt5`
- `pacman -Scc`
- `go get -u -v github.com/therecipe/qt/cmd/...`
- `$GOPATH/bin/qtsetup`

![_](https://user-images.githubusercontent.com/10949969/40920001-40ad58d0-6846-11e8-9951-3100b3f8544b.PNG)

That's it. It may take about an hour or so.
Hope this helps.
