### ISSUE TITLE
qtsetup fails on OSX

### ISSUE THREAD

**Issue by morriswinkler** [therecipe/qt#633]
Running following steps on OSX 10.12.6 / XCODE 9.2:
```
# brew install qt5
# qtsetup 
```

results in:
```
PANI[0000] failed to find QT_DIR (/Users/morris/Qt5.10.0)  error="open /Users/morris/Qt5.10.0: no such file or directory"
panic: (*logrus.Entry) (0x13f3ea0,0xc42019cb90)

goroutine 1 [running]:
github.com/sirupsen/logrus.Entry.log(0xc420098190, 0xc420188540, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/Users/morris/tools/go/src/github.com/sirupsen/logrus/entry.go:112 +0x254
github.com/sirupsen/logrus.(*Entry).Panic(0xc42019cb40, 0xc42005b7d0, 0x1, 0x1)
	/Users/morris/tools/go/src/github.com/sirupsen/logrus/entry.go:182 +0xaa
github.com/sirupsen/logrus.(*Entry).Panicf(0xc42019cb40, 0x14239b9, 0x16, 0xc42005bb48, 0x2, 0x2)
	/Users/morris/tools/go/src/github.com/sirupsen/logrus/entry.go:230 +0xed
github.com/therecipe/qt/internal/cmd/setup.Check(0x13ff33a, 0x6, 0x13f0000)
	/Users/morris/tools/go/src/github.com/therecipe/qt/internal/cmd/setup/check.go:147 +0x13e5
main.main()
	/Users/morris/tools/go/src/github.com/therecipe/qt/cmd/qtsetup/main.go:96 +0x2c0
 (develop)
```
Panincing, creating /Users/morris/Qt5.10.0 results in an installation that fails to link QT.   
   

However, following seems to fix it.:
```
# QT_DIR=/usr/local/Cellar/qt/5.10.1 qtsetup
```

Any idea why there is a panic. Anyway Awesome project. Static linking is soo needed:)

**Comment by therecipe** [comment]
Hey

You will just need to export `QT_HOMEBREW=true` before running the setup.
Maybe take a look [here](https://github.com/therecipe/qt/wiki/Installation-on-macOS#homebrew-version-without-iosandroid-support
) as well.

**Comment by morriswinkler** [comment]
Ok i see, 
so the recommended way is to install QT in,
```
~/QT.5.10.X
```

Is it possible to add a something to that panic message on darwin like :

```
export QT_HOMEBREW=true if QT was installed by homebrew
```
