### ISSUE TITLE
qtsetup fails on Exherbo

### ISSUE THREAD

**Issue by hasufell** [therecipe/qt#646]
```
$ qtsetup 
INFO[0000] running: 'qtsetup prep'                      
WARN[0000] failed to create qtrcc symlink in your PATH (/usr/x86_64-pc-linux-gnu/lib/go/bin/qtrcc); please use /home/jule/go/bin/qtrcc instead 
WARN[0000] failed to create qtmoc symlink in your PATH (/usr/x86_64-pc-linux-gnu/lib/go/bin/qtmoc); please use /home/jule/go/bin/qtmoc instead 
WARN[0000] failed to create qtminimal symlink in your PATH (/usr/x86_64-pc-linux-gnu/lib/go/bin/qtminimal); please use /home/jule/go/bin/qtminimal instead 
WARN[0000] failed to create qtdeploy symlink in your PATH (/usr/x86_64-pc-linux-gnu/lib/go/bin/qtdeploy); please use /home/jule/go/bin/qtdeploy instead 
INFO[0000] running: 'qtsetup check linux' [docker=false] [vagrant=false] 
ERRO[0000] failed to detect the Linux distro            
INFO[0000] GOOS:                        'linux'         
INFO[0000] GOARCH:                      'amd64'         
INFO[0000] GOVERSION:                   'go1.10'        
INFO[0000] GOROOT:                      '/usr/x86_64-pc-linux-gnu/lib/go' 
INFO[0000] GOPATH:                   *  '/home/jule/go' 
INFO[0000] GOBIN:                       '/home/jule/go/bin' 
INFO[0000] QT_HASH:                     '491342284b02f5b27d5a19d030e5e446727b464d' 
INFO[0000] QT_VERSION:                  '5.10.0'        
INFO[0000] QT_VERSION_MAJOR:            '5.10.0'        
INFO[0000] QT_DIR:                      '/home/jule/Qt5.10.0' 
PANI[0000] failed to find QT_DIR (/home/jule/Qt5.10.0)   error="open /home/jule/Qt5.10.0: no such file or directory"
panic: (*logrus.Entry) (0x812da0,0xc4201d67d0)

goroutine 1 [running]:
github.com/sirupsen/logrus.Entry.log(0xc42009e190, 0xc4201d4c00, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/home/jule/go/src/github.com/sirupsen/logrus/entry.go:112 +0x254
github.com/sirupsen/logrus.(*Entry).Panic(0xc4201d6780, 0xc42006f7d0, 0x1, 0x1)
	/home/jule/go/src/github.com/sirupsen/logrus/entry.go:182 +0xaa
github.com/sirupsen/logrus.(*Entry).Panicf(0xc4201d6780, 0x842eb7, 0x16, 0xc42006fb48, 0x2, 0x2)
	/home/jule/go/src/github.com/sirupsen/logrus/entry.go:230 +0xed
github.com/therecipe/qt/internal/cmd/setup.Check(0x81dce3, 0x5, 0x810000)
	/home/jule/go/src/github.com/therecipe/qt/internal/cmd/setup/check.go:147 +0x13e5
main.main()
	/home/jule/go/src/github.com/therecipe/qt/cmd/qtsetup/main.go:96 +0x2be
```

I don't know what qtsetup does or what weird logic it uses to find qt, but it appears to be fundamentally broken.

**Comment by hello-code** [comment]
Maybe you should try docker:
[https://hub.docker.com/r/therecipe/qt/](https://hub.docker.com/r/therecipe/qt/)

**Comment by hasufell** [comment]
> Maybe you should try docker:

No thanks, I don't want containerization, I want to install a program using this library.

**Comment by therecipe** [comment]
@hasufell Did you install Qt prior running the setup?

**Comment by hasufell** [comment]
> @hasufell Did you install Qt prior running the setup?

Yes

**Comment by gluaxspeed** [comment]
I am having this issue too did anyone manage to get this to work?

**Comment by therecipe** [comment]
@hasufell Shit, sorry seems like this issue slipped through

@gluaxspeed Do you have the `failed to find QT_DIR` issue as well?

Usually the problem is just that Qt got installed in some alternative location, and so you will only need to export `QT_DIR` to point to the actual location of you Qt installation.

It might be that it got installed under `/opt` or something, or if you did choose another location then  please export `QT_DIR` to point to that location.
