### ISSUE TITLE
qtsetup segmentation violation 

### ISSUE THREAD

**Issue by r0l1** [therecipe/qt#650]
```
INFO[0000] running: 'qtsetup prep'                      
WARN[0000] failed to create qtrcc symlink in your PATH (/usr/lib/go/bin/qtrcc); please use /home/foo/go/bin/qtrcc instead 
WARN[0000] failed to create qtmoc symlink in your PATH (/usr/lib/go/bin/qtmoc); please use /home/foo/go/bin/qtmoc instead 
WARN[0000] failed to create qtminimal symlink in your PATH (/usr/lib/go/bin/qtminimal); please use /home/foo/go/bin/qtminimal instead 
WARN[0000] failed to create qtdeploy symlink in your PATH (/usr/lib/go/bin/qtdeploy); please use /home/foo/go/bin/qtdeploy instead 
INFO[0000] running: 'qtsetup check linux' [docker=false] [vagrant=false] 
INFO[0000] GOOS:                        'linux'         
INFO[0000] GOARCH:                      'amd64'         
INFO[0000] GOVERSION:                   'go1.10.3'      
INFO[0000] GOfooT:                      '/usr/lib/go'   
INFO[0000] GOPATH:                   *  '/home/foo/go' 
INFO[0000] GOBIN:                       '/home/foo/go/bin' 
INFO[0000] QT_HASH:                     '491342284b02f5b27d5a19d030e5e446727b464d' 
INFO[0000] QT_VERSION:                  '5.11.0'        
INFO[0000] QT_VERSION_MAJOR:            '5.11.0'        
INFO[0000] QT_DIR:                      '/home/foo/Qt5.11.0' 
INFO[0000] QT_STUB:                     'false'         
INFO[0000] QT_DEBUG:                    'false'         
INFO[0000] QT_QMAKE_DIR:                ''              
INFO[0000] QT_WEBKIT:                   'false'         
INFO[0000] QT_DISTRO:                   'arch'          
INFO[0000] QT_PKG_CONFIG:            *  'true'          
INFO[0000] QT_DOC_DIR:                  '/usr/share/doc/qt' 
INFO[0000] QT_MISC_DIR:                 '/usr/lib/qt'   
INFO[0000] running: 'qtsetup generate linux' [docker=false] [vagrant=false] 
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x40 pc=0x528006]

goroutine 1 [running]:
github.com/therecipe/qt/internal/binding/parser.(*Class).GetBases(0x0, 0x0, 0x0, 0xab8498)
	/home/foo/go/src/github.com/therecipe/qt/internal/binding/parser/class.go:70 +0x26
github.com/therecipe/qt/internal/binding/parser.(*Class).GetAllBasesRecursiveCheckFailed(0x0, 0x1, 0xc426a68808, 0xf, 0xab90c0, 0x0)
	/home/foo/go/src/github.com/therecipe/qt/internal/binding/parser/class.go:92 +0x96
github.com/therecipe/qt/internal/binding/parser.(*Class).GetAllBases(0x0, 0x0, 0x0, 0x0)
	/home/foo/go/src/github.com/therecipe/qt/internal/binding/parser/class.go:80 +0x34
github.com/therecipe/qt/internal/binding/parser.(*Function).IsDerivedFromVirtual(0xc4227f6540, 0xaa00000000000000)
	/home/foo/go/src/github.com/therecipe/qt/internal/binding/parser/function.go:500 +0x7b
github.com/therecipe/qt/internal/binding/parser.(*Function).fixGeneral_AfterClasses(0xc4227f6540)
	/home/foo/go/src/github.com/therecipe/qt/internal/binding/parser/function_fix.go:58 +0xb4
github.com/therecipe/qt/internal/binding/parser.(*Class).fixFunctions(0xc42a71cea0, 0x86a730)
	/home/foo/go/src/github.com/therecipe/qt/internal/binding/parser/class_fix.go:33 +0x52
github.com/therecipe/qt/internal/binding/parser.(*Class).fix(0xc42a71cea0)
	/home/foo/go/src/github.com/therecipe/qt/internal/binding/parser/class_fix.go:28 +0xcd
github.com/therecipe/qt/internal/binding/parser.(*Module).Prepare(0xc42256c420, 0x86a748, 0xc4201dd870)
	/home/foo/go/src/github.com/therecipe/qt/internal/binding/parser/module.go:84 +0x1033
github.com/therecipe/qt/internal/binding/parser.LoadModules()
	/home/foo/go/src/github.com/therecipe/qt/internal/binding/parser/parser.go:48 +0x1ac
github.com/therecipe/qt/internal/cmd/setup.Generate(0x81daa6, 0x5, 0x810000)
	/home/foo/go/src/github.com/therecipe/qt/internal/cmd/setup/generate.go:23 +0x147
main.main()
	/home/foo/go/src/github.com/therecipe/qt/cmd/qtsetup/main.go:97 +0x2ee
```

**Comment by akhenakh** [comment]
It seems Qt 5.11 is not supported yet

**Comment by therecipe** [comment]
Hey

Qt 5.11.x should work now with: https://github.com/therecipe/qt/commit/5355937d17e9eee62460706cb9a033180014400e
