### ISSUE TITLE
Panic when initializing QtWebView on Linux

### ISSUE THREAD

**Issue by quantonganh** [therecipe/qt#703]
Code:

```
func main() {
	core.QCoreApplication_SetAttribute(core.Qt__AA_EnableHighDpiScaling, true)
	var app = widgets.NewQApplication(len(os.Args), os.Args)
	webview.QtWebView_Initialize()
        ...
```

Error:

```
fatal error: unexpected signal during runtime execution
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x7fb278032c5d]

runtime stack:
runtime.throw(0x12bfde2, 0x2a)
	/usr/local/go/src/runtime/panic.go:616 +0x81
runtime.sigpanic()
	/usr/local/go/src/runtime/signal_unix.go:372 +0x28e

goroutine 1 [syscall, locked to thread]:
runtime.cgocall(0xfc1ec0, 0xc420211ee8, 0x0)
	/usr/local/go/src/runtime/cgocall.go:128 +0x64 fp=0xc420211eb8 sp=0xc420211e80 pc=0x57cec4
github.com/therecipe/qt/webview._Cfunc_QtWebView_QtWebView_Initialize()
	_cgo_gotypes.go:75 +0x41 fp=0xc420211ee8 sp=0xc420211eb8 pc=0xf40ab1
github.com/therecipe/qt/webview.QtWebView_Initialize()
	/home/user/work/src/github.com/therecipe/qt/webview/webview-minimal.go:71 +0x62 fp=0xc420211f20 sp=0xc420211ee8 pc=0xf40b32
main.initWeb()
	/go/src/git.domain.com/wl/main/ui/client/main_web_qml.go:12 +0x20 fp=0xc420211f30 sp=0xc420211f20 pc=0xf41db0
main.main()
	/go/src/git.domain.com/wl/main/ui/client/main.go:17 +0x76 fp=0xc420211f88 sp=0xc420211f30 pc=0xf40c36
runtime.main()
	/usr/local/go/src/runtime/proc.go:198 +0x212 fp=0xc420211fe0 sp=0xc420211f88 pc=0x5a6a72
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:2361 +0x1 fp=0xc420211fe8 sp=0xc420211fe0 pc=0x5d18d1

goroutine 5 [syscall]:
os/signal.signal_recv(0x0)
	/usr/local/go/src/runtime/sigqueue.go:139 +0xa6
os/signal.loop()
	/usr/local/go/src/os/signal/signal_unix.go:22 +0x22
created by os/signal.init.0
	/usr/local/go/src/os/signal/signal_unix.go:28 +0x41

goroutine 6 [chan receive]:
github.com/getsentry/raven-go.(*Client).worker(0xc42028c420)
	/go/godeps/src/github.com/getsentry/raven-go/client.go:418 +0x170
created by github.com/getsentry/raven-go.newClient
	/go/godeps/src/github.com/getsentry/raven-go/client.go:307 +0x105
```

This does not happen on OS X. I've tried to enable `QT_DEBUG` [as you suggested](https://github.com/therecipe/qt/issues/364#issuecomment-308865703), but no function is printed. Why?

**Comment by therecipe** [comment]
Hey

This should be fixed now with: https://github.com/therecipe/qt/commit/47bca7ecfd76d584c1e7ba142ca3c8a15767c008
It seems like the webview module now depends on the webengine in 5.11.

>I've tried to enable QT_DEBUG as you suggested, but no function is printed. Why?

Did you set QT_DEBUG before running qtdeploy or qtminimal and also while running the application?

**Comment by quantonganh** [comment]
>Did you set QT_DEBUG before running qtdeploy or qtminimal

Yes.

>and also while running the application?

I didn't know we have to do that.
I've just tried and it's ok now:

```
21:52:11 	QCoreApplication                             QCoreApplication_SetAttribute(attribute Qt__ApplicationAttribute, on bool)
21:52:11 	QApplication                                 NewQApplication(argc int, argv []string) *QApplication
21:52:11 	QObject                                      ConnectDestroyed(f func (obj *QObject) )
21:52:11 	QApplication                                 callbackQApplication_ConnectNotify(ptr unsafe.Pointer, sign unsafe.Pointer)
21:52:11 	QApplication                                 ConnectNotifyDefault(sign core.QMetaMethod_ITF)
21:52:11 	QtWebView                                    QtWebView_Initialize()
fatal error: unexpected signal during runtime execution
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x7fdb2c162c5d]
...
```
