### ISSUE TITLE
qtsetup panics

### ISSUE THREAD

**Issue by freman** [therecipe/qt#734]
Installed the latest QT today via pkg on OSX, made sure I had all the latest go code, qtsetup panics :(

```
shannon@mac ~ $ qtsetup
INFO[0000] running: 'qtsetup prep'
INFO[0000] successfully created qtrcc symlink in your PATH (/usr/local/bin/qtrcc)
INFO[0000] successfully created qtmoc symlink in your PATH (/usr/local/bin/qtmoc)
INFO[0000] successfully created qtminimal symlink in your PATH (/usr/local/bin/qtminimal)
INFO[0000] successfully created qtdeploy symlink in your PATH (/usr/local/bin/qtdeploy)
INFO[0000] running: 'qtsetup check darwin' [docker=false] [vagrant=false]
INFO[0000] GOOS:                        'darwin'
INFO[0000] GOARCH:                      'amd64'
INFO[0000] GOVERSION:                   'go1.11.2'
INFO[0000] GOROOT:                      '/usr/local/go'
INFO[0000] GOPATH:                   *  '/Users/shannon/go'
INFO[0000] GOBIN:                       '/Users/shannon/go/bin'
INFO[0000] QT_HASH:                     '599f8bc2c975802ea592c43d110209f0a267b188'
INFO[0000] QT_VERSION:               *  '5.11.1'
INFO[0000] QT_VERSION_MAJOR:            '5.11.1'
INFO[0000] QT_DIR:                      '/Users/shannon/Qt5.11.1'
INFO[0000] QT_STUB:                     'false'
INFO[0000] QT_DEBUG:                    'false'
INFO[0000] QT_QMAKE_DIR:                ''
INFO[0000] QT_WEBKIT:                   'false'
INFO[0000] QT_HOMEBREW:                 'false'
INFO[0000] XCODE_DIR:                   '/Applications/Xcode.app'
INFO[0000] running: 'qtsetup generate darwin' [docker=false] [vagrant=false]
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x40 pc=0x1123166]

goroutine 1 [running]:
github.com/therecipe/qt/internal/binding/parser.(*Class).GetBases(0x0, 0x0, 0x0, 0x178c318)
	/Users/shannon/go/src/github.com/therecipe/qt/internal/binding/parser/class.go:64 +0x26
github.com/therecipe/qt/internal/binding/parser.(*Class).GetAllBasesRecursiveCheckFailed(0x0, 0x1, 0xc003a82ec8, 0xf, 0x178cd60, 0x0)
	/Users/shannon/go/src/github.com/therecipe/qt/internal/binding/parser/class.go:86 +0x96
github.com/therecipe/qt/internal/binding/parser.(*Class).GetAllBases(0x0, 0x0, 0x0, 0x0)
	/Users/shannon/go/src/github.com/therecipe/qt/internal/binding/parser/class.go:74 +0x34
github.com/therecipe/qt/internal/binding/parser.(*Function).IsDerivedFromVirtual(0xc003ae5040, 0x4d000000013ee000)
	/Users/shannon/go/src/github.com/therecipe/qt/internal/binding/parser/function.go:466 +0x72
github.com/therecipe/qt/internal/binding/parser.(*Function).fixGeneral_AfterClasses(0xc003ae5040)
	/Users/shannon/go/src/github.com/therecipe/qt/internal/binding/parser/function_fix.go:58 +0x9b
github.com/therecipe/qt/internal/binding/parser.(*Class).fixFunctions(0xc003a3b080, 0x1450b98)
	/Users/shannon/go/src/github.com/therecipe/qt/internal/binding/parser/class_fix.go:33 +0x52
github.com/therecipe/qt/internal/binding/parser.(*Class).fix(0xc003a3b080)
	/Users/shannon/go/src/github.com/therecipe/qt/internal/binding/parser/class_fix.go:28 +0xc3
github.com/therecipe/qt/internal/binding/parser.(*Module).Prepare(0xc0001c6210, 0x1450bb0, 0xc00009cd80)
	/Users/shannon/go/src/github.com/therecipe/qt/internal/binding/parser/module.go:84 +0xf1f
github.com/therecipe/qt/internal/binding/parser.LoadModules()
	/Users/shannon/go/src/github.com/therecipe/qt/internal/binding/parser/parser.go:46 +0x1bd
github.com/therecipe/qt/internal/cmd/setup.Generate(0x14042b9, 0x6, 0x1400000)
	/Users/shannon/go/src/github.com/therecipe/qt/internal/cmd/setup/generate.go:22 +0x147
main.main()
	/Users/shannon/go/src/github.com/therecipe/qt/cmd/qtsetup/main.go:88 +0x258
```

For good measure I copy/pasted the path from above into ls to make sure it was there

```
shannon@mac ~ $ ls /Users/shannon/Qt5.11.1
5.11.1              Examples            Licenses            MaintenanceTool.dat Qt Creator.app      dist
Docs                InstallationLog.txt MaintenanceTool.app MaintenanceTool.ini components.xml      network.xml
```

**Comment by therecipe** [comment]
Hey

Please try to update the binding by running `qtsetup upgrade`, or if this won't work then manually.
You somewhat still have an old version of the binding -> https://github.com/therecipe/qt/commit/599f8bc2c975802ea592c43d110209f0a267b188

**Comment by freman** [comment]
Thanks, trying that now, I'll report back when I start slapping my forehead for missing that.

**Comment by freman** [comment]
Yep that fixed it for me, sorry.

**Comment by therecipe** [comment]
No problem :)
