### ISSUE TITLE
concurrent map read and map write when running qtmoc?

### ISSUE THREAD

**Issue by quantonganh** [therecipe/qt#738]
I pulled the latest `linux` tag that was built 6 days ago: https://hub.docker.com/r/therecipe/qt/tags/
and got this error when running `qtmoc`:

```
+ qtmoc
fatal error: concurrent map read and map write
goroutine 4891 [running]:
runtime.throw(0x7313c3, 0x21)
	/usr/local/go/src/runtime/panic.go:608 +0x72 fp=0xc001093a10 sp=0xc0010939e0 pc=0x42bab2
runtime.mapaccess1_faststr(0x6bb7e0, 0xc00008cc60, 0x6f79f6, 0x3, 0x7)
	/usr/local/go/src/runtime/map_faststr.go:21 +0x418 fp=0xc001093a80 sp=0xc001093a10 pc=0x412c58
github.com/therecipe/qt/internal/binding/templater.isAlreadyCached(0x6f79f6, 0x3, 0xc0005bfe80, 0x39, 0x6f8457, 0x5, 0x1, 0xc010772400, 0x9, 0x10, ...)
	/home/user/work/src/github.com/therecipe/qt/internal/binding/templater/template_cgo_qmake.go:95 +0x4ae fp=0xc001093d38 sp=0xc001093a80 pc=0x64a1ee
github.com/therecipe/qt/internal/binding/templater.cgoTemplate(0x6f79f6, 0x3, 0xc0005bfe80, 0x39, 0x6f8457, 0x5, 0x1, 0xc0019ba840, 0xa, 0x0, ...)
	/home/user/work/src/github.com/therecipe/qt/internal/binding/templater/template_cgo_qmake.go:54 +0x844 fp=0xc001093e68 sp=0xc001093d38 pc=0x649a04
github.com/therecipe/qt/internal/binding/templater.CgoTemplateSafe(0x6f79f6, 0x3, 0xc0005bfe80, 0x39, 0x6f8457, 0x5, 0x1, 0xc0019ba840, 0xa, 0x0, ...)
	/home/user/work/src/github.com/therecipe/qt/internal/binding/templater/template_cgo_qmake.go:30 +0xe9 fp=0xc001093ef8 sp=0xc001093e68 pc=0x649189
github.com/therecipe/qt/internal/cmd/moc.moc.func4(0xc0005bfe80, 0x39, 0x6f8457, 0x5, 0xc0019ba840, 0xa, 0x0, 0x0, 0xc010772400, 0x9, ...)
	/home/user/work/src/github.com/therecipe/qt/internal/cmd/moc/moc.go:383 +0xe0 fp=0xc001093f88 sp=0xc001093ef8 pc=0x6870c0
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1333 +0x1 fp=0xc001093f90 sp=0xc001093f88 pc=0x457b51
created by github.com/therecipe/qt/internal/cmd/moc.moc
	/home/user/work/src/github.com/therecipe/qt/internal/cmd/moc/moc.go:382 +0x33da

goroutine 1 [runnable]:
github.com/sirupsen/logrus.(*Entry).WithField(0xc01111b680, 0x6f7f64, 0x4, 0x6aca40, 0xc0065bb3b0, 0xc00a6bed01)
	/home/user/work/src/github.com/sirupsen/logrus/entry.go:101 +0x11f
github.com/sirupsen/logrus.(*Logger).WithField(0xc00006a2a0, 0x6f7f64, 0x4, 0x6aca40, 0xc0065bb3b0, 0x0)
	/home/user/work/src/github.com/sirupsen/logrus/logger.go:108 +0xa3
github.com/therecipe/qt/internal/cmd/moc.parse(0xc00087e640, 0x47, 0xc0005bfe80, 0x39, 0xc0004161f0, 0x0, 0x0, 0x1, 0x1)
	/home/user/work/src/github.com/therecipe/qt/internal/cmd/moc/moc.go:422 +0x27c
github.com/therecipe/qt/internal/cmd/moc.moc(0xc000016244, 0x2e, 0x6f8457, 0x5, 0x0, 0x0, 0xc000010000, 0x0, 0x0)
	/home/user/work/src/github.com/therecipe/qt/internal/cmd/moc/moc.go:146 +0x3a73
github.com/therecipe/qt/internal/cmd/moc.Moc(0xc000016244, 0x2e, 0x6f8457, 0x5, 0x0, 0x0, 0x0)
	/home/user/work/src/github.com/therecipe/qt/internal/cmd/moc/moc.go:54 +0x8f
main.main()
	/home/user/work/src/github.com/therecipe/qt/cmd/qtmoc/main.go:95 +0x529

goroutine 4892 [runnable]:
syscall.readlen(0x6, 0xc00108f858, 0x8, 0x5, 0xc00043ae00, 0x6a)
	/usr/local/go/src/syscall/zsyscall_linux_amd64.go:1025 +0xfd
syscall.forkExec(0xc00a68c020, 0x1d, 0xc002e9e000, 0x4, 0x4, 0xc00108f9c0, 0x20, 0x0, 0xc00a68c100)
	/usr/local/go/src/syscall/exec_unix.go:203 +0x3d0
syscall.StartProcess(0xc00a68c020, 0x1d, 0xc002e9e000, 0x4, 0x4, 0xc00108f9c0, 0x2, 0x4, 0x0, 0x0)
	/usr/local/go/src/syscall/exec_unix.go:241 +0x64
os.startProcess(0xc00a68c020, 0x1d, 0xc002e9e000, 0x4, 0x4, 0xc00108fb50, 0xc0101bfc00, 0x69, 0x69)
	/usr/local/go/src/os/exec_posix.go:46 +0x213
os.StartProcess(0xc00a68c020, 0x1d, 0xc002e9e000, 0x4, 0x4, 0xc00108fb50, 0x0, 0x0, 0x0)
	/usr/local/go/src/os/exec.go:102 +0x7c
os/exec.(*Cmd).Start(0xc0007e2160, 0x1, 0xc0043fa000)
	/usr/local/go/src/os/exec/exec.go:383 +0x4b3
os/exec.(*Cmd).Run(0xc0007e2160, 0xc0043fa000, 0xc01127d4a0)
	/usr/local/go/src/os/exec/exec.go:306 +0x2b
os/exec.(*Cmd).CombinedOutput(0xc0007e2160, 0xc00108fcc8, 0x1, 0x1, 0xc00108fdd0, 0x0)
	/usr/local/go/src/os/exec/exec.go:525 +0xf7
github.com/therecipe/qt/internal/utils.RunCmd(0xc0007e2160, 0x6f937d, 0x7, 0x3, 0x3)
	/home/user/work/src/github.com/therecipe/qt/internal/utils/utils.go:93 +0x461
github.com/therecipe/qt/internal/cmd/moc.moc.func5(0x6f8457, 0x5, 0xc0005bfe80, 0x39, 0x0, 0x0)
	/home/user/work/src/github.com/therecipe/qt/internal/cmd/moc/moc.go:389 +0x239
created by github.com/therecipe/qt/internal/cmd/moc.moc
	/home/user/work/src/github.com/therecipe/qt/internal/cmd/moc/moc.go:388 +0x3459

goroutine 4890 [runnable]:
go/parser.(*parser).checkExprOrType(0xc00b328180, 0x7a7220, 0xc00814c1c0, 0xc00814c1c0, 0x18)
	/usr/local/go/src/go/parser/parser.go:1445 +0x1ca
go/parser.(*parser).parseRhsOrType(0xc00b328180, 0x31, 0x108e)
	/usr/local/go/src/go/parser/parser.go:1639 +0x68
go/parser.(*parser).parseCallOrConversion(0xc00b328180, 0x7a7560, 0xc00814c1a0, 0x0)
	/usr/local/go/src/go/parser/parser.go:1259 +0x121
go/parser.(*parser).parsePrimaryExpr(0xc00b328180, 0x986f00, 0x0, 0x0)
	/usr/local/go/src/go/parser/parser.go:1497 +0xcc
go/parser.(*parser).parseUnaryExpr(0xc00b328180, 0xc00814c100, 0x0, 0x0)
	/usr/local/go/src/go/parser/parser.go:1583 +0x383
go/parser.(*parser).parseBinaryExpr(0xc00b328180, 0xc010035300, 0x1, 0x0, 0x0)
	/usr/local/go/src/go/parser/parser.go:1600 +0x69
go/parser.(*parser).parseExpr(0xc00b328180, 0xc00b328100, 0x0, 0x0)
	/usr/local/go/src/go/parser/parser.go:1625 +0x57
go/parser.(*parser).parseExprList(0xc00b328180, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/go/parser/parser.go:569 +0x5b
go/parser.(*parser).parseRhsList(0xc00b328180, 0xc0100353b0, 0x1, 0x1)
	/usr/local/go/src/go/parser/parser.go:609 +0x42
go/parser.(*parser).parseSimpleStmt(0xc00b328180, 0x1, 0x0, 0x0, 0xc010035300)
	/usr/local/go/src/go/parser/parser.go:1682 +0x375
go/parser.(*parser).parseStmt(0xc00b328180, 0x0, 0x0)
	/usr/local/go/src/go/parser/parser.go:2218 +0x81
go/parser.(*parser).parseStmtList(0xc00b328180, 0x0, 0x0, 0x0)
	/usr/local/go/src/go/parser/parser.go:1068 +0x8a
go/parser.(*parser).parseBlockStmt(0xc00b328180, 0x0)
	/usr/local/go/src/go/parser/parser.go:1097 +0xd0
go/parser.(*parser).parseIfStmt(0xc00b328180, 0x0)
	/usr/local/go/src/go/parser/parser.go:1900 +0x144
go/parser.(*parser).parseStmt(0xc00b328180, 0x0, 0x0)
	/usr/local/go/src/go/parser/parser.go:2237 +0x454
go/parser.(*parser).parseStmtList(0xc00b328180, 0xc010035360, 0x1, 0x1)
	/usr/local/go/src/go/parser/parser.go:1068 +0x8a
go/parser.(*parser).parseBlockStmt(0xc00b328180, 0x0)
	/usr/local/go/src/go/parser/parser.go:1097 +0xd0
go/parser.(*parser).parseIfStmt(0xc00b328180, 0x0)
	/usr/local/go/src/go/parser/parser.go:1900 +0x144
go/parser.(*parser).parseStmt(0xc00b328180, 0x0, 0x0)
	/usr/local/go/src/go/parser/parser.go:2237 +0x454
go/parser.(*parser).parseStmtList(0xc00b328180, 0x0, 0x0, 0x0)
	/usr/local/go/src/go/parser/parser.go:1068 +0x8a
go/parser.(*parser).parseBody(0xc00b328180, 0xc0100352c0, 0x0)
	/usr/local/go/src/go/parser/parser.go:1082 +0x162
go/parser.(*parser).parseFuncDecl(0xc00b328180, 0x0)
	/usr/local/go/src/go/parser/parser.go:2441 +0x36a
go/parser.(*parser).parseDecl(0xc00b328180, 0xc00008c630, 0x0, 0x0)
	/usr/local/go/src/go/parser/parser.go:2485 +0x167
go/parser.(*parser).parseFile(0xc00b328180, 0x0)
	/usr/local/go/src/go/parser/parser.go:2540 +0x311
go/parser.ParseFile(0xc010756040, 0x6f8a99, 0x6, 0x6a9980, 0xc0047b6000, 0x4, 0x0, 0x0, 0x0)
	/usr/local/go/src/go/parser/interface.go:117 +0x183
golang.org/x/tools/imports.parse(0xc010756040, 0x6f8a99, 0x6, 0xc015244000, 0x45e3e, 0x46000, 0xc0112d9e90, 0x43d66c, 0xc0069aee98, 0x4073f1, ...)
	/home/user/work/src/golang.org/x/tools/imports/imports.go:133 +0x114
golang.org/x/tools/imports.Process(0x6f8a99, 0x6, 0xc015244000, 0x45e3e, 0x46000, 0xc0112d9e90, 0x7964282066692065, 0x61635f63696d616e, 0x6e696150513c7473, 0x5765636976654474, ...)
	/home/user/work/src/golang.org/x/tools/imports/imports.go:60 +0x100
github.com/therecipe/qt/internal/cmd/moc.moc.func3(0xc015244000, 0x45e3e, 0x46000, 0xc0005bfe80, 0x39)
	/home/user/work/src/github.com/therecipe/qt/internal/cmd/moc/moc.go:369 +0xd4
created by github.com/therecipe/qt/internal/cmd/moc.moc
	/home/user/work/src/github.com/therecipe/qt/internal/cmd/moc/moc.go:363 +0x32f1
```

**Comment by therecipe** [comment]
Hey

Sorry, this was probably introduced by https://github.com/therecipe/qt/commit/3de3e2be88af3cdfa0d49ca4238d2cd4bc713665, but should be fixed now with https://github.com/therecipe/qt/commit/531ee97d86621d7f1e7dbe17a2caacff6c8f87a2

The new image(s) should be ready once https://dev.azure.com/therecipe/qt/_build/results?buildId=85&view=logs is done
