### ISSUE TITLE
qtsetup fail with qt5.12.0

### ISSUE THREAD

**Issue by forestsource** [therecipe/qt#748]
ubuntu18.04
qt 5.12.0

I renamed `~/Qt/Docs/Qt-5.12.0/qtquickcontrols` to `~/Qt/Docs/Qt-5.12.0/qtquickcontrols2`
and all `qtquickcontrols.*` rename to  `qtquickcontrols2.*`

but,  panic occurred.
```
forestsource@ubuntu:~/$ qtsetup -qt_version 5.12.0
INFO[0000] running: 'qtsetup prep'                      
WARN[0000] failed to create qtrcc symlink in your PATH (/usr/local/go/bin/qtrcc); please use /home/forestsource/go/bin/qtrcc instead 
WARN[0000] failed to create qtmoc symlink in your PATH (/usr/local/go/bin/qtmoc); please use /home/forestsource/go/bin/qtmoc instead 
WARN[0000] failed to create qtminimal symlink in your PATH (/usr/local/go/bin/qtminimal); please use /home/forestsource/go/bin/qtminimal instead 
WARN[0000] failed to create qtdeploy symlink in your PATH (/usr/local/go/bin/qtdeploy); please use /home/forestsource/go/bin/qtdeploy instead 
INFO[0000] running: 'qtsetup check linux' [docker=false] [vagrant=false] 
INFO[0000] GOOS:                        'linux'         
INFO[0000] GOARCH:                      'amd64'         
INFO[0000] GOVERSION:                   'go1.11'        
INFO[0000] GOROOT:                   *  '/usr/local/go' 
INFO[0000] GOPATH:                   *  '/home/forestsource/go' 
INFO[0000] GOBIN:                       '/home/forestsource/go/bin' 
INFO[0000] QT_HASH:                     '33cc66032318128c0fd7657937d109bc8d75e478' 
INFO[0000] QT_API:                      ''              
INFO[0000] QT_VERSION:               *  '5.12.0'        
INFO[0000] QT_VERSION_MAJOR:            '5.12.0'        
INFO[0000] QT_DIR:                      '/home/forestsource/Qt' 
INFO[0000] QT_STUB:                     'false'         
INFO[0000] QT_DEBUG:                    'false'         
INFO[0000] QT_QMAKE_DIR:                ''              
INFO[0000] QT_WEBKIT:                   'false'         
INFO[0000] QT_DISTRO:                   'ubuntu'        
INFO[0000] QT_PKG_CONFIG:               'false'         
INFO[0000] running: 'qtsetup generate linux' [docker=false] [vagrant=false] 
INFO[0008] generating full qt/core                      
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x50 pc=0x5b5ae9]

goroutine 1 [running]:
github.com/therecipe/qt/internal/binding/parser.(*Function).IsSupported(0xc0126e0380, 0xc006dd69d0)
	/home/forestsource/go/src/github.com/therecipe/qt/internal/binding/parser/function.go:316 +0x469
github.com/therecipe/qt/internal/binding/templater.cTemplateFunctions(0xc007eeca80, 0xc0127b3d40, 0x994860, 0x9509e8, 0x2, 0x0)
	/home/forestsource/go/src/github.com/therecipe/qt/internal/binding/templater/template_c.go:47 +0x3aa
github.com/therecipe/qt/internal/binding/templater.cTemplate(0xc007eeca80, 0xc0127b3d40, 0x994848, 0x994860, 0x9509e8, 0x2, 0x0)
	/home/forestsource/go/src/github.com/therecipe/qt/internal/binding/templater/template_c.go:15 +0xc2
github.com/therecipe/qt/internal/binding/templater.CppTemplate(0xc001c68e60, 0x6, 0x0, 0x95232d, 0x5, 0x0, 0x0, 0x0, 0x0, 0x0)
	/home/forestsource/go/src/github.com/therecipe/qt/internal/binding/templater/template_cpp.go:388 +0x1551
github.com/therecipe/qt/internal/binding/templater.GenModule(0x951301, 0x4, 0x95232d, 0x5, 0x0)
	/home/forestsource/go/src/github.com/therecipe/qt/internal/binding/templater/templater.go:54 +0xf8f
github.com/therecipe/qt/internal/cmd/setup.Generate(0x95232d, 0x5, 0x950000)
	/home/forestsource/go/src/github.com/therecipe/qt/internal/cmd/setup/generate.go:44 +0x394
main.main()
	/home/forestsource/go/src/github.com/therecipe/qt/cmd/qtsetup/main.go:109 +0x3b5

```

**Comment by therecipe** [comment]
Hey

I'm already working on the support for 5.12
I will just need to do a few more tests and will probably push the changes in the next 24 hours.

In the meantime you could try to run `qtsetup -qt_api 5.11.1 -qt_version 5.12.0`, which will link against 5.12.0 as well, but uses the 5.11.1 API to generate code.
(But I haven't tested this with the current master, so maybe it won't work as well)

**Comment by therecipe** [comment]
Qt 5.12 should be supported now with https://github.com/therecipe/qt/commit/5746a84fb25d76c6b43b253a73f3aaa2344b03cb
