### ISSUE TITLE
 out of memory when qtsetup with qt/widgets or some other package 

### ISSUE THREAD

**Issue by hick** [therecipe/qt#842]
```
time="2019-04-20T13:57:16+08:00" level=info msg="installing full qt/widgets "
github.com/therecipe/qt/widgets
# github.com/therecipe/qt/widgets
runtime: out of memory: cannot allocate 401408-byte block (1681555456 in use)
fatal error: out of memory

runtime stack:
runtime.throw(0xbe2a8d, 0xd)
        c:/go/src/runtime/panic.go:608 +0x64
runtime.largeAlloc(0x60bc8, 0x13810101, 0x44bc20)
        c:/go/src/runtime/malloc.go:1021 +0x107
runtime.mallocgc.func1()
        c:/go/src/runtime/malloc.go:914 +0x39
runtime.systemstack(0x0)
        c:/go/src/runtime/asm_386.s:396 +0x53
runtime.mstart()
        c:/go/src/runtime/proc.go:1229

```

it can be repeated in my tow machine both with windows 7 64, one with 4G memory and one with 8G memory , in cmd.exe with administrator privildge:

and tried serveral times,   when qtsetup  try to installing qt/widgets, sometime for other package like qt/multimedia too,

![image](https://user-images.githubusercontent.com/38886/56453979-abbe9800-637c-11e9-8dfe-00ca89da7051.png)

the above is just little part, and the more as following:

```
time="2019-04-20T13:57:02+08:00" level=info msg="installing full qt/dbus "
time="2019-04-20T13:57:05+08:00" level=info msg="installing full qt/nfc "
time="2019-04-20T13:57:07+08:00" level=info msg="installing full qt/script "
time="2019-04-20T13:57:10+08:00" level=info msg="installing full qt/sensors "
time="2019-04-20T13:57:13+08:00" level=info msg="installing full qt/positioning
"
time="2019-04-20T13:57:16+08:00" level=info msg="installing full qt/widgets "
github.com/therecipe/qt/widgets
# github.com/therecipe/qt/widgets
runtime: out of memory: cannot allocate 401408-byte block (1681555456 in use)
fatal error: out of memory

runtime stack:
runtime.throw(0xbe2a8d, 0xd)
        c:/go/src/runtime/panic.go:608 +0x64
runtime.largeAlloc(0x60bc8, 0x13810101, 0x44bc20)
        c:/go/src/runtime/malloc.go:1021 +0x107
runtime.mallocgc.func1()
        c:/go/src/runtime/malloc.go:914 +0x39
runtime.systemstack(0x0)
        c:/go/src/runtime/asm_386.s:396 +0x53
runtime.mstart()
        c:/go/src/runtime/proc.go:1229

goroutine 5 [running]:
runtime.systemstack_switch()
        c:/go/src/runtime/asm_386.s:357 fp=0x37822b98 sp=0x37822b94 pc=0x44d2e0
runtime.mallocgc(0x60bc8, 0xb8f320, 0x479ef901, 0x479ef960)
        c:/go/src/runtime/malloc.go:913 +0x676 fp=0x37822bec sp=0x37822b98 pc=0x
409cb6
runtime.makeslice(0xb8f320, 0x182f2, 0x182f2, 0x479ef998, 0x143d7d08, 0x143d7ce4
)
        c:/go/src/runtime/slice.go:70 +0x59 fp=0x37822c00 sp=0x37822bec pc=0x439
409
cmd/compile/internal/ssa.newSparseMap(...)
        c:/go/src/cmd/compile/internal/ssa/sparsemap.go:26
cmd/compile/internal/ssa.newBiasedSparseMap(...)
        c:/go/src/cmd/compile/internal/ssa/biasedsparsemap.go:27
cmd/compile/internal/ssa.numberLines(0x16a046e0)
        c:/go/src/cmd/compile/internal/ssa/numberlines.go:171 +0x6e6 fp=0x37822d
2c sp=0x37822c00 pc=0x5d5086
cmd/compile/internal/ssa.Compile(0x16a046e0)
        c:/go/src/cmd/compile/internal/ssa/compile.go:70 +0x26c fp=0x37825f04 sp
=0x37822d2c pc=0x5a896c
cmd/compile/internal/gc.buildssa(0x1ce9e300, 0x0, 0x0)
        c:/go/src/cmd/compile/internal/gc/ssa.go:211 +0x8ca fp=0x37825f98 sp=0x3
7825f04 pc=0xaa6f4a
cmd/compile/internal/gc.compileSSA(0x1ce9e300, 0x0)
        c:/go/src/cmd/compile/internal/gc/pgen.go:259 +0x2d fp=0x37825fcc sp=0x3
7825f98 pc=0xa7ba5d
cmd/compile/internal/gc.compileFunctions.func2(0x2c1f68c0, 0x1883af40, 0x0)
        c:/go/src/cmd/compile/internal/gc/pgen.go:323 +0x3b fp=0x37825fe0 sp=0x3
7825fcc pc=0xb17bbb
runtime.goexit()
        c:/go/src/runtime/asm_386.s:1324 +0x1 fp=0x37825fe4 sp=0x37825fe0 pc=0x4
4eb11
created by cmd/compile/internal/gc.compileFunctions
        c:/go/src/cmd/compile/internal/gc/pgen.go:321 +0xee

goroutine 1 [chan send]:
cmd/compile/internal/gc.compileFunctions()
        c:/go/src/cmd/compile/internal/gc/pgen.go:329 +0x136
cmd/compile/internal/gc.Main(0xbfe770)
        c:/go/src/cmd/compile/internal/gc/main.go:651 +0x2381
main.main()
        c:/go/src/cmd/compile/main.go:51 +0x7e

goroutine 6 [runnable]:
cmd/compile/internal/ssa.(*sortvalues).Less(0x22ffad40, 0x21, 0x20, 0x14330101)
        <autogenerated>:1 +0x6c
sort.insertionSort(0xd326b0, 0x22ffad40, 0x1c, 0x23)
        c:/go/src/sort/sort.go:27 +0x88
sort.quickSort(0xd326b0, 0x22ffad40, 0x1c, 0x23, 0xa)
        c:/go/src/sort/sort.go:209 +0x196
sort.quickSort(0xd326b0, 0x22ffad40, 0x0, 0x23, 0xa)
        c:/go/src/sort/sort.go:197 +0xf2
sort.Sort(0xd326b0, 0x22ffad40)
        c:/go/src/sort/sort.go:218 +0x61
cmd/compile/internal/ssa.partitionValues(0x5a447a40, 0x27, 0x75, 0x143301e0, 0x0
, 0x75, 0x2f46ebe0)
        c:/go/src/cmd/compile/internal/ssa/cse.go:287 +0x83
cmd/compile/internal/ssa.cse(0x5d517d90)
        c:/go/src/cmd/compile/internal/ssa/cse.go:49 +0x2d8
cmd/compile/internal/ssa.Compile(0x5d517d90)
        c:/go/src/cmd/compile/internal/ssa/compile.go:70 +0x26c
cmd/compile/internal/gc.buildssa(0x1cf66a80, 0x1, 0x0)
        c:/go/src/cmd/compile/internal/gc/ssa.go:211 +0x8ca
cmd/compile/internal/gc.compileSSA(0x1cf66a80, 0x1)
        c:/go/src/cmd/compile/internal/gc/pgen.go:259 +0x2d
cmd/compile/internal/gc.compileFunctions.func2(0x2c1f68c0, 0x1883af40, 0x1)
        c:/go/src/cmd/compile/internal/gc/pgen.go:323 +0x3b
created by cmd/compile/internal/gc.compileFunctions
        c:/go/src/cmd/compile/internal/gc/pgen.go:321 +0xee

time="2019-04-20T14:23:25+08:00" level=info msg="installing full qt/sql "
github.com/therecipe/qt/widgets
# github.com/therecipe/qt/widgets
runtime: out of memory: cannot allocate 221184-byte block (1681555456 in use)
fatal error: out of memory

runtime stack:
runtime.throw(0xbe2a8d, 0xd)
        c:/go/src/runtime/panic.go:608 +0x64
runtime.largeAlloc(0x34aa0, 0x13810101, 0x44bc20)
        c:/go/src/runtime/malloc.go:1021 +0x107
runtime.mallocgc.func1()
        c:/go/src/runtime/malloc.go:914 +0x39
runtime.systemstack(0x0)
        c:/go/src/runtime/asm_386.s:396 +0x53
runtime.mstart()
        c:/go/src/runtime/proc.go:1229

goroutine 7 [running]:
runtime.systemstack_switch()
        c:/go/src/runtime/asm_386.s:357 fp=0x3995eb98 sp=0x3995eb94 pc=0x44d2e0
runtime.mallocgc(0x34aa0, 0xb8f320, 0x7ebf4201, 0x7ebf4298)
        c:/go/src/runtime/malloc.go:913 +0x676 fp=0x3995ebec sp=0x3995eb98 pc=0x
409cb6
runtime.makeslice(0xb8f320, 0xd2a8, 0xd2a8, 0x7ebf42e8, 0x307ee028, 0x307edcc4)
        c:/go/src/runtime/slice.go:70 +0x59 fp=0x3995ec00 sp=0x3995ebec pc=0x439
409
cmd/compile/internal/ssa.newSparseMap(...)
        c:/go/src/cmd/compile/internal/ssa/sparsemap.go:26
cmd/compile/internal/ssa.newBiasedSparseMap(...)
        c:/go/src/cmd/compile/internal/ssa/biasedsparsemap.go:27
cmd/compile/internal/ssa.numberLines(0x7eb6c630)
        c:/go/src/cmd/compile/internal/ssa/numberlines.go:171 +0x6e6 fp=0x3995ed
2c sp=0x3995ec00 pc=0x5d5086
cmd/compile/internal/ssa.Compile(0x7eb6c630)
        c:/go/src/cmd/compile/internal/ssa/compile.go:70 +0x26c fp=0x39961f04 sp
=0x3995ed2c pc=0x5a896c
cmd/compile/internal/gc.buildssa(0x1b6a4480, 0x1, 0x0)
        c:/go/src/cmd/compile/internal/gc/ssa.go:211 +0x8ca fp=0x39961f98 sp=0x3
9961f04 pc=0xaa6f4a
cmd/compile/internal/gc.compileSSA(0x1b6a4480, 0x1)
        c:/go/src/cmd/compile/internal/gc/pgen.go:259 +0x2d fp=0x39961fcc sp=0x3
9961f98 pc=0xa7ba5d
cmd/compile/internal/gc.compileFunctions.func2(0x1f989d00, 0x13fbe890, 0x1)
        c:/go/src/cmd/compile/internal/gc/pgen.go:323 +0x3b fp=0x39961fe0 sp=0x3
9961fcc pc=0xb17bbb
runtime.goexit()
        c:/go/src/runtime/asm_386.s:1324 +0x1 fp=0x39961fe4 sp=0x39961fe0 pc=0x4
4eb11
created by cmd/compile/internal/gc.compileFunctions
        c:/go/src/cmd/compile/internal/gc/pgen.go:321 +0xee

goroutine 1 [runnable]:
cmd/compile/internal/gc.compileFunctions()
        c:/go/src/cmd/compile/internal/gc/pgen.go:329 +0x136
cmd/compile/internal/gc.Main(0xbfe770)
        c:/go/src/cmd/compile/internal/gc/main.go:651 +0x2381
main.main()
        c:/go/src/cmd/compile/main.go:51 +0x7e

goroutine 6 [running]:
        goroutine running on other thread; stack unavailable
created by cmd/compile/internal/gc.compileFunctions
        c:/go/src/cmd/compile/internal/gc/pgen.go:321 +0xee

time="2019-04-20T14:47:01+08:00" level=info msg="installing full qt/qml "
time="2019-04-20T14:47:04+08:00" level=info msg="installing full qt/websockets "

time="2019-04-20T14:47:05+08:00" level=info msg="installing full qt/xmlpatterns
"
time="2019-04-20T14:47:06+08:00" level=info msg="installing full qt/bluetooth "
time="2019-04-20T14:47:08+08:00" level=info msg="installing full qt/webchannel "

time="2019-04-20T14:47:11+08:00" level=info msg="installing full qt/svg "
```

**Comment by therecipe** [comment]
Hey

Did you use a 32 bit version of Go?
If not, then maybe try to close some background processes to free some RAM before running the setup.
If there is no way to get it working whatsoever, then export `QT_STUB=true` before running the setup.

**Comment by hick** [comment]
> Hey
> 
> Did you use a 32 bit version of Go?
> If not, then maybe try to close some background processes to free some RAM before running the setup.
> If there is no way to get it working whatsoever, then export `QT_STUB=true` before running the setup.

thx a lot,  sorry for my mistake, I switched to 64 bit, and the problem is resolved.   and I monitored the usage of memory was upto nearly 3G but it's passed!
