### ISSUE TITLE
Debugging a crash

### ISSUE THREAD

**Issue by muesli** [therecipe/qt#852]
I'm currently experiencing a seemingly random crash and am struggling to identify its cause.

I'm not suggesting this is a bug in the bindings either, I really have no clue what's causing it so far. However, I'm wondering what's the best approach to debug this. Any advice?

```
KCrash: crashing... crashRecursionCounter = 2
KCrash: Application Name = chirp path = /home/muesli/Sources/go/src/github.com/muesli/chirp/deploy/linux pid = 1984
KCrash: Arguments: /home/muesli/Sources/go/src/github.com/muesli/chirp/deploy/linux/chirp 
KCrash: Attempting to start /usr/lib/drkonqi from kdeinit
sock_file=/run/user/1000/kdeinit5__0
QSocketNotifier: Invalid socket 6 and type 'Read', disabling...
QSocketNotifier: Invalid socket 12 and type 'Read', disabling...
QSocketNotifier: Invalid socket 17 and type 'Read', disabling...
QSocketNotifier: Invalid socket 13 and type 'Read', disabling...
runtime: epollwait on fd 8 failed with 9
fatal error: runtime: netpoll failed
QSocketNotifier: Invalid socket 21 and type 'Read', disabling...

runtime stack:
runtime.throw(0x846d44, 0x17)
        /usr/lib/go/src/runtime/panic.go:617 +0x72
runtime.netpoll(0xc000038501, 0xc00002a501)
        /usr/lib/go/src/runtime/netpoll_epoll.go:75 +0x209
runtime.findrunnable(0xc00002a500, 0x0)
        /usr/lib/go/src/runtime/proc.go:2380 +0x51f
runtime.schedule()
        /usr/lib/go/src/runtime/proc.go:2525 +0x21c
runtime.park_m(0xc000001980)
        /usr/lib/go/src/runtime/proc.go:2605 +0xa1
runtime.mcall(0x800000)
        /usr/lib/go/src/runtime/asm_amd64.s:299 +0x5b

goroutine 1 [syscall, locked to thread]:
github.com/therecipe/qt/gui._Cfunc_QGuiApplication_QGuiApplication_Exec(0xc000000000)
        _cgo_gotypes.go:230 +0x49
github.com/therecipe/qt/gui.QGuiApplication_Exec(...)
        /home/muesli/Sources/go/src/github.com/therecipe/qt/gui/gui-minimal.go:789
main.runApp(0xc0000b8320, 0x1, 0x1, 0xc0000a6390, 0x8)
        /home/muesli/Sources/go/src/github.com/muesli/chirp/chirp.go:59 +0x173
main.main()
        /home/muesli/Sources/go/src/github.com/muesli/chirp/chirp.go:95 +0x17c

goroutine 20 [sleep]:
runtime.goparkunlock(...)
        /usr/lib/go/src/runtime/proc.go:307
time.Sleep(0xdf8475800)
        /usr/lib/go/src/runtime/time.go:105 +0x159
main.(*MessageModel).init.func1(0xc0000ae580)
        /home/muesli/Sources/go/src/github.com/muesli/chirp/messagemodel.go:103 +0x30
created by main.(*MessageModel).init
        /home/muesli/Sources/go/src/github.com/muesli/chirp/messagemodel.go:101 +0x96b

goroutine 21 [sleep]:
runtime.goparkunlock(...)
        /usr/lib/go/src/runtime/proc.go:307
time.Sleep(0xdf8475800)
        /usr/lib/go/src/runtime/time.go:105 +0x159
main.(*MessageModel).init.func1(0xc0000ae740)
        /home/muesli/Sources/go/src/github.com/muesli/chirp/messagemodel.go:103 +0x30
created by main.(*MessageModel).init
        /home/muesli/Sources/go/src/github.com/muesli/chirp/messagemodel.go:101 +0x96b

goroutine 22 [chan receive]:
main.handleEvents(0xc000088120, 0xc0000ae580, 0xc0000ae740)
        /home/muesli/Sources/go/src/github.com/muesli/chirp/events.go:18 +0x55
created by main.setupMastodon
        /home/muesli/Sources/go/src/github.com/muesli/chirp/chirp.go:73 +0x260

goroutine 23 [running]:
        goroutine running on other thread; stack unavailable
created by main.setupMastodon
        /home/muesli/Sources/go/src/github.com/muesli/chirp/chirp.go:74 +0x282

goroutine 52 [sync.Cond.Wait]:
runtime.goparkunlock(...)
        /usr/lib/go/src/runtime/proc.go:307
sync.runtime_notifyListWait(0xc000478180, 0xc00000023a)
        /usr/lib/go/src/runtime/sema.go:510 +0xf9
sync.(*Cond).Wait(0xc000478170)
        /usr/lib/go/src/sync/cond.go:56 +0x9e
net/http.(*http2pipe).Read(0xc000478168, 0xc00062f92f, 0x66d1, 0x66d1, 0x0, 0x0, 0x0)
        /usr/lib/go/src/net/http/h2_bundle.go:3511 +0x8a
net/http.http2transportResponseBody.Read(0xc000478140, 0xc00062f92f, 0x66d1, 0x66d1, 0x0, 0x0, 0x0)
        /usr/lib/go/src/net/http/h2_bundle.go:8375 +0x95
bufio.(*Scanner).Scan(0xc0000d7e90, 0x0)
        /usr/lib/go/src/bufio/scan.go:213 +0xa4
github.com/mattn/go-mastodon.handleReader(0xc000088f00, 0x7f06b4137288, 0xc000478140, 0x7f06b4137288, 0xc000478140)
        /home/muesli/Sources/go/src/github.com/mattn/go-mastodon/streaming.go:47 +0xd4
github.com/mattn/go-mastodon.(*Client).doStreaming(0xc000026100, 0xc00015a500, 0xc000088f00)
        /home/muesli/Sources/go/src/github.com/mattn/go-mastodon/streaming.go:126 +0x21d
github.com/mattn/go-mastodon.(*Client).streaming.func1(0xc000088f00, 0x8c6ca0, 0xc0000a6010, 0xc000026100, 0xc00015a500)
        /home/muesli/Sources/go/src/github.com/mattn/go-mastodon/streaming.go:107 +0x6b
created by github.com/mattn/go-mastodon.(*Client).streaming
        /home/muesli/Sources/go/src/github.com/mattn/go-mastodon/streaming.go:98 +0x3dd

goroutine 16 [IO wait]:
internal/poll.runtime_pollWait(0x7f06c46120b8, 0x72, 0xffffffffffffffff)
        /usr/lib/go/src/runtime/netpoll.go:182 +0x56
internal/poll.(*pollDesc).wait(0xc000128118, 0x72, 0x2800, 0x28dc, 0xffffffffffffffff)
        /usr/lib/go/src/internal/poll/fd_poll_runtime.go:87 +0x9b
internal/poll.(*pollDesc).waitRead(...)
        /usr/lib/go/src/internal/poll/fd_poll_runtime.go:92
internal/poll.(*FD).Read(0xc000128100, 0xc00049e000, 0x28dc, 0x28dc, 0x0, 0x0, 0x0)
        /usr/lib/go/src/internal/poll/fd_unix.go:169 +0x19b
net.(*netFD).Read(0xc000128100, 0xc00049e000, 0x28dc, 0x28dc, 0x203000, 0x0, 0x28cf)
        /usr/lib/go/src/net/fd_unix.go:202 +0x4f
net.(*conn).Read(0xc000010058, 0xc00049e000, 0x28dc, 0x28dc, 0x0, 0x0, 0x0)
        /usr/lib/go/src/net/net.go:177 +0x69
crypto/tls.(*atLeastReader).Read(0xc000358360, 0xc00049e000, 0x28dc, 0x28dc, 0x244, 0x8bc0e0, 0xc0001429e0)
        /usr/lib/go/src/crypto/tls/conn.go:761 +0x60
bytes.(*Buffer).ReadFrom(0xc00004d3d8, 0x8bbfe0, 0xc000358360, 0x465c55, 0x7e36a0, 0x824ea0)
        /usr/lib/go/src/bytes/buffer.go:207 +0xbd
crypto/tls.(*Conn).readFromUntil(0xc00004d180, 0x8bc480, 0xc000010058, 0x5, 0xc000010058, 0x761)
        /usr/lib/go/src/crypto/tls/conn.go:783 +0xf8
crypto/tls.(*Conn).readRecordOrCCS(0xc00004d180, 0x858200, 0xc00004d2b8, 0x5)
        /usr/lib/go/src/crypto/tls/conn.go:590 +0x125
crypto/tls.(*Conn).readRecord(...)
        /usr/lib/go/src/crypto/tls/conn.go:558
crypto/tls.(*Conn).Read(0xc00004d180, 0xc000372000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
        /usr/lib/go/src/crypto/tls/conn.go:1236 +0x137
bufio.(*Reader).Read(0xc000070a20, 0xc0004fe118, 0x9, 0x9, 0xc000142d00, 0x49a72b, 0xc000142d28)
        /usr/lib/go/src/bufio/bufio.go:223 +0x23e
io.ReadAtLeast(0x8bbec0, 0xc000070a20, 0xc0004fe118, 0x9, 0x9, 0x9, 0xc0001aa25d, 0x758, 0xda3)
        /usr/lib/go/src/io/io.go:310 +0x88
io.ReadFull(...)
        /usr/lib/go/src/io/io.go:329
net/http.http2readFrameHeader(0xc0004fe118, 0x9, 0x9, 0x8bbec0, 0xc000070a20, 0x0, 0x0, 0x0, 0x0)
        /usr/lib/go/src/net/http/h2_bundle.go:1476 +0x88
net/http.(*http2Framer).ReadFrame(0xc0004fe0e0, 0xc000159e60, 0x0, 0x0, 0x0)
        /usr/lib/go/src/net/http/h2_bundle.go:1734 +0xa1
net/http.(*http2clientConnReadLoop).run(0xc000142fb8, 0x857ca0, 0xc000127fb8)
        /usr/lib/go/src/net/http/h2_bundle.go:8102 +0x8f
net/http.(*http2ClientConn).readLoop(0xc0004a8600)
        /usr/lib/go/src/net/http/h2_bundle.go:8030 +0x76
created by net/http.(*http2Transport).newClientConn
        /usr/lib/go/src/net/http/h2_bundle.go:7093 +0x637
```

**Comment by muesli** [comment]
Just a heads up, I may have just figured out what's causing this: sounds like an out-of-thread access on the model (and a potential race condition following therefore).

I'd still appreciate any tips & recommendations for catching similar errors. Of course I have firsthand knowledge how tricky it can be to analyze such situations even when you're directly using C++. However I find the stack traces there a bit more helpful than an `epoll` error :smile:

**Comment by therecipe** [comment]
Hey

You could try to export `QT_DEBUG=true` and `QT_DEBUG_CPP=true` to have all qt function calls printed. Then rebuild the app with either qtdeploy or `qtmoc && go run/build` and check the terminal.

But from the log it seems like the crash is caused by `fatal error: runtime: netpoll failed`
which is probably related to https://github.com/golang/go/issues/23517

**Comment by muesli** [comment]
Thanks, I'll give that a shot. The issue you linked to seems a bit confusing. This is running on an up-to-date Arch, and I don't see the netpoll issue with any of my other Go projects.

**Comment by muesli** [comment]
Even with QT_DEBUG & QT_DEBUG_CPP I can only conclude that this seems to happen randomly, sometimes after a minute of running my app, sometimes after hours.

Is there any advice with regards to goroutines and dealing with models? Obviously my main/GUI thread is blocked by `QGuiApplication_Exec()`, so I've set up a go routine that receives events via channels from a backend and tries to update the model for the GUI. It just occurred to me that this may end up running in a different thread and probably causes race conditions. However, I'm not sure how else I would feed data to the blocked GUI thread. Any examples or advice here?

**Comment by muesli** [comment]
As an extra remark, I was following this example here: https://github.com/therecipe/qt/blob/master/internal/examples/quick/listview/personmodel.go

Is this still the right approach?

**Comment by muesli** [comment]
I guess we can close this, as all essential information was already provided by @therecipe in this thread, and it's unlikely to be an issue with the bindings themselves. Thanks for the feedback!
