### ISSUE TITLE
QML async invocation

### ISSUE THREAD

**Issue by ziflex** [therecipe/qt#994]
Hey,

I understand that this question is more about Qt rather than the bindings, but I would like to know whether it's possible to do it with the bindings.
I got a situation where I need to execute some Go code from QML in async manner in order to not block UI thread. 
From C++ examples, I understand you can use Promises for that. Are they supported by these bindings? And is it possible to receive a function pointer as an argument in case I would have to implement promises by myself?

**Comment by therecipe** [comment]
Hey

Yeah, Promises are supported and even though you wouldn't need them for async calls, you can still use them though.
To make it work you will need to use a `*qml.QJSValue` to receive a function pointer and then call the "resolve" or "reject" function from Go.

`main.go`
```go
package main

import (
	"os"
	"time"

	"github.com/therecipe/qt/core"
	"github.com/therecipe/qt/qml"
	"github.com/therecipe/qt/quick"
	"github.com/therecipe/qt/widgets"
)

type Bridge struct {
	core.QObject

	_ func(m *core.QVariant, funcs *qml.QJSValue) `signal:"resolveOrReject,auto"`
}

func (b *Bridge) resolveOrReject(m *core.QVariant, funcs *qml.QJSValue) {
	go func() {
		time.Sleep(3 * time.Second)

		if m.ToBool() {
			funcs.Property2(0).Call([]*qml.QJSValue{qml.NewQJSValue8("resolved from Go")})
		} else {
			funcs.Property2(1).Call([]*qml.QJSValue{qml.NewQJSValue8("rejected from Go")})
		}
	}()
}

func main() {
	core.QCoreApplication_SetAttribute(core.Qt__AA_EnableHighDpiScaling, true)

	app := widgets.NewQApplication(len(os.Args), os.Args)

	view := quick.NewQQuickView(nil)
	view.SetTitle("goroutine Example")
	view.SetResizeMode(quick.QQuickView__SizeRootObjectToView)

	view.RootContext().SetContextProperty("bridge", NewBridge(nil))
	view.SetSource(core.NewQUrl3("qrc:/qml/main.qml", 0))
	view.Show()

	app.Exec()
}
```

`qml/main.qml`
```qml
import QtQuick 2.10				//Item
import QtQuick.Controls 2.3		//Button
import QtQuick.Layouts 1.3		//ColumnLayout

Item {
	width: 250
	height: 200

	ColumnLayout {
		anchors.fill: parent

		Label {
			id: someLabel
			Layout.alignment: Qt.AlignCenter
			color: text == "resolved" ? "green" : "red"
		}

		Button {
			Layout.fillWidth: true
			Layout.alignment: Qt.AlignBottom

			text: "call Go func"

			onClicked: {
				new Promise(function(resolve, reject) {

					bridge.resolveOrReject(someLabel.text != "resolved", [resolve, reject]);

				}).then(result => {
					console.log(result);
					someLabel.text = "resolved";
				}).catch(reason => {
					console.log(reason);
					someLabel.text = "rejected";
				});
			}
		}
	}
}
```

Btw if you move the "Bridge" object into a different thread, then all the calls to it will be async by default and you won't need to start a new go routine inside your callback functions.

```go
package main

import (
	"os"
	"time"

	"github.com/therecipe/qt/core"
	"github.com/therecipe/qt/qml"
	"github.com/therecipe/qt/quick"
	"github.com/therecipe/qt/widgets"
)

type Bridge struct {
	core.QObject

	_ func(m *core.QVariant, funcs *qml.QJSValue) `signal:"resolveOrReject,auto"`
}

func (b *Bridge) resolveOrReject(m *core.QVariant, funcs *qml.QJSValue) {
	time.Sleep(3 * time.Second)

	if m.ToBool() {
		funcs.Property2(0).Call([]*qml.QJSValue{qml.NewQJSValue8("resolved from Go")})
	} else {
		funcs.Property2(1).Call([]*qml.QJSValue{qml.NewQJSValue8("rejected from Go")})
	}
}

func main() {
	core.QCoreApplication_SetAttribute(core.Qt__AA_EnableHighDpiScaling, true)

	app := widgets.NewQApplication(len(os.Args), os.Args)

	view := quick.NewQQuickView(nil)
	view.SetTitle("goroutine Example")
	view.SetResizeMode(quick.QQuickView__SizeRootObjectToView)

	t := core.NewQThread(nil)
	t.Start()
	b := NewBridge(nil)
	b.MoveToThread(t)

	view.RootContext().SetContextProperty("bridge", b)
	view.SetSource(core.NewQUrl3("qrc:/qml/main.qml", 0))
	view.Show()

	app.Exec()
}
```

**Comment by ziflex** [comment]
Awesome! Thank you!

**Comment by ziflex** [comment]
Hey, I've got another problem :)

How can I convert QObject (or plain Go struct) to QJSValue ?
I want to pass an object to a given callback but all existing constructors allow me only to create primitives.

**Comment by therecipe** [comment]
You can use [QJSEngine::newQObject](https://doc.qt.io/qt-5/qjsengine.html#newQObject) to create a QJSValue from an QObject and it's derivatives.
If you use the QQmlApplicationEngine, then just use `(*QQmlApplicationEngine).NewQObject(*QObject)` and if you use the `QQuickView`, then use `(*QQuickView).Engine().NewQObject(*QObject)` instead.

But a plain Go struct to QJSValue/QVariant conversion isn't possible at the moment.
I looked into that some time ago, but I sadly haven't had time to dig deeper.
But I just though about it, and maybe it's possible to make
(`map[string]interface{} -> QJSValue/QVariant`) work real quick.
I will see if I can get something working over the weekend.

**Comment by ziflex** [comment]
I see. I'm doing it manually right now.

But now I'm having this weird issue:

```
QObject::setParent: Cannot set parent, new parent is in a different thread
QObject::setParent: Cannot set parent, new parent is in a different thread
QObject::setParent: Cannot set parent, new parent is in a different thread
<Unknown File>: TypeError: Type error
fatal error: unexpected signal during runtime execution
```

The code [is here](https://github.com/MontFerret/besynes/blob/master/internal/ui/controllers/execution.go#L36).

**Comment by therecipe** [comment]
It seems like `callback.Call` is either not running the js function in the main thread or it's not moving the QJSValues into the main thread before executing the js function. Which probably causes problems when the QJSEngine tries to bind the QJSValue's properties to some of the visual elements living in the main thread.

You can work around this by calling the `callback.Call` function on the main thread though.
To do so you can create a small helper function to call go functions on the main thread again.

I think something like this should work:
```diff
diff --git a/internal/ui/bridges/execution.go b/internal/ui/bridges/execution.go
index e4bad53..2947b6c 100644
--- a/internal/ui/bridges/execution.go
+++ b/internal/ui/bridges/execution.go
@@ -9,4 +9,7 @@ type Execution struct {
 	core.QObject
 
 	_ func(query *core.QJsonObject, callback *qml.QJSValue) `slot:"execute"`
+	_ func(f func())                                        `slot:"runOnMainHelper,auto"`
 }
+
+func (b *Bridge) runOnMainHelper(f func()) { f() }
diff --git a/internal/ui/controllers/execution.go b/internal/ui/controllers/execution.go
index b61c57a..48218c7 100644
--- a/internal/ui/controllers/execution.go
+++ b/internal/ui/controllers/execution.go
@@ -30,8 +30,11 @@ func NewExecution(logger zerolog.Logger, jsEngine *qml.QJSEngine, service *execu
 
 func (ctl *Execution) Connect(bridge *bridges.Execution) {
 	bridge.ConnectExecute(ctl.execute)
+	runOnMainHelper = bridge.RunOnMainHelper
 }
 
+var runOnMainHelper func(f func())
+
 func (ctl *Execution) execute(query *core.QJsonObject, callback *qml.QJSValue) {
 	go func() {
 		defer func() {
@@ -88,6 +91,6 @@ func (ctl *Execution) execute(query *core.QJsonObject, callback *qml.QJSValue) {
 
 		jsv.SetProperty("stats", jsvStats)
 
-		callback.Call([]*qml.QJSValue{jsv})
+		runOnMainHelper(func() { callback.Call([]*qml.QJSValue{jsv}) })
 	}()
 }
```

**Comment by ziflex** [comment]
Thank you! 
Yes, this issue occurs when go runtime spawns a new thread (in my case when I used ``time.Sleep()``).

I'm testing your example, but it seems ``qtmoc`` generates an invalid code when ``auto`` tag is added:

![image](https://user-images.githubusercontent.com/1607148/67569624-5aada900-f6fd-11e9-9589-3bf10800e9bc.png)

**Comment by ziflex** [comment]
Not sure that I did it right. I manually replace ``runOnMainHelper`` with ``RunOnMainHelper`` in the code above.
And now whenever I run the code, I'm getting this:


```bash
fatal: morestack on g0
SIGTRAP: trace trap
PC=0x4060922 m=0 sigcode=1
signal arrived during cgo execution

goroutine 1 [running, locked to thread]:
runtime.abort()
	runtime/asm_amd64.s:859 +0x2 fp=0x7ffeefb7a468 sp=0x7ffeefb7a460 pc=0x4060922
runtime.morestack()
	runtime/asm_amd64.s:416 +0x25 fp=0x7ffeefb7a470 sp=0x7ffeefb7a468 pc=0x405efe5

rax    0x17
rbx    0x7ffeefb7a438
rcx    0x53c6280
rdx    0x0
rdi    0x2
rsi    0x7ffeefb7a3d8
rbp    0xc000354ea0
rsp    0x7ffeefb7a460
r8     0x53c6280
r9     0x0
r10    0x7ffeefb7a438
r11    0x206
r12    0x40
r13    0x40
r14    0xc000131ff8
r15    0x93ada10
rip    0x4060922
rflags 0x216
cs     0x2b
fs     0x0
gs     0x0
```

**Comment by therecipe** [comment]
No problem, you are welcome.
And sorry, it should have been `func (*Execution) runOnMainHelper(f func()) { f() }`.
I updated my comment.

Also replacing `runOnMainHelper` with `RunOnMainHelper` will result in an infinite recursion, that's why it's crashing with 
```
fatal: morestack on g0
SIGTRAP: trace trap
```

**Comment by ziflex** [comment]
Thank you, it works!

**Comment by ziflex** [comment]
The workaround has almost fixed the problem.
But sometimes, I get this error:
```
QObject::~QObject: Timers cannot be stopped from another thread
```

Here is the full stack trace:

```
fatal error: unexpected signal during runtime execution
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x7e03694]

runtime stack:
runtime.throw(0x4b47d72, 0x2a)
	runtime/panic.go:774 +0x72
runtime.sigpanic()
	runtime/signal_unix.go:378 +0x47c

goroutine 5 [syscall]:
runtime.cgocall(0x483ad80, 0xc0001b3db8, 0x8704d10001b0100)
	runtime/cgocall.go:128 +0x5b fp=0xc0001b3d70 sp=0xc0001b3d38 pc=0x400a96b
github.com/therecipe/qt/qml._Cfunc_QJSValue_SetProperty(0x87b86d0, 0x8704d10, 0xb, 0x87f7070)
	_cgo_gotypes.go:1169 +0x45 fp=0xc0001b3db8 sp=0xc0001b3d70 pc=0x4272375
github.com/therecipe/qt/qml.(*QJSValue).SetProperty.func2(0xc0001311c0, 0x8704d10, 0x4b30563, 0xb, 0x4c5e9c0, 0xc0001311c8)
	github.com/therecipe/qt@v0.0.0-20191015155015-04913862338b/qml/qml.go:900 +0xc9 fp=0xc0001b3e00 sp=0xc0001b3db8 pc=0x4288559
github.com/therecipe/qt/qml.(*QJSValue).SetProperty(0xc0001311c0, 0x4b30563, 0xb, 0x4c5e9c0, 0xc0001311c8)
	github.com/therecipe/qt@v0.0.0-20191015155015-04913862338b/qml/qml.go:900 +0x83 fp=0xc0001b3e80 sp=0xc0001b3e00 pc=0x427cc53
github.com/MontFerret/besynes/internal/ui/controllers.(*Execution).execute.func1(0xc00020e770, 0xc0000101a8, 0xc0000101b0)
	github.com/MontFerret/besynes@/internal/ui/controllers/execution.go:98 +0x3d7 fp=0xc0001b3fc8 sp=0xc0001b3e80 pc=0x463dea7
runtime.goexit()
	runtime/asm_amd64.s:1357 +0x1 fp=0xc0001b3fd0 sp=0xc0001b3fc8 pc=0x40616f1
created by github.com/MontFerret/besynes/internal/ui/controllers.(*Execution).execute
	github.com/MontFerret/besynes@/internal/ui/controllers/execution.go:47 +0x53

goroutine 1 [syscall, locked to thread]:
github.com/therecipe/qt/gui._Cfunc_QGuiApplication_QGuiApplication_Exec(0x0)
	_cgo_gotypes.go:13438 +0x49
github.com/therecipe/qt/gui.(*QGuiApplication).Exec(...)
	github.com/therecipe/qt@v0.0.0-20191015155015-04913862338b/gui/gui.go:14525
github.com/MontFerret/besynes/internal/ui.(*Engine).Run(0xc00020e700, 0x0, 0x0)
	github.com/MontFerret/besynes@/internal/ui/engine.go:46 +0x1b3
github.com/MontFerret/besynes/internal.(*Application).Run(...)
	github.com/MontFerret/besynes@/internal/app.go:39
main.main()
	github.com/MontFerret/besynes@/main.go:12 +0x4d
QObject::~QObject: Timers cannot be stopped from another thread
```

**Comment by therecipe** [comment]
I think you will need to wrap all the calls to QJSEngine + the creation and population of the QJSValues inside the main thread helper function as well.
https://github.com/MontFerret/besynes/blob/master/internal/ui/controllers/execution.go#L84-L90
https://github.com/MontFerret/besynes/blob/master/internal/ui/controllers/execution.go#L97-L115

Sorry, it seems like I forgot to do this when I wrote https://github.com/therecipe/qt/issues/994#issuecomment-546197740 as well.

Btw, with https://github.com/therecipe/qt/commit/79e83fbcfd0c6cb569a84fe30d1e69b25acce1c2 you can now write something like this, to simply convert a Go object to an QVariant/QJSValue and vice versa.
It should work with all kinds of Go Types, not only structs but also with maps, slices, arrays and primitives.

```go
package main

import (
	"fmt"
	"os"
	"reflect"

	"github.com/therecipe/qt/core"
	"github.com/therecipe/qt/gui"
	"github.com/therecipe/qt/qml"
)

type SomeGoType struct {
	SomeInt    int
	SomeBool   bool
	SomeString string
	SomeMap    map[string]string
}

func main() {
	gui.NewQGuiApplication(len(os.Args), os.Args)
	e := qml.NewQJSEngine()

	//GoType -> QVariant -> QJSValue

	o := SomeGoType{12345, true, "someString", map[string]string{"ABC": "DEF"}}
	v := core.NewQVariant1(o)
	jsv := e.ToScriptValue(v)

	//QJSValue -> QVariant -> GoType

	var dst SomeGoType
	jsv.ToVariant().ToGoType(&dst)

	//

	fmt.Println(o, dst, reflect.DeepEqual(o, dst))

	gui.QGuiApplication_Exec()
}
```

I also looked into some way to extend the Go/Qml interoperability much further and make it possible to access Go struct methods and maybe most of Qt's api from Qml/JS as well.

**Comment by ziflex** [comment]
> I think you will need to wrap all the calls to QJSEngine + the creation and population of the QJSValues inside the main thread helper function as well.
> https://github.com/MontFerret/besynes/blob/master/internal/ui/controllers/execution.go#L84-L90
> https://github.com/MontFerret/besynes/blob/master/internal/ui/controllers/execution.go#L97-L115
> 
> Sorry, it seems like I forgot to do this when I wrote [#994 (comment)](https://github.com/therecipe/qt/issues/994#issuecomment-546197740) as well.

Oh, ok. Do I need to create these helper function for each bridge I create? Or maybe it Would be sufficient to create one "helper" bridge?

> Btw, with [79e83fb](https://github.com/therecipe/qt/commit/79e83fbcfd0c6cb569a84fe30d1e69b25acce1c2) you can now write something like this, to simply convert a Go object to an QVariant/QJSValue and vice versa.
> It should work with all kinds of Go Types, not only structs but also with maps, slices, arrays and primitives.
> 
> ```go
> package main
> 
> import (
> 	"fmt"
> 	"os"
> 	"reflect"
> 
> 	"github.com/therecipe/qt/core"
> 	"github.com/therecipe/qt/gui"
> 	"github.com/therecipe/qt/qml"
> )
> 
> type SomeGoType struct {
> 	SomeInt    int
> 	SomeBool   bool
> 	SomeString string
> 	SomeMap    map[string]string
> }
> 
> func main() {
> 	gui.NewQGuiApplication(len(os.Args), os.Args)
> 	e := qml.NewQJSEngine()
> 
> 	//GoType -> QVariant -> QJSValue
> 
> 	o := SomeGoType{12345, true, "someString", map[string]string{"ABC": "DEF"}}
> 	v := core.NewQVariant1(o)
> 	jsv := e.ToScriptValue(v)
> 
> 	//QJSValue -> QVariant -> GoType
> 
> 	var dst SomeGoType
> 	jsv.ToVariant().ToGoType(&dst)
> 
> 	//
> 
> 	fmt.Println(o, dst, reflect.DeepEqual(o, dst))
> 
> 	gui.QGuiApplication_Exec()
> }
> ```
> 
> I also looked into some way to extend the Go/Qml interoperability much further and make it possible to access Go struct methods and maybe most of Qt's api from Qml/JS as well.

Awesome! That's a great feature!

**Comment by ziflex** [comment]
Ehh, this is getting messy. 
I wonder whether it makes sense to try to use Qt's async primitives like Future and FutureWatcher?

**Comment by therecipe** [comment]
>Oh, ok. Do I need to create these helper functions for each bridge I create? Or maybe it would be sufficient to create one "helper" bridge?

You can just create one main thread helper bridge and then just use that every time you need to have something run on the main thread. So no, there is no need to create these functions for each of your `bridges`/`moc structs`.
I will also see if I can add the convenience "RunOnMainThread" function to the core package or some other package in the future as well. (Probably when I push the changes for the better Go/Qml interoperability)

>I wonder whether it makes sense to try to use Qt's async primitives like Future and FutureWatcher?

These classes are sadly not available atm, I can look into what's needed to get them working though. However, I would probably just try to use Go's primitives if possible.

**Comment by ziflex** [comment]
Ok, thanks! I'm gonna try it.

Btw, that would be nice if ``. ToGoType`` respected ``json`` tags.

**Comment by ziflex** [comment]
That works, thanks! But, I would really like ``json`` tags be used by the helpers.

**Comment by therecipe** [comment]
Supporting `json` tags is a great idea, I will add it.
I'm quite busy atm though, but maybe I can get it done over the weekend.

**Comment by ziflex** [comment]
Great!
I will be waiting for it.
Either ``json`` or a custom tag, like, ``qml``.

**Comment by therecipe** [comment]
@ziflex sorry for the wait, json tags should now be supported with the latest version.

I also pushed some changes, that make working with Qml much more pleasant https://github.com/therecipe/qt/commit/3738bb93204319792fb73ddef42e539552781543

For example, something like this should work now:
```go
package main

import (
	"fmt"
	"os"
	"reflect"

	"github.com/therecipe/qt/core"
	"github.com/therecipe/qt/qml"
	"github.com/therecipe/qt/widgets"
)

type SomeMocStruct struct {
	core.QObject
}

func (*SomeMocStruct) SomeGoFunction(a string, b map[string]string, c SomeGoType, d func() string) {
	fmt.Println("inside Go:", a, b, c, d())
}

type SomeGoType struct {
	SomeInt    int  `json:"someInt"`
	SomeBool   bool `json:"someBool"`
	SomeString string
	SomeMap    map[string]string
}

func main() {
	widgets.NewQApplication(len(os.Args), os.Args)
	e := qml.NewQJSEngine()

	//GoType -> QJSValue

	o := SomeGoType{12345, true, "someString", map[string]string{"ABC": "DEF"}}
	jsv := e.NewGoType(o)

	//QJSValue -> GoType

	var dst SomeGoType
	e.ToGoType(jsv, &dst)

	fmt.Println(o, dst, reflect.DeepEqual(o, dst))

	//

	//when converting go functions, the first argument can be used to register the function inside the engine by name
	e.NewGoType("someFunction", func(in string) string { return "the " + in })

	//if you don't want to name the function, then you will need to make it accessible by passing it to Qml/JS in some other way
	someAnonymousFunction := e.NewGoType(func() { println("inside Go: from the anonymous function") })

	//for example like this, but properties, signals or slots should work as well
	e.GlobalObject().SetProperty("someAnonymousFunction", someAnonymousFunction)

	e.Evaluate(`
		var o = main.NewSomeMocStruct();
		o.SomeGoFunction("someString", {"Some":"Map"}, {"someInt": 123, "someBool": true, "SomeString": "thisIsAString", SomeMap: {"Some":"MapAgain"}}, function() { return "string returned rom JS function"});

		var b = widgets.NewQPushButton();
		b.SetText("click me");
		b.ConnectClicked(function(){ o.SomeGoFunction("from " + someFunction("button")); someAnonymousFunction() });
		b.Show();
		`, "", 0)

	widgets.QApplication_Exec()
}
```

**Comment by ziflex** [comment]
Fantastic! Thank you for the update!
With the latest updates and your recommendations I do not have any issues anymore, so I'm closing it.

**Comment by ziflex** [comment]
Tags are working great! But, embedded structs are not handled like they would be by json marshaller - they become nested objects with capital letters (because there is not way to set tags for them).

**Comment by therecipe** [comment]
I just looked into this and it seems to work.
(empty structs are encoded differently though)
Could you provide some example so I reproduce it?

```go
package main

import (
	"encoding/json"
	"fmt"
	"os"
	"reflect"

	"github.com/therecipe/qt/core"
	"github.com/therecipe/qt/qml"
	"github.com/therecipe/qt/widgets"
)

type CloudWatchEvent struct {
	Version    string            `json:"version"`
	ID         string            `json:"id"`
	DetailType string            `json:"detail-type"`
	Source     string            `json:"source"`
	AccountID  string            `json:"account"`
	Time       string            `json:"time"`
	Region     string            `json:"region"`
	Resources  []string          `json:"resources"`
	Detail     CloudWatchDetails `json:"detail"`
}

type CloudWatchDetails struct {
	Detail struct {
		StatusCode           string `json:"statusCode"`
		AutoScalingGroupName string `json:"autoScalingGroupName"`
		ActivityID           string `json:"activityId"`
		Details              struct {
			AvailabilityZone string `json:"availability Zone"`
			SubnetID         string `json:"Subnet ID"`
		} `json:"Details"`
		RequestID     string `json:"RequestId"`
		EndTime       string `json:"EndTime"`
		EC2InstanceID string `json:"EC2InstanceId"`
		StartTime     string `json:"StartTime"`
		Cause         string `json:"Cause"`
	} `json:"detail"`
}

func main() {

	widgets.NewQApplication(len(os.Args), os.Args)
	engine := qml.NewQJSEngine()

	println("---- EMPTY ----")
	ee, _ := json.Marshal(&CloudWatchEvent{})
	println(core.QJsonDocument_FromVariant(engine.NewGoType(&CloudWatchEvent{}).ToVariant()).ToJson().ConstData())
	println(string(ee))
	println("---- EMPTY ----")

	println("---- FULL ----")
	ce := CloudWatchEvent{}
	json.Unmarshal([]byte(`{
		    "account": "1",
		    "detail": {
		        "detail": {
		            "Cause": "2",
		            "Details": {
		                "Subnet ID": "3",
		                "availability Zone": "4"
		            },
		            "EC2InstanceId": "5",
		            "EndTime": "6",
		            "RequestId": "7",
		            "StartTime": "8",
		            "activityId": "9",
		            "autoScalingGroupName": "10",
		            "statusCode": "11"
		        }
		    },
		    "detail-type": "12",
		    "id": "13",
		    "region": "14",
		    "resources": [
		    ],
		    "source": "15",
		    "time": "16",
		    "version": "17"
		}`), &ce)
	fmt.Println(ce)
	println("---- FULL ----")

	ce2 := CloudWatchEvent{}
	ce3 := CloudWatchEvent{}

	println("---- QJSVALUE ----")
	{
		gt := engine.NewGoType(ce)                                                                   //CloudWatchEvent -> QJSVALUE
		engine.ToGoType(gt, &ce2)                                                                    //QJSVALUE -> CloudWatchEvent2
		js := core.QJsonDocument_FromVariant(engine.NewGoType(ce2).ToVariant()).ToJson().ConstData() //CloudWatchEvent2 -> JSON

		json.Unmarshal([]byte(js), &ce3) //JSON -> CloudWatchEvent3
		println("are equal?", reflect.DeepEqual(ce, ce2), reflect.DeepEqual(ce2, ce3))

		fmt.Println(ce)
		fmt.Println(ce2)
		fmt.Println(ce3)
	}
	println("---- QJSVALUE ----")

	ce2 = CloudWatchEvent{}
	ce3 = CloudWatchEvent{}

	println("---- QVARIANT ----")
	{
		gt := core.NewQVariant1(ce)                                                       //CloudWatchEvent -> QVARIANT
		gt.ToGoType(&ce2)                                                                 //QVARIANT -> CloudWatchEvent2
		js := core.QJsonDocument_FromVariant(core.NewQVariant1(ce2)).ToJson().ConstData() //CloudWatchEvent2 -> JSON

		json.Unmarshal([]byte(js), &ce3) //JSON -> CloudWatchEvent3
		println("are equal?", reflect.DeepEqual(ce, ce2), reflect.DeepEqual(ce2, ce3))

		fmt.Println(ce)
		fmt.Println(ce2)
		fmt.Println(ce3)
	}
	println("---- QVARIANT ----")
}
```

**Comment by ziflex** [comment]
Sorry, for the late response.
I put my work on hold that project.
Could you take a look at [this](https://github.com/MontFerret/besynes/blob/master/internal/ui/connector.go#L96) line? Am I doing something wrong?
